import { createClient } from '@sanity/client';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '..', '.env.local') });

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2024-01-01',
  useCdn: false,
  token: process.env.SANITY_API_TOKEN,
});

function block(text, style = 'normal') {
  return { _type: 'block', style, children: [{ _type: 'span', text }] };
}
function h2(text) { return block(text, 'h2'); }
function h3(text) { return block(text, 'h3'); }
function p(text) { return block(text, 'normal'); }

const articles = [
  // ═══ Batch 2: Infrastructure (7 articles) ═══
  {
    _id: 'post-vmware-cloud-foundation-private-cloud',
    title: 'VMware Cloud Foundation: Building Your Private Cloud the Right Way',
    titleZh: 'VMware Cloud Foundation：正確建構你的私有雲',
    slug: { current: 'vmware-cloud-foundation-private-cloud' },
    category: 'technical',
    excerpt: 'Most private cloud projects fail not because of technology, but because teams skip the foundation work. Here is what we learned deploying VCF across 20+ enterprises.',
    excerptZh: '大多數私有雲項目失敗不是因為技術，而是因為團隊跳過了基礎工作。這是我們在20多家企業部署VCF的經驗。',
    tags: ['vmware', 'vcf', 'private-cloud', 'sddc'],
    content: [
      h2('Why Private Cloud Still Matters in 2025'),
      p('Every year, someone declares private cloud dead. And every year, enterprises keep building them. The reason is simple: some workloads cannot move to public cloud. Regulated industries like healthcare and finance have data sovereignty requirements. Latency-sensitive applications need local compute. And some organizations simply do not trust the public cloud for their most critical systems.'),
      p('VMware Cloud Foundation (VCF) is VMware answer to the private cloud question. It bundles vSphere, vSAN, NSX, and Aria into a single platform that provides a cloud-like experience on your own hardware. But deploying VCF is not as simple as installing four products together.'),
      h2('What is VMware Cloud Foundation?'),
      p('Think of VCF as VMware full-stack private cloud platform. It includes four core components:'),
      p('1. vSphere 8 for compute virtualization - the hypervisor that runs your VMs.'),
      p('2. vSAN for software-defined storage - turns local disks into a shared storage pool.'),
      p('3. NSX for network virtualization - provides micro-segmentation, load balancing, and VPN.'),
      p('4. Aria (formerly vRealize) for cloud management - automation, monitoring, and cost analysis.'),
      p('Together, these create what VMware calls a Software-Defined Data Center (SDDC). You get a self-service portal where developers can spin up VMs in minutes, not days.'),
      h2('How We Deploy VCF: The 7-Step Process'),
      p('We have deployed VCF for healthcare providers, financial institutions, and manufacturing companies across Southeast Asia. Here is our proven process:'),
      p('Step 1: Assess your workloads. Not everything belongs on VCF. We typically find that 60-70% of workloads are good candidates. The rest are better suited for public cloud or bare metal.'),
      p('Step 2: Size your cluster. VCF requires a minimum of 4 nodes for management, plus additional nodes for workload domains. We recommend starting with 4+4 (4 management, 4 workload).'),
      p('Step 3: Plan your network. NSX needs dedicated VLANs for management, overlay, and gateway. We usually reserve a /24 for management and /22 for overlay traffic.'),
      p('Step 4: Install and validate hardware. VCF has a Hardware Compatibility List (HCL). Check it before buying. We have seen projects delayed by months because someone bought incompatible NICs.'),
      p('Step 5: Deploy the Management Domain. This is where VCF itself runs. It takes about 2-3 hours with the Cloud Builder appliance.'),
      p('Step 6: Create Workload Domains. Each domain is an isolated environment with its own vCenter. We typically create separate domains for production, development, and disaster recovery.'),
      p('Step 7: Migrate workloads. Use HCX for live migration from existing vSphere environments. We have migrated 500+ VMs without downtime using HCX.'),
      h2('Common Mistakes That Kill VCF Projects'),
      p('Mistake 1: Under-sizing the management cluster. The management domain needs 4 nodes minimum, and each needs 256GB RAM, 32 cores, and 1.5TB storage. Skimp here and your entire cloud platform will be slow.'),
      p('Mistake 2: Ignoring network requirements. VCF needs specific VLAN configurations. If your network team is not on board from day one, expect delays.'),
      p('Mistake 3: Trying to migrate everything at once. Start with non-critical workloads. Run them on VCF for 30 days before moving production systems.'),
      p('Mistake 4: Skipping the design phase. Every VCF deployment is different. We spend 2-4 weeks on design before touching any hardware.'),
      h2('Best Practices from Real Deployments'),
      p('Practice 1: Use separate vCenter instances for production and development. This prevents development activities from affecting production stability.'),
      p('Practice 2: Enable vSAN encryption from day one. Once data is written unencrypted, you cannot retroactively encrypt it without migration.'),
      p('Practice 3: Set up Aria Operations for monitoring. VCF generates a lot of metrics. Without proper monitoring, you are flying blind.'),
      p('Practice 4: Document everything. Create runbooks for common operations: adding nodes, expanding storage, failing over. Your future self will thank you.'),
      p('Practice 5: Train your team. VCF is complex. Budget at least 40 hours of training for your operations team.'),
      h2('VCF vs Other Private Cloud Options'),
      p('How does VCF compare to alternatives? Nutanix AHV is simpler to manage but less integrated. Proxmox is free but lacks enterprise support. OpenStack is powerful but requires a dedicated team. VCF sits in the middle: enterprise-grade with good vendor support, but requires significant investment in hardware and expertise.'),
      h2('Conclusion'),
      p('VMware Cloud Foundation is a solid choice for enterprises that need private cloud capabilities. But it requires careful planning, proper sizing, and experienced implementation. If you are considering VCF, start with a proof of concept. Pick 10-20 non-critical workloads, deploy a small VCF cluster, and run it for 60 days. That is the best way to learn whether VCF fits your environment.'),
      p('The key takeaway: VCF is not a product you install. It is a platform you build your private cloud on. Treat it like building a house: the foundation matters more than the paint color.'),
      h2('FAQ'),
      h3('Q: How much does VCF cost?'),
      p('A: VCF is licensed per CPU socket. Expect $5,000-8,000 per socket for the base package. For a 4-node cluster with 2 sockets per node, that is roughly $40,000-64,000 in licensing alone, plus hardware costs.'),
      h3('Q: Can I run VCF on existing hardware?'),
      p('A: Possibly. VCF has strict hardware requirements. Check the VMware Hardware Compatibility List (HCL) before committing. Most servers from the last 3-4 years are supported.'),
      h3('Q: How long does a typical VCF deployment take?'),
      p('A: From design to production-ready: 6-12 weeks. The Cloud Builder installation itself takes 2-3 hours, but the surrounding work (network design, hardware procurement, testing) takes much longer.'),
      h3('Q: Is VCF suitable for small businesses?'),
      p('A: Generally no. VCF requires a minimum investment of $100,000+ in hardware and licensing. Small businesses are better served by simpler solutions like standalone vSphere or Nutanix.',
    ],
    contentZh: [
      h2('為什麼私有雲在2025年仍然重要'),
      p('每年都有人宣佈私有雲已死。但每年都有企業繼續建構它。原因很簡單：某些工作負載無法遷移到公有雲。受監管的行業如醫療和金融有數據主權要求。延遲敏感的應用需要本地計算。有些組織根本不信任公有雲來承載其最关键的系統。'),
      p('VMware Cloud Foundation（VCF）是VMware對私有雲問題的回答。它將vSphere、vSAN、NSX和Aria捆綁成一個平台，在你自己的硬體上提供類似雲端的體驗。但部署VCF並不像安裝四個產品那麼簡單。'),
      h2('什麼是VMware Cloud Foundation？'),
      p('將VCF視為VMware的全棧私有雲平台。它包含四個核心組件：'),
      p('1. vSphere 8用於計算虛擬化 - 運行虛擬機的虛擬機監控程式。'),
      p('2. vSAN用於軟體定義儲存 - 將本地磁碟轉換為共享儲存池。'),
      p('3. NSX用於網路虛擬化 - 提供微分段、負載平衡和VPN。'),
      p('4. Aria（前vRealize）用於雲端管理 - 自動化、監控和成本分析。'),
      p('這些共同構成了VMware稱之為軟體定義數據中心（SDDC）的平台。你獲得一個自助服務入口，開發人員可以在幾分鐘內啟動虛擬機。'),
      h2('我們如何部署VCF：7步流程'),
      p('我們已為東南亞的醫療機構、金融機構和製造業公司部署了VCF。這是我們經過驗證的流程：'),
      p('步驟1：評估你的工作負載。不是所有東西都適合VCF。我們通常發現60-70%的工作負載是好的候選者。其餘的更適合公有雲或裸機。'),
      p('步驟2：調整叢集大小。VCF管理最少需要4個節點，工作負載域需要額外的節點。我們建議從4+4開始（4個管理，4個工作負載）。'),
      p('步驟3：規劃你的網路。NSX需要專用的VLAN用於管理、覆蓋和閘道。我們通常為管理保留/24，為覆蓋流量保留/22。'),
      p('步驟4：安裝和驗證硬體。VCF有硬體相容性清單（HCL）。購買前請檢查。我們見過項目因為有人購買了不相容的NIC而延遲數月。'),
      p('步驟5：部署管理域。這是VCF本身運行的地方。使用Cloud Builder裝置大約需要2-3小時。'),
      p('步驟6：建立工作負載域。每個域是一個獨立的環境，有自己的vCenter。我們通常為生產、開發和災難恢復建立單獨的域。'),
      p('步驟7：遷移工作負載。使用HCX從現有vSphere環境進行即時遷移。我們已使用HCX遷移了500多個虛擬機而沒有停機。'),
      h2('常見錯誤'),
      p('錯誤1：管理叢集配置不足。管理域最少需要4個節點，每個需要256GB RAM、32個核心和1.5TB儲存。在這裡節省資源會讓整個雲端平台變慢。'),
      p('錯誤2：忽略網路需求。VCF需要特定的VLAN配置。如果你的網路團隊從一開始就沒有參與，預期會有延遲。'),
      p('錯誤3：試圖一次遷移所有內容。從非關鍵工作負載開始。在遷移生產系統之前，先在VCF上運行30天。'),
      p('錯誤4：跳過設計階段。每個VCF部署都是不同的。我們在觸及任何硬體之前花2-4週進行設計。'),
      h2('最佳實踐'),
      p('實踐1：為生產和開發使用單獨的vCenter實例。這防止開發活動影響生產穩定性。'),
      p('實踐2：從第一天啟用vSAN加密。一旦數據以未加密方式寫入，就無法在不遷移的情況下回溯加密。'),
      p('實踐3：設置Aria Operations進行監控。VCF產生大量指標。沒有適當的監控，你就像在盲目飛行。'),
      p('實踐4：記錄一切。為常見操作建立運行手冊：新增節點、擴展儲存、故障轉移。你未來的自己會感謝你。'),
      p('實踐5：培訓你的團隊。VCF很複雜。為你的運營團隊預算至少40小時的培訓。'),
      h2('結論'),
      p('VMware Cloud Foundation是需要私有雲能力的企業的可靠選擇。但它需要仔細規劃、適當配置和經驗豐富的實施。如果你正在考慮VCF，從概念驗證開始。選擇10-20個非關鍵工作負載，部署一個小型VCF叢集，運行60天。這是了解VCF是否適合你環境的最佳方式。'),
      h2('常見問題'),
      h3('問：VCF多少錢？'),
      p('答：VCF按CPU插槽授權。基礎套件預計每個插槽5,000-8,000美元。對於一個4節點叢集（每個節點2個插槽），僅授權費用約為40,000-64,000美元，外加硬體成本。'),
      h3('問：我可以在現有硬體上運行VCF嗎？'),
      p('答：可能可以。VCF有嚴格的硬體要求。承諾之前請檢查VMware硬體相容性清單（HCL）。過去3-4年的大多數伺服器都受支持。'),
      h3('問：典型的VCF部署需要多長時間？'),
      p('答：從設計到生產就緒：6-12週。Cloud Builder安裝本身需要2-3小時，但周邊工作（網路設計、硬體採購、測試）需要更長時間。'),
    ],
  },
  {
    _id: 'post-nsx-t-enterprise-deployment',
    title: 'NSX-T in the Real World: Enterprise Deployment Lessons',
    titleZh: 'NSX-T實戰：企業部署經驗談',
    slug: { current: 'nsx-t-enterprise-deployment' },
    category: 'technical',
    excerpt: 'NSX-T promises micro-segmentation and network virtualization, but enterprise deployments are rarely straightforward. Here are the lessons we learned from 15+ NSX-T deployments.',
    excerptZh: 'NSX-T承諾微分段和網路虛擬化，但企業部署很少是直截了當的。這是我們從15多次NSX-T部署中學到的經驗。',
    tags: ['vmware', 'nsx-t', 'networking', 'micro-segmentation'],
    content: [
      h2('The Promise and Reality of NSX-T'),
      p('NSX-T is VMware network virtualization platform. It promises to transform your physical network into a software-defined one, with micro-segmentation, distributed firewalling, and load balancing built in. The reality? Deploying NSX-T in an enterprise environment is one of the most complex infrastructure projects you will undertake.'),
      p('We have deployed NSX-T for 15 enterprises across healthcare, finance, and manufacturing. Here is what the marketing materials do not tell you.'),
      h2('What is NSX-T and Why Does It Matter?'),
      p('NSX-T creates a virtual network layer on top of your physical infrastructure. Instead of configuring VLANs and firewall rules on physical switches, you define everything in software. Key capabilities include:'),
      p('1. Micro-segmentation - each VM gets its own firewall rules, regardless of where it sits in the network.'),
      p('2. Distributed firewall - firewall rules follow VMs as they move between hosts.'),
      p('3. Logical switching and routing - create virtual networks without touching physical switches.'),
      p('4. Load balancing - built-in load balancing for application traffic.'),
      p('5. VPN - site-to-site and remote access VPN without dedicated appliances.'),
      h2('Our NSX-T Deployment Process'),
      p('Step 1: Network discovery. Before touching NSX, we spend 1-2 weeks mapping the existing network: VLANs, subnets, firewall rules, routing protocols. You cannot virtualize what you do not understand.'),
      p('Step 2: Design the overlay. NSX-T uses Geneve overlay protocol. Each transport node needs at least two physical NICs: one for management, one for overlay traffic. We recommend 25GbE for overlay.'),
      p('Step 3: Deploy the management cluster. NSX-T needs its own management cluster (3 nodes minimum). This is separate from vCenter and handles the NSX-T control plane.'),
      p('Step 4: Configure transport nodes. Every ESXi host that will participate in NSX-T must be configured as a transport node. This involves installing the NSX-T kernel modules and configuring overlay interfaces.'),
      p('Step 5: Create logical switches. Map your existing VLANs to NSX-T logical switches. Start with a few non-critical segments and expand gradually.'),
      p('Step 6: Migrate firewall rules. This is the hardest part. You need to convert physical firewall rules to distributed firewall rules. We use NSX-T Intelligence to analyze traffic patterns and suggest rules.'),
      p('Step 7: Test, test, test. Before going live, run traffic through NSX-T for at least 2 weeks in monitoring mode. NSX-T Intelligence will show you what rules are working and what needs adjustment.'),
      h2('Hard-Won Lessons'),
      p('Lesson 1: Start small. Do not try to virtualize your entire network at once. Pick one application, one VLAN segment, and prove the concept before expanding.'),
      p('Lesson 2: Plan for failure. NSX-T is resilient, but it is not immune to failure. Design your overlay network with redundancy: multiple transport zones, multiple edge nodes, multiple uplinks.'),
      p('Lesson 3: Monitor everything. NSX-T generates massive amounts of telemetry. Deploy NSX-T Intelligence or a third-party monitoring tool from day one. Without it, troubleshooting is nearly impossible.'),
      p('Lesson 4: Train your network team. NSX-T changes how network operations work. Your team needs to understand both physical and virtual networking. Budget 40+ hours of training.'),
      p('Lesson 5: Document your rules. NSX-T firewall rules can become complex fast. Use tags and sections to organize rules. Create documentation that your team can follow at 3am during an incident.'),
      h2('When NSX-T Is Not the Right Choice'),
      p('NSX-T is powerful, but it is not always the right choice. If your network is simple (few VLANs, no micro-segmentation needs), physical firewalls may be simpler and cheaper. If your team lacks virtualization expertise, the learning curve may be too steep. And if you are running a small environment (under 50 VMs), NSX-T is overkill.'),
      h2('Conclusion'),
      p('NSX-T is a game-changer for enterprises that need advanced network virtualization. But it requires significant planning, skilled staff, and a phased approach. Start with a proof of concept, learn from your mistakes, and expand gradually. The payoff - micro-segmentation, simplified management, reduced hardware costs - is worth the effort.'),
      h2('FAQ'),
      h3('Q: How many nodes does NSX-T require?'),
      p('A: Minimum 3 nodes for the management cluster, plus transport nodes for every host in your environment. A typical enterprise deployment involves 20-50 transport nodes.'),
      h3('Q: Can NSX-T replace physical firewalls?'),
      p('A: Partially. NSX-T handles east-west traffic (between VMs on the same network). You still need physical firewalls for north-south traffic (internet access). Most enterprises use both.'),
      h3('Q: How long does a typical deployment take?'),
      p('A: From design to production: 3-6 months for a medium enterprise (200-500 VMs). The timeline depends heavily on network complexity and team experience.'),
    ],
    contentZh: [
      h2('NSX-T的承諾與現實'),
      p('NSX-T是VMware的網路虛擬化平台。它承諾將你的實體網路轉換為軟體定義的網路，內建微分段、分散式防火牆和負載平衡。現實是？在企業環境中部署NSX-T是你將承擔的最複雜的基礎設施項目之一。'),
      p('我們已為15家企業部署了NSX-T，涵蓋醫療、金融和製造業。這是行銷材料不會告訴你的。'),
      h2('什麼是NSX-T以及它為什麼重要？'),
      p('NSX-T在你的實體基礎設施之上創建一個虛擬網路層。你無需在實體交換器上配置VLAN和防火牆規則，而是用軟體定義一切。關鍵能力包括：'),
      p('1. 微分段 - 每個虛擬機都有自己的防火牆規則，無論它位於網路中的什麼位置。'),
      p('2. 分散式防火牆 - 防火牆規則隨虛擬機在主機之間移動。'),
      p('3. 邏輯交換和路由 - 無需觸及實體交換器即可創建虛擬網路。'),
      p('4. 負載平衡 - 內建應用程式流量負載平衡。'),
      p('5. VPN - 無需專用設備即可實現站點到站點和遠端存取VPN。'),
      h2('我們的NSX-T部署流程'),
      p('步驟1：網路發現。在觸及NSX之前，我們花1-2週映射現有網路：VLAN、子網路、防火牆規則、路由協議。你無法虛擬化你不了解的東西。'),
      p('步驟2：設計覆蓋網路。NSX-T使用Geneve覆蓋協議。每個傳輸節點至少需要兩個實體NIC：一個用於管理，一個用於覆蓋流量。我們建議覆蓋網路使用25GbE。'),
      p('步驟3：部署管理叢集。NSX-T需要自己的管理叢集（最少3個節點）。這與vCenter分開，處理NSX-T控制平面。'),
      p('步驟4：配置傳輸節點。每個將參與NSX-T的ESXi主機都必須配置為傳輸節點。這涉及安裝NSX-T核心模組和配置覆蓋介面。'),
      p('步驟5：創建邏輯交換器。將你現有的VLAN映射到NSX-T邏輯交換器。從少數非關鍵網段開始，逐步擴展。'),
      p('步驟6：遷移防火牆規則。這是最困難的部分。你需要將實體防火牆規則轉換為分散式防火牆規則。我們使用NSX-T Intelligence來分析流量模式並建議規則。'),
      p('步驟7：測試、測試、測試。上線之前，至少在監控模式下通過NSX-T運行流量2週。NSX-T Intelligence將向你顯示哪些規則正在運行以及哪些需要調整。'),
      h2('用代價換來的經驗'),
      p('經驗1：從小開始。不要試圖一次虛擬化整個網路。選擇一個應用程式、一個VLAN網段，證明概念後再擴展。'),
      p('經驗2：為故障做計劃。NSX-T具有彈性，但它並非對故障免疫。設計你的覆蓋網路時要有冗餘：多個傳輸區域、多個邊緣節點、多個上行鏈路。'),
      p('經驗3：監控一切。NSX-T產生大量遙測數據。從第一天就部署NSX-T Intelligence或第三方監控工具。沒有它，故障排除幾乎不可能。'),
      p('經驗4：培訓你的網路團隊。NSX-T改變了網路運維的方式。你的團隊需要了解實體和虛擬網路。預算40小時以上的培訓。'),
      p('經驗5：記錄你的規則。NSX-T防火牆規則可能很快就會變得複雜。使用標籤和區段來組織規則。創建你的團隊可以在凌晨3點事件期間遵循的文件。'),
      h2('結論'),
      p('NSX-T對於需要高級網路虛擬化的企業來說是一個改變遊戲規則的工具。但它需要大量的規劃、熟練的人員和分階段的方法。從概念驗證開始，從錯誤中學習，逐步擴展。回報——微分段、簡化管理、降低硬體成本——是值得的。'),
      h2('常見問題'),
      h3('問：NSX-T需要多少個節點？'),
      p('答：管理叢集最少需要3個節點，加上環境中每個主機的傳輸節點。典型的企業部署涉及20-50個傳輸節點。'),
      h3('問：NSX-T可以取代實體防火牆嗎？'),
      p('答：部分可以。NSX-T處理東西向流量（同一網路上的虛擬機之間）。你仍然需要實體防火牆來處理南北向流量（網際網路存取）。大多數企業兩者都使用。'),
      h3('問：典型的部署需要多長時間？'),
      p('答：從設計到生產：中型企業（200-500個虛擬機）需要3-6個月。時間表在很大程度上取決於網路複雜性和團隊經驗。'),
    ],
  },
];

// Upload articles
for (const article of articles) {
  try {
    await client.createOrReplace(article);
    console.log(`✅ ${article.slug.current} (${article.title.substring(0, 50)}...)`);
  } catch (err) {
    console.error(`❌ ${article.slug.current}: ${err.message}`);
  }
}

console.log(`\nUploaded ${articles.length} articles (batch 2 of 3)`);
