import { createClient } from '@sanity/client';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const envContent = readFileSync(resolve(process.cwd(), '.env.local'), 'utf-8');
const tokenMatch = envContent.match(/SANITY_API_TOKEN=(.+)/);
const token = tokenMatch ? tokenMatch[1].trim() : null;

if (!token) {
  console.error('SANITY_API_TOKEN not found in .env.local');
  process.exit(1);
}

const client = createClient({
  projectId: 'r6ztl1oq',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token,
  useCdn: false,
});

function block(text, style = 'normal') {
  return { _type: 'block', style, children: [{ _type: 'span', text }] };
}
function h2(text) { return block(text, 'h2'); }
function h3(text) { return block(text, 'h3'); }
function para(text) { return block(text, 'normal'); }

// ============================================================
// ARTICLE 5: vmware-ha-vs-ft-comparison
// ============================================================
const article5 = {
  _id: 'post-vmware-ha-vs-ft-comparison',
  _type: 'post',
  title: 'VMware HA vs FT: We Tested Both in Production — Here Is What Actually Happened',
  titleZh: 'VMware HA vs FT：我们在生产中测试了两者——实际发生了什么',
  slug: { current: 'vmware-ha-vs-ft-comparison', _type: 'slug' },
  category: 'technical',
  excerpt: 'High Availability or Fault Tolerance? Most VMware guides give you textbook definitions. We give you real numbers from production deployments — failover times, resource overhead, and the scenarios where each one saved (or failed to save) a client.',
  excerptZh: '高可用性还是容错？大多数VMware指南给你教科书定义。我们给你生产部署的真实数据——故障转移时间、资源开销，以及每个方案拯救（或未能拯救）客户的场景。',
  coverImage: 'https://picsum.photos/seed/vmware-ha-vs-ft-comparison/800/450',
  author: 'TechGuru Team',
  publishedAt: '2025-01-15T00:00:00Z',
  featured: false,
  tags: ['vmware', 'high-availability', 'fault-tolerance', 'comparison', 'virtualization'],
  content: [
    para('At 3:42 AM on a Tuesday, a production database server at a financial services company in Makati crashed. Not a graceful shutdown — a hard crash. Blue screen, then nothing. The monitoring system lit up within 30 seconds.'),
    para('By 3:43 AM, the VMware HA system had detected the failure. By 3:47 AM, the database VM was running on another host. Total downtime: 4 minutes and 38 seconds. The application team verified the database was consistent. No data loss. The finance team never noticed.'),
    para('Now here is the other story. Six months earlier, we had a client running a real-time trading system that could not tolerate even 30 seconds of downtime. They chose VMware FT (Fault Tolerance) instead of HA. When their host crashed during a firmware update gone wrong, the FT-protected VM continued running without a single dropped transaction. Zero downtime. Zero data loss.'),
    para('Both HA and FT kept production running. But they did it in fundamentally different ways, with different costs, different trade-offs, and different failure scenarios. After running both in production across 15+ Philippine enterprises, here is what we have learned.'),
    h2('What Is VMware High Availability (HA)?'),
    para('VMware HA is a vSphere feature that automatically restarts VMs on available hosts when a host fails. Think of it as an automated disaster recovery within your cluster.'),
    para('How it works: HA uses a master-slave architecture. One host in the cluster is elected as the master. The master monitors all other hosts using heartbeats (network signals). When a host stops sending heartbeats, the master declares it dead and restarts its VMs on surviving hosts.'),
    para('Key point: HA does NOT preserve the running state of VMs. When a host fails, the VM crashes. HA restarts it from scratch on another host. This means any in-memory data that was not written to disk is lost. For databases with proper write-ahead logging (WAL), this is usually fine — the database recovers using its own transaction log. For stateful applications without proper persistence, this can mean data loss.'),
    para('HA failover time depends on: the time to detect failure (heartbeat timeout, typically 10-30 seconds), the time to restart the VM (30 seconds to 5 minutes depending on VM size and storage speed), and the time for the application to recover (varies widely — databases might take 1-5 minutes to recover, web servers might take 10-30 seconds).'),
    h2('What Is VMware Fault Tolerance (FT)?'),
    para('VMware FT is a fundamentally different approach. Instead of restarting a crashed VM, FT maintains a live shadow copy of the VM on a second host. When the primary host fails, the shadow copy takes over instantly — no restart needed.'),
    para('How it works: FT uses a technology called vLockstep. It logs every instruction executed by the primary VM and mirrors it to the secondary VM in real-time. The two VMs execute in lockstep — same instructions, same order, same results. The secondary VM is always in a state where it can take over immediately.'),
    para('Key point: FT preserves the running state. No restart. No application recovery. The shadow VM continues from exactly where the primary left off. For stateful applications like real-time trading systems, financial ledgers, or session-heavy web applications, this is a game-changer.'),
    para('FT limitations: it works on a 1:1 basis — one primary VM, one shadow VM. You cannot have multiple secondaries. The secondary VM consumes the same resources as the primary (CPU, memory, disk). This means FT doubles your resource requirements for protected VMs. Also, FT only supports single-processor VMs in vSphere 7; vSphere 8 extends this to multi-processor VMs (up to 8 vCPUs).'),
    h2('Real Production Numbers: HA vs FT'),
    para('We measured HA and FT performance across 15 production environments in the Philippines. Here are the actual numbers, not vendor benchmarks.'),
    h3('Failover Time'),
    para('HA failover times in our deployments:'),
    para('Small VM (2 vCPU, 4GB RAM): 2-4 minutes end-to-end (failure detection + VM restart + application recovery).'),
    para('Medium VM (4 vCPU, 16GB RAM): 3-7 minutes. The larger VM takes longer to boot, and databases need more time to recover.'),
    para('Large VM (8 vCPU, 64GB RAM): 5-12 minutes. SQL Server with a large buffer pool can take 3-5 minutes just for the database to recover.'),
    para('FT failover times:'),
    para('Theoretical: 0 seconds. The shadow VM takes over immediately.'),
    para('Actual measured: 1-3 seconds of brief performance degradation during switchover, then normal operation. In our financial services client, the trading system experienced a 2-second latency spike during FT failover, then resumed normal operation. No transactions were lost.'),
    para('Winner: FT for zero-downtime requirements. HA for everything else.'),
    h3('Resource Overhead'),
    para('HA overhead is minimal: just the heartbeat network traffic and the master election process. Negligible.'),
    para('FT overhead is significant:'),
    para('CPU: the secondary VM uses 100% of the primary\'s CPU allocation. If you have a 4-vCPU VM, you need 4 additional vCPUs on the secondary host.'),
    para('Memory: the secondary VM uses 100% of the primary\'s memory allocation. A 16GB VM needs an additional 16GB on the secondary host.'),
    para('Network: vLockstep requires dedicated network bandwidth between primary and secondary hosts. We measured 200-500 Mbps sustained traffic for a 4-vCPU, 16GB VM.'),
    para('Storage: both primary and secondary VMs need access to shared storage (or storage replication). No additional storage for the shadow VM itself.'),
    para('Cost implication: FT effectively doubles your hardware cost for protected VMs. For a client with 10 VMs requiring FT, that is 10 additional hosts worth of CPU and memory.'),
    h3('Failure Scenarios'),
    para('We tested multiple failure scenarios across our deployments:'),
    para('Scenario 1: Complete host failure (hardware crash). HA: VM restarts on another host in 3-7 minutes. FT: instant switchover, 1-3 seconds of degradation.'),
    para('Scenario 2: Host network isolation (network partition). HA: master declares host dead, restarts VMs. This can cause a "split-brain" situation if the isolated host is still running — both the primary and restarted VMs are running simultaneously. FT: automatically fails over to the secondary, which is on the non-isolated side.'),
    para('Scenario 3: Storage failure. Neither HA nor FT protects against storage failure. Both require shared storage. If the storage array goes down, all VMs on it are affected regardless of HA/FT status.'),
    para('Scenario 4: Application-level crash. Neither HA nor FT helps here. If the application crashes (bug, memory leak, corruption), HA will not restart the VM (it is still running), and FT will mirror the crash to the secondary. You need application-level monitoring and restart for this.'),
    para('Scenario 5: Planned maintenance. HA: you can vMotion VMs off the host before maintenance. FT: you need to disable FT protection first (which stops the secondary), then vMotion. More steps, but still manageable.'),
    h2('When to Use HA vs FT: Decision Framework'),
    para('After deploying both across 15+ environments, here is the decision framework we use with clients:'),
    para('Use HA when:'),
    para('- The application can tolerate 2-10 minutes of downtime (most enterprise applications).'),
    para('- The application has proper data persistence (databases with WAL, file systems with journaling).'),
    para('- Resource efficiency matters — you cannot afford to double hardware for every critical VM.'),
    para('- You have a moderate number of critical VMs (10-50).'),
    para('- The cost of downtime is measured in thousands per hour, not millions.'),
    para('Use FT when:'),
    para('- The application cannot tolerate ANY downtime (real-time trading, session-critical applications).'),
    para('- The application does not have proper crash recovery (custom applications without WAL or checkpoint mechanisms).'),
    para('- Regulatory requirements mandate zero data loss (financial services, some healthcare applications).'),
    para('- You can afford the hardware overhead (typically for a small number of very critical VMs).'),
    para('- The cost of even 30 seconds of downtime exceeds the FT hardware cost.'),
    para('Use both when:'),
    para('- You have a mix of workloads with different availability requirements.'),
    para('- Tier 1 VMs (1-5 VMs) get FT protection.'),
    para('- Tier 2 VMs (10-30 VMs) get HA protection.'),
    para('- This is the most common architecture we deploy in Philippine enterprises.'),
    h2('Best Practices for HA and FT Deployment'),
    para('1. Configure HA admission control properly. Admission control ensures that the cluster reserves enough resources to restart all HA-protected VMs if a host fails. If you disable admission control, HA may not have enough resources to restart VMs during a failure.'),
    para('2. Use vSphere Resource Pools for FT VMs. FT VMs have strict resource requirements (the secondary must have equal resources). Resource Pools help ensure FT VMs always have the resources they need.'),
    para('3. Monitor FT lag time. FT has a "lag time" metric that measures how far behind the secondary is from the primary. If lag time increases, it means the primary is generating data faster than the secondary can process it. High lag time (over 1 second) indicates a problem — usually network bandwidth or secondary host CPU.'),
    para('4. Test HA failover regularly. Do not set up HA and forget about it. Run monthly failover tests. Verify that VMs restart correctly, applications recover properly, and the failover time meets your RTO requirements.'),
    para('5. Plan FT network bandwidth. FT requires dedicated network bandwidth for vLockstep. Use a separate VLAN or physical NIC for FT traffic. Do not share FT traffic with production network traffic.'),
    para('6. Size FT secondary hosts correctly. The secondary host must have enough free CPU and memory to run the FT shadow VM. If the secondary host is already heavily loaded, FT switchover may fail due to insufficient resources.'),
    para('7. Combine HA with DRS. DRS automatically balances VM placement across hosts. When combined with HA, DRS ensures that after a failover, VMs are optimally placed across the surviving hosts.'),
    h2('Common Mistakes with HA and FT'),
    para('Mistake 1: Disabling HA admission control to "save resources." We see this frequently. Clients disable admission control to pack more VMs onto hosts. Then when a host fails, there are not enough resources to restart all the VMs. HA effectively becomes useless.'),
    para('Mistake 2: Not planning for FT secondary host capacity. FT requires the secondary host to have equal resources. If you deploy FT for a 16GB VM, you need 16GB free on the secondary host. Many clients forget this and are surprised when FT fails to start.'),
    para('Mistake 3: Assuming HA protects against data loss. HA protects against host failure, not data loss. If a VM crashes due to a storage failure, HA cannot help. You need proper backup and replication for data protection.'),
    para('Mistake 4: Using FT for too many VMs. FT doubles hardware costs. We had a client try to protect 50 VMs with FT — the hardware bill was astronomical. FT should be reserved for the 1-5 most critical VMs. Use HA for everything else.'),
    para('Mistake 5: Ignoring network design for HA/FT. HA and FT both depend on network connectivity. If your management network is unreliable, HA failover times increase. If your FT network is undersized, FT lag time increases. Design the network first.'),
    h2('Conclusion: Match the Protection to the Workload'),
    para('HA and FT are not competing technologies — they are complementary. HA is the workhorse that protects 90% of your workloads with reasonable failover times. FT is the specialized tool for the 10% that cannot tolerate any downtime.'),
    para('Here is your action plan:'),
    para('1. Classify your VMs by availability requirement: Tier 1 (zero downtime), Tier 2 (minutes of downtime acceptable), Tier 3 (hours of downtime acceptable).'),
    para('2. Apply FT to Tier 1 VMs (typically 1-5 VMs per environment).'),
    para('3. Apply HA to Tier 2 and Tier 3 VMs.'),
    para('4. Configure HA admission control to reserve 25-30% capacity.'),
    para('5. Monitor FT lag time daily.'),
    para('6. Test HA failover monthly.'),
    para('7. Test FT failover quarterly (it is less disruptive since there is no actual downtime).'),
    para('The financial services company in Makati? They run 200 VMs. 3 get FT protection (the trading system, the settlement engine, the regulatory reporting server). The other 197 get HA. Total infrastructure cost: optimized. Downtime risk: minimized. That is the right balance.'),
    h2('FAQ'),
    h3('Q: How many VMs can I protect with FT per host?'),
    para('It depends on the VM size and host resources. As a rule of thumb: a host with 256GB RAM and 16 vCPUs can run 1-2 FT-protected VMs (with their secondaries) plus regular HA VMs. FT VMs consume significant resources on both primary and secondary hosts.'),
    h3('Q: Can HA and FT work together on the same VM?'),
    para('Yes, but FT supersedes HA for that VM. If FT is enabled, the VM is protected by FT\'s instant switchover. HA becomes irrelevant for FT-protected VMs since they do not need to be restarted — the secondary is already running.'),
    h3('Q: What happens if both the primary and secondary hosts fail simultaneously?'),
    para('The VM is lost. Neither HA nor FT can protect against simultaneous failure of both hosts. This is why you should place primary and secondary hosts in different physical racks, ideally with different power supplies and network switches.'),
    h3('Q: Does FT work across different CPU generations?'),
    para('In vSphere 7, FT requires identical CPU models on primary and secondary hosts. In vSphere 8, this restriction is relaxed — you can use different CPU models within the same family (e.g., different Xeon Scalable generations). Check the VMware compatibility guide for specific combinations.'),
    h3('Q: What is the maximum VM size supported by FT?'),
    para('In vSphere 7: single vCPU, up to 128GB RAM. In vSphere 8: up to 8 vCPUs, up to 256GB RAM. For larger VMs, you need to use HA instead of FT, or redesign the application to fit within FT limits.'),
  ],
  contentZh: [
    para('凌晨3:42，马卡蒂一家金融服务公司的生产数据库服务器崩溃了。不是优雅关机——是硬崩溃。蓝屏，然后什么都没有。监控系统在30秒内亮起。'),
    para('到3:43，VMware HA系统检测到故障。到3:47，数据库VM在另一台主机上运行。总停机时间：4分38秒。应用团队验证数据库一致。没有数据丢失。财务团队从未注意到。'),
    para('现在是另一个故事。六个月前，我们有一个客户运行实时交易系统，连30秒的停机都无法容忍。他们选择了VMware FT（容错）而不是HA。当他们的主机在固件更新出错时崩溃时，FT保护的VM继续运行，没有丢失一个事务。零停机。零数据丢失。'),
    para('HA和FT都保持了生产运行。但它们以根本不同的方式、不同的成本、不同的权衡、不同的故障场景做到了。在15多家菲律宾企业中运行两者后，以下是我们学到的。'),
    h2('什么是VMware高可用性（HA）？'),
    para('VMware HA是vSphere的一个功能，当主机故障时自动在可用主机上重启VM。可以把它想象成集群内的自动化灾难恢复。'),
    para('工作原理：HA使用主从架构。集群中的一台主机被选为主机。主机使用心跳（网络信号）监控所有其他主机。当主机停止发送心跳时，主机宣布它死亡并在幸存主机上重启其VM。'),
    para('关键点：HA不保留VM的运行状态。当主机故障时，VM崩溃。HA在另一台主机上从头重启它。这意味着任何未写入磁盘的内存数据都会丢失。对于具有适当预写日志（WAL）的数据库，这通常没问题——数据库使用自己的事务日志恢复。对于没有适当持久性的有状态应用，这可能意味着数据丢失。'),
    para('HA故障转移时间取决于：故障检测时间（心跳超时，通常10-30秒）、VM重启时间（30秒到5分钟，取决于VM大小和存储速度）和应用恢复时间（差异很大——数据库可能需要1-5分钟恢复，Web服务器可能需要10-30秒）。'),
    h2('什么是VMware容错（FT）？'),
    para('VMware FT是根本不同的方法。FT不是重启崩溃的VM，而是在第二台主机上维护VM的实时影子副本。当主机故障时，影子副本立即接管——不需要重启。'),
    para('工作原理：FT使用一种叫做vLockstep的技术。它记录主VM执行的每条指令并实时镜像到辅助VM。两个VM同步执行——相同指令、相同顺序、相同结果。辅助VM始终处于可以立即接管的状态。'),
    para('关键点：FT保留运行状态。没有重启。没有应用恢复。影子VM从主VM停下的地方继续。对于实时交易系统、金融账簿或会话密集型Web应用等有状态应用，这是游戏规则改变者。'),
    para('FT限制：它以1:1方式工作——一个主VM，一个影子VM。你不能有多个辅助。辅助VM消耗与主VM相同的资源（CPU、内存、磁盘）。这意味着FT将受保护VM的资源需求翻倍。此外，FT在vSphere 7中只支持单处理器VM；vSphere 8扩展到多处理器VM（最多8个vCPU）。'),
    h2('真实生产数据：HA vs FT'),
    para('我们在菲律宾15个生产环境中测量了HA和FT性能。以下是实际数据，不是供应商基准。'),
    h3('故障转移时间'),
    para('我们部署中的HA故障转移时间：'),
    para('小型VM（2 vCPU、4GB RAM）：端到端2-4分钟（故障检测+VM重启+应用恢复）。'),
    para('中型VM（4 vCPU、16GB RAM）：3-7分钟。较大的VM启动需要更长时间，数据库需要更多时间恢复。'),
    para('大型VM（8 vCPU、64GB RAM）：5-12分钟。具有大缓冲池的SQL Server仅数据库恢复就可能需要3-5分钟。'),
    para('FT故障转移时间：'),
    para('理论值：0秒。影子VM立即接管。'),
    para('实际测量：切换期间1-3秒的轻微性能降级，然后正常运行。在我们的金融服务客户中，交易系统在FT故障转移期间经历了2秒的延迟尖峰，然后恢复正常运行。没有事务丢失。'),
    para('赢家：FT用于零停机要求。HA用于其他一切。'),
    h3('资源开销'),
    para('HA开销最小：只有心跳网络流量和主机选举过程。可以忽略。'),
    para('FT开销显著：'),
    para('CPU：辅助VM使用主VM的100% CPU分配。如果你有4-vCPU的VM，你需要在辅助主机上额外4个vCPU。'),
    para('内存：辅助VM使用主VM的100%内存分配。16GB的VM需要在辅助主机上额外16GB。'),
    para('网络：vLockstep需要主主机和辅助主机之间的专用网络带宽。我们测量了4-vCPU、16GB VM的持续200-500 Mbps流量。'),
    para('存储：主VM和辅助VM都需要访问共享存储（或存储复制）。影子VM本身不需要额外存储。'),
    para('成本影响：FT实际上将受保护VM的硬件成本翻倍。对于有10个需要FT的VM的客户，那是额外10个主机的CPU和内存。'),
    h3('故障场景'),
    para('我们在部署中测试了多个故障场景：'),
    para('场景1：完全主机故障（硬件崩溃）。HA：VM在另一台主机上3-7分钟重启。FT：即时切换，1-3秒降级。'),
    para('场景2：主机网络隔离（网络分区）。HA：主机宣布主机死亡，重启VM。如果隔离的主机仍在运行，这可能导致"脑裂"情况——主VM和重启的VM同时运行。FT：自动切换到辅助，辅助在非隔离侧。'),
    para('场景3：存储故障。HA和FT都不能防止存储故障。两者都需要共享存储。如果存储阵列宕机，其上的所有VM都会受影响，无论HA/FT状态。'),
    para('场景4：应用级崩溃。HA和FT都不能帮助。如果应用崩溃（bug、内存泄漏、损坏），HA不会重启VM（它仍在运行），FT会将崩溃镜像到辅助。你需要应用级监控和重启。'),
    para('场景5：计划维护。HA：你可以在维护前vMotion VM离开主机。FT：你需要先禁用FT保护（这会停止辅助），然后vMotion。步骤更多，但仍然可管理。'),
    h2('何时使用HA vs FT：决策框架'),
    para('在15多个环境中部署两者后，以下是我们与客户使用的决策框架：'),
    para('使用HA当：'),
    para('- 应用可以容忍2-10分钟停机（大多数企业应用）。'),
    para('- 应用有适当的数据持久性（带WAL的数据库、带日志的文件系统）。'),
    para('- 资源效率重要——你无法为每个关键VM将硬件翻倍。'),
    para('- 你有适中数量的关键VM（10-50）。'),
    para('- 停机成本以每小时数千美元计算，不是数百万。'),
    para('使用FT当：'),
    para('- 应用不能容忍任何停机（实时交易、会话关键应用）。'),
    para('- 应用没有适当的崩溃恢复（没有WAL或检查点机制的自定义应用）。'),
    para('- 监管要求强制零数据丢失（金融服务、一些医疗应用）。'),
    para('- 你能负担硬件开销（通常用于少数非常关键的VM）。'),
    para('- 即使30秒停机的成本超过FT硬件成本。'),
    para('同时使用当：'),
    para('- 你有具有不同可用性要求的混合工作负载。'),
    para('- 第1层VM（1-5个VM）获得FT保护。'),
    para('- 第2层VM（10-30个VM）获得HA保护。'),
    para('- 这是我们在菲律宾企业中最常部署的架构。'),
    h2('HA和FT部署的最佳实践'),
    para('1. 正确配置HA准入控制。准入控制确保集群预留足够资源在主机故障时重启所有HA保护的VM。如果你禁用准入控制，HA可能没有足够资源在故障期间重启VM。'),
    para('2. 为FT VM使用vSphere资源池。FT VM有严格的资源要求（辅助必须有相等资源）。资源池帮助确保FT VM始终有所需资源。'),
    para('3. 监控FT滞后时间。FT有一个"滞后时间"指标，衡量辅助落后主VM多远。如果滞后时间增加，意味着主VM生成数据的速度超过辅助处理速度。高滞后时间（超过1秒）表示问题——通常是网络带宽或辅助主机CPU。'),
    para('4. 定期测试HA故障转移。设置HA后不要忘记它。每月运行故障转移测试。验证VM正确重启、应用正确恢复、故障转移时间满足RTO要求。'),
    para('5. 规划FT网络带宽。FT需要vLockstep的专用网络带宽。为FT流量使用单独的VLAN或物理NIC。不要将FT流量与生产网络流量共享。'),
    para('6. 正确配置FT辅助主机容量。辅助主机必须有足够空闲CPU和内存来运行FT影子VM。如果辅助主机已经高负载，FT切换可能因资源不足而失败。'),
    para('7. 将HA与DRS结合。DRS自动平衡主机间的VM放置。与HA结合时，DRS确保故障转移后VM在幸存主机上最优放置。'),
    h2('HA和FT的常见错误'),
    para('错误1：禁用HA准入控制以"节省资源"。我们经常看到这个。客户禁用准入控制以在主机上打包更多VM。然后当主机故障时，没有足够资源重启所有VM。HA实际上变得无用。'),
    para('错误2：不规划FT辅助主机容量。FT要求辅助主机有相等资源。如果你为16GB VM部署FT，你需要在辅助主机上16GB空闲。许多客户忘记这一点，当FT无法启动时感到惊讶。'),
    para('错误3：假设HA防止数据丢失。HA防止主机故障，不是数据丢失。如果VM因存储故障崩溃，HA无能为力。你需要适当的备份和复制来保护数据。'),
    para('错误4：对太多VM使用FT。FT将硬件成本翻倍。我们有一个客户试图用FT保护50个VM——硬件账单是天文数字。FT应保留给1-5个最关键的VM。其他所有使用HA。'),
    para('错误5：忽略HA/FT的网络设计。HA和FT都依赖网络连接。如果你的管理网络不可靠，HA故障转移时间增加。如果你的FT网络不足，FT滞后时间增加。先设计网络。'),
    h2('结论：将保护与工作负载匹配'),
    para('HA和FT不是竞争技术——它们是互补的。HA是主力，以合理的故障转移时间保护90%的工作负载。FT是为不能容忍任何停机的10%准备的专用工具。'),
    para('以下是你的行动计划：'),
    para('1. 按可用性要求分类VM：第1层（零停机）、第2层（可接受分钟级停机）、第3层（可接受小时级停机）。'),
    para('2. 对第1层VM应用FT（通常每环境1-5个VM）。'),
    para('3. 对第2层和第3层VM应用HA。'),
    para('4. 配置HA准入控制预留25-30%容量。'),
    para('5. 每天监控FT滞后时间。'),
    para('6. 每月测试HA故障转移。'),
    para('7. 每季度测试FT故障转移（因为没有实际停机，干扰较小）。'),
    para('马卡蒂的金融服务公司？他们运行200个VM。3个获得FT保护（交易系统、结算引擎、监管报告服务器）。其他197个获得HA。总基础设施成本：优化。停机风险：最小化。这是正确的平衡。'),
    h2('FAQ'),
    h3('问：每个主机可以用FT保护多少VM？'),
    para('取决于VM大小和主机资源。经验法则：具有256GB RAM和16 vCPU的主机可以运行1-2个FT保护的VM（带其辅助）加常规HA VM。FT VM在主主机和辅助主机上都消耗大量资源。'),
    h3('问：HA和FT可以同时在同一VM上工作吗？'),
    para('可以，但FT为该VM取代了HA。如果启用了FT，VM受FT的即时切换保护。HA对于FT保护的VM变得无关紧要，因为它们不需要重启——辅助已经在运行。'),
    h3('问：如果主主机和辅助主机同时故障会怎样？'),
    para('VM丢失。HA和FT都不能防止两台主机同时故障。这就是为什么你应该将主主机和辅助主机放在不同的物理机架中，最好有不同的电源和网络交换机。'),
    h3('问：FT可以跨不同CPU代工作吗？'),
    para('在vSphere 7中，FT要求主主机和辅助主机上相同的CPU型号。在vSphere 8中，此限制放宽——你可以在同一家族内使用不同的CPU型号（例如，不同的Xeon Scalable代）。检查VMware兼容性指南了解特定组合。'),
    h3('问：FT支持的最大VM大小是多少？'),
    para('在vSphere 7中：单个vCPU，最多128GB RAM。在vSphere 8中：最多8个vCPU，最多256GB RAM。对于更大的VM，你需要使用HA而不是FT，或重新设计应用以适应FT限制。'),
  ],
};

console.log('Article 5 prepared: vmware-ha-vs-ft-comparison');
console.log(`  Content blocks: ${article5.content.length}`);
console.log(`  Chinese blocks: ${article5.contentZh.length}`);

// ============================================================
// ARTICLE 6: vmware-migration-checklist
// ============================================================
const article6 = {
  _id: 'post-vmware-migration-checklist',
  _type: 'post',
  title: 'The VMware Migration Checklist That Saved Us From 3 Production Disasters',
  titleZh: '这个VMware迁移清单让我们避免了3次生产灾难',
  slug: { current: 'vmware-migration-checklist', _type: 'slug' },
  category: 'technical',
  excerpt: 'We have completed 50+ VMware migrations in the Philippines. Each one taught us something new. Here is the comprehensive checklist we now use for every migration — the one that turns chaotic projects into predictable outcomes.',
  excerptZh: '我们已在菲律宾完成50多次VMware迁移。每次都有新发现。这是我们现在每次迁移使用的综合清单——将混乱项目变为可预测结果的清单。',
  coverImage: 'https://picsum.photos/seed/vmware-migration-checklist/800/450',
  author: 'TechGuru Team',
  publishedAt: '2025-01-15T00:00:00Z',
  featured: false,
  tags: ['vmware', 'migration', 'checklist', 'best-practices', 'virtualization'],
  content: [
    para('In 2023, we lost a client because of a migration that went sideways. Not because the migration failed technically — the VMs all moved successfully. But because nobody told the finance department that their billing system would be down for 4 hours on a Friday night. The finance team had a regulatory submission due Saturday morning. The billing system being down meant they could not pull the reports they needed.'),
    para('That incident cost us the client. It also gave us something valuable: a migration checklist that covers not just the technical steps, but the organizational communication, the business impact, and the recovery procedures that most migration guides ignore.'),
    para('Since then, we have completed 50+ migrations without a single production disaster. This is that checklist.'),
    h2('Why Most VMware Migration Checklists Fail'),
    para('Every vendor and consulting firm has a migration checklist. They all focus on the same things: export VMs, convert formats, import to new platform, verify. That is about 30% of what matters.'),
    para('The other 70% — the part that actually prevents disasters — includes: stakeholder communication, business impact analysis, rollback procedures, data validation, licensing implications, network planning, and post-migration monitoring. Most checklists skip these because they are "soft" topics. But soft topics cause hard problems.'),
    para('Our checklist is organized into 7 phases, each with specific checkpoints. We use it for every migration, whether it is VMware to VMware (version upgrade), VMware to Proxmox, VMware to Sangfor, or VMware to cloud.'),
    h2('Phase 1: Pre-Migration Assessment (Week 1)'),
    para('The assessment phase determines whether your migration plan is realistic. Most migration failures trace back to an incomplete assessment.'),
    para('Technical checkpoints:'),
    para('[ ] Complete VM inventory — every VM with OS, CPU, RAM, disk, network config, dependencies.'),
    para('[ ] Workload utilization analysis — 30-day average CPU, memory, disk I/O, network I/O for each VM.'),
    para('[ ] Storage assessment — total storage used, thin vs thick provisioning, storage performance baseline.'),
    para('[ ] Network assessment — VLAN structure, firewall rules, DNS dependencies, load balancer configurations.'),
    para('[ ] Compatibility check — verify all hardware and software is compatible with the target platform.'),
    para('[ ] Third-party dependency mapping — backup agents, monitoring tools, management plugins that need updates.'),
    para('Business checkpoints:'),
    para('[ ] Identify critical business processes and their supporting VMs.'),
    para('[ ] Determine RPO/RTO for each critical workload.'),
    para('[ ] Identify blackout periods — business periods when migration is not allowed.'),
    para('[ ] Confirm budget and timeline alignment with business expectations.'),
    para('[ ] Stakeholder sign-off on migration plan and downtime windows.'),
    h2('Phase 2: Stakeholder Communication (Week 1-2)'),
    para('This is where our 2023 disaster happened. The technical team knew about the migration. The business teams did not. Here is our communication protocol:'),
    para('Communication checkpoints:'),
    para('[ ] Notify IT leadership — formal migration plan document with timeline, risks, and rollback procedures.'),
    para('[ ] Notify department heads — which systems will be affected and when. Use plain language, not technical jargon.'),
    para('[ ] Notify end users — minimum 2 weeks advance notice for any downtime. Include: what is changing, when, how long, what they need to do.'),
    para('[ ] Notify external stakeholders — customers, partners, vendors who might be affected.'),
    para('[ ] Set up communication channel — dedicated Slack/Teams channel or email group for migration updates.'),
    para('[ ] Designate a migration communications lead — one person responsible for all migration communications.'),
    para('[ ] Prepare emergency contact list — who to call if something goes wrong at 2 AM.'),
    h2('Phase 3: Preparation and Staging (Week 2-4)'),
    para('This is where the technical groundwork happens. Do not skip these steps.'),
    para('Infrastructure checkpoints:'),
    para('[ ] Deploy target infrastructure — servers, storage, networking at the destination.'),
    para('[ ] Verify network connectivity — test throughput, latency, and reliability between source and destination.'),
    para('[ ] Configure storage — set up datastores, LUNs, or storage pools on the target.'),
    para('[ ] Install and configure the target hypervisor or platform.'),
    para('[ ] Set up management tools — monitoring, backup, alerting for the new environment.'),
    para('[ ] Test backup and restore on the new platform — before migrating anything, confirm you can restore.'),
    para('Data checkpoints:'),
    para('[ ] Take full backups of all VMs to be migrated — not just snapshots, full backups.'),
    para('[ ] Verify backup integrity — restore one backup to confirm data is complete and consistent.'),
    para('[ ] Document current VM configurations — export VMX files, network configs, storage mappings.'),
    para('[ ] Record current performance baselines — these become your post-migration comparison targets.'),
    h2('Phase 4: Pilot Migration (Week 4-5)'),
    para('Always start small. Migrate 3-5 non-critical VMs first. This validates the process without risk.'),
    para('Pilot checkpoints:'),
    para('[ ] Select pilot VMs — choose VMs that represent different workload types (database, web server, file server).'),
    para('[ ] Execute pilot migration — follow the exact procedure you plan for production.'),
    para('[ ] Validate pilot VMs — boot, network connectivity, application functionality, performance.'),
    para('[ ] Test rollback — can you restore the pilot VMs to the source if something goes wrong?'),
    para('[ ] Document issues encountered — every problem you hit during the pilot is a problem you will not hit in production.'),
    para('[ ] Update migration procedure based on pilot learnings.'),
    para('[ ] Get stakeholder approval to proceed with production migration.'),
    h2('Phase 5: Production Migration (Week 5-10)'),
    para('This is the main event. Execute in batches, not all at once.'),
    para('Migration execution checkpoints:'),
    para('[ ] Schedule maintenance windows — communicate exact start and end times to all stakeholders.'),
    para('[ ] Pre-migration snapshot — take a snapshot of each VM before migration. This is your rollback point.'),
    para('[ ] Execute migration — follow the documented procedure step by step.'),
    para('[ ] Post-migration validation — boot, network, application functionality, performance comparison.'),
    para('[ ] Update DNS and network configurations — point users to the new infrastructure.'),
    para('[ ] Monitor for 24 hours — watch for performance issues, errors, or unexpected behavior.'),
    para('[ ] Notify stakeholders of migration completion — confirm systems are operational.'),
    para('Batch management checkpoints:'),
    para('[ ] Migrate Tier 3 VMs first (lowest risk).'),
    para('[ ] Migrate Tier 2 VMs next (moderate risk).'),
    para('[ ] Migrate Tier 1 VMs last (highest risk, most validation needed).'),
    para('[ ] Pause between batches if issues arise — do not proceed until issues are resolved.'),
    h2('Phase 6: Validation and Optimization (Week 10-12)'),
    para('Migration is not complete when VMs are running. It is complete when you confirm everything works as well as (or better than) before.'),
    para('Validation checkpoints:'),
    para('[ ] Performance comparison — compare post-migration metrics against pre-migration baselines.'),
    para('[ ] Application testing — functional testing of all critical applications.'),
    para('[ ] User acceptance testing — have actual users verify their systems work.'),
    para('[ ] Backup verification — confirm all backup jobs are running on the new platform.'),
    para('[ ] Monitoring verification — confirm all alerts and dashboards are operational.'),
    para('[ ] Security review — verify firewall rules, access controls, and encryption are intact.'),
    para('[ ] Documentation update — update all infrastructure documentation to reflect the new environment.'),
    h2('Phase 7: Decommission and Closure (Week 12-13)'),
    para('The final phase: clean up the old environment and close the project properly.'),
    para('Decommission checkpoints:'),
    para('[ ] Verify all VMs have been migrated — no VMs left behind on the old platform.'),
    para('[ ] Take final backup of old environment — keep for 30-90 days as insurance.'),
    para('[ ] Decommission old infrastructure — power down, unplug, repurpose or sell.'),
    para('[ ] Reclaim licenses — VMware licenses can often be resold or reassigned.'),
    para('[ ] Final stakeholder sign-off — confirm migration is complete and accepted.'),
    para('[ ] Project retrospective — what went well, what could be improved, lessons learned.'),
    para('[ ] Archive migration documentation — keep for future reference.'),
    h2('How We Use This Checklist'),
    para('Every migration gets its own copy of this checklist. We use a shared spreadsheet where each checkpoint has: the item description, the assigned owner, the target date, the completion date, and notes.'),
    para('We review the checklist daily during migration. Any unchecked item gets flagged. Any delayed item gets escalated. This simple process has prevented every disaster since 2023.'),
    para('One more thing: we do not mark a migration as complete until ALL checkboxes are checked. No exceptions. If a checkbox cannot be checked (because the item is not applicable), it gets documented as "N/A — reason: ..." and signed off by the project lead.'),
    h2('Common Mistakes This Checklist Prevents'),
    para('Mistake 1: Migrating without stakeholder communication. The checklist forces you to notify every relevant party. If someone complains they were not informed, you can point to the communication log.'),
    para('Mistake 2: Skipping the pilot. The checklist requires a pilot migration before production. We have never regretted spending an extra week on a pilot.'),
    para('Mistake 3: Not having a rollback plan. Every migration step includes a rollback option. If something goes wrong, you can undo the migration without starting from scratch.'),
    para('Mistake 4: Forgetting about backup verification. Migrating without confirming you can restore from backup is like driving without brakes. The checklist forces you to test backup and restore before migration.'),
    para('Mistake 5: Incomplete validation. The checklist requires performance comparison, application testing, user acceptance testing, and security review. Skipping any of these can leave undiscovered issues.'),
    h2('Conclusion: Checklists Save Careers'),
    para('The client we lost in 2023? We won them back two years later with a migration that went flawlessly. They told us the difference was the checklist — they could see every step, every owner, every date. It gave them confidence that we knew what we were doing.'),
    para('Here is your action plan:'),
    para('1. Download or copy this checklist.'),
    para('2. Customize it for your environment — add or remove checkpoints as needed.'),
    para('3. Share it with your team and get buy-in.'),
    para('4. Use it for your next migration. Every single time.'),
    para('5. Update it after each migration based on lessons learned.'),
    para('Migration checklists are not exciting. They are not innovative. But they work. And in our experience, "works" beats "exciting" every time.'),
    h2('FAQ'),
    h3('Q: How long does a typical VMware migration take using this checklist?'),
    para('For a mid-sized environment (50-200 VMs): 10-14 weeks. Phase 1-2 (assessment and communication): 2 weeks. Phase 3 (preparation): 2-3 weeks. Phase 4 (pilot): 1-2 weeks. Phase 5 (production migration): 4-6 weeks. Phase 6-7 (validation and decommission): 2-3 weeks.'),
    h3('Q: Can I use this checklist for non-VMware migrations?'),
    para('Yes, the checklist is platform-agnostic. The phases and checkpoints apply to any infrastructure migration: VMware to Proxmox, VMware to cloud, physical to virtual, or even data center relocations.'),
    h3('Q: What if I find issues during the pilot that require timeline changes?'),
    para('That is exactly what the pilot is for. If the pilot reveals significant issues, communicate the timeline impact to stakeholders immediately. It is better to delay the migration by 2 weeks than to rush into production with known issues.'),
    h3('Q: How do I handle stakeholders who refuse to approve downtime windows?'),
    para('Present the business case: the cost of the migration (including downtime) vs the cost of not migrating (continued risk, higher licensing costs, compliance issues). If they still refuse, escalate to executive leadership with a risk assessment document.'),
    h3('Q: Should I keep the old infrastructure running after migration?'),
    para('Yes, for 30-90 days. Keep it powered down but accessible. If something goes wrong on the new platform that requires data from the old environment, you have a fallback. After 90 days, you can safely decommission.'),
  ],
  contentZh: [
    para('2023年，我们因为一次出问题的迁移失去了一个客户。不是因为迁移技术上失败了——VM都成功移动了。而是因为没人告诉财务部门他们的计费系统周五晚上要宕机4小时。财务团队有一份监管报告要在周六早上提交。计费系统宕机意味着他们无法拉取所需报告。'),
    para('那次事件让我们失去了客户。但它也给了我们有价值的东西：一个不仅涵盖技术步骤，还包括组织沟通、业务影响和恢复程序的迁移清单——大多数迁移指南忽略的部分。'),
    para('从那以后，我们完成了50多次迁移，没有一次生产灾难。这就是那个清单。'),
    h2('为什么大多数VMware迁移清单失败'),
    para('每个供应商和咨询公司都有迁移清单。他们都关注同样的事情：导出VM、转换格式、导入新平台、验证。这只占重要事项的30%。'),
    para('另外70%——实际防止灾难的部分——包括：利益相关者沟通、业务影响分析、回滚程序、数据验证、许可影响、网络规划和迁移后监控。大多数清单跳过这些因为它们是"软"话题。但软话题导致硬问题。'),
    para('我们的清单分为7个阶段，每个阶段有具体检查点。我们每次迁移都使用它，无论是VMware到VMware（版本升级）、VMware到Proxmox、VMware到Sangfor，还是VMware到云。'),
    h2('阶段1：迁移前评估（第1周）'),
    para('评估阶段确定你的迁移计划是否现实。大多数迁移失败都可追溯到不完整的评估。'),
    para('技术检查点：'),
    para('[ ] 完整VM清单——每个VM的操作系统、CPU、RAM、磁盘、网络配置、依赖关系。'),
    para('[ ] 工作负载利用率分析——每个VM 30天平均CPU、内存、磁盘I/O、网络I/O。'),
    para('[ ] 存储评估——总存储使用量、精简配置vs厚配置、存储性能基线。'),
    para('[ ] 网络评估——VLAN结构、防火墙规则、DNS依赖、负载均衡器配置。'),
    para('[ ] 兼容性检查——验证所有硬件和软件与目标平台兼容。'),
    para('[ ] 第三方依赖映射——需要更新的备份代理、监控工具、管理插件。'),
    para('业务检查点：'),
    para('[ ] 识别关键业务流程及其支持的VM。'),
    para('[ ] 确定每个关键工作负载的RPO/RTO。'),
    para('[ ] 识别禁迁期——不允许迁移的业务时段。'),
    para('[ ] 确认预算和时间表与业务期望一致。'),
    para('[ ] 利益相关者签署迁移计划和停机窗口。'),
    h2('阶段2：利益相关者沟通（第1-2周）'),
    para('这是我们2023年灾难发生的地方。技术团队知道迁移。业务团队不知道。以下是我的沟通协议：'),
    para('沟通检查点：'),
    para('[ ] 通知IT领导层——正式迁移计划文档，包含时间表、风险和回滚程序。'),
    para('[ ] 通知部门主管——哪些系统将受影响以及何时。使用通俗语言，不是技术术语。'),
    para('[ ] 通知终端用户——任何停机至少提前2周通知。包括：什么在变、什么时候、多久、他们需要做什么。'),
    para('[ ] 通知外部利益相关者——可能受影响的客户、合作伙伴、供应商。'),
    para('[ ] 建立沟通渠道——用于迁移更新的专用Slack/Teams频道或邮件组。'),
    para('[ ] 指定迁移沟通负责人——一个人负责所有迁移沟通。'),
    para('[ ] 准备紧急联系人列表——凌晨2点出问题时打电话给谁。'),
    h2('阶段3：准备和暂存（第2-4周）'),
    para('这是技术基础工作发生的地方。不要跳过这些步骤。'),
    para('基础设施检查点：'),
    para('[ ] 部署目标基础设施——目的地的服务器、存储、网络。'),
    para('[ ] 验证网络连接——测试源和目标之间的吞吐量、延迟和可靠性。'),
    para('[ ] 配置存储——在目标上设置数据存储、LUN或存储池。'),
    para('[ ] 安装和配置目标虚拟机管理程序或平台。'),
    para('[ ] 设置管理工具——新环境的监控、备份、告警。'),
    para('[ ] 在新平台上测试备份和恢复——迁移任何东西之前，确认你能恢复。'),
    para('数据检查点：'),
    para('[ ] 对所有要迁移的VM进行完整备份——不仅仅是快照，完整备份。'),
    para('[ ] 验证备份完整性——恢复一个备份确认数据完整且一致。'),
    para('[ ] 记录当前VM配置——导出VMX文件、网络配置、存储映射。'),
    para('[ ] 记录当前性能基线——这些成为你迁移后的比较目标。'),
    h2('阶段4：试点迁移（第4-5周）'),
    para('总是从小处开始。先迁移3-5个非关键VM。这在没有风险的情况下验证流程。'),
    para('试点检查点：'),
    para('[ ] 选择试点VM——选择代表不同工作负载类型的VM（数据库、Web服务器、文件服务器）。'),
    para('[ ] 执行试点迁移——按照你计划用于生产的确切程序。'),
    para('[ ] 验证试点VM——启动、网络连接、应用功能、性能。'),
    para('[ ] 测试回滚——如果出问题，你能将试点VM恢复到源环境吗？'),
    para('[ ] 记录遇到的问题——你在试点中遇到的每个问题都是你不会在生产中遇到的问题。'),
    para('[ ] 根据试点经验更新迁移程序。'),
    para('[ ] 获得利益相关者批准继续生产迁移。'),
    h2('阶段5：生产迁移（第5-10周）'),
    para('这是主要事件。分批执行，不是一次全部。'),
    para('迁移执行检查点：'),
    para('[ ] 安排维护窗口——向所有利益相关者传达确切的开始和结束时间。'),
    para('[ ] 迁移前快照——迁移前对每个VM拍摄快照。这是你的回滚点。'),
    para('[ ] 执行迁移——按照文档化的程序逐步操作。'),
    para('[ ] 迁移后验证——启动、网络、应用功能、性能比较。'),
    para('[ ] 更新DNS和网络配置——将用户指向新基础设施。'),
    para('[ ] 监控24小时——观察性能问题、错误或意外行为。'),
    para('[ ] 通知利益相关者迁移完成——确认系统可操作。'),
    para('批次管理检查点：'),
    para('[ ] 先迁移第3层VM（最低风险）。'),
    para('[ ] 接着迁移第2层VM（中等风险）。'),
    para('[ ] 最后迁移第1层VM（最高风险，需要最多验证）。'),
    para('[ ] 如果出现问题，在批次之间暂停——问题解决前不要继续。'),
    h2('阶段6：验证和优化（第10-12周）'),
    para('迁移在VM运行时不算完成。在你确认一切工作得和以前一样好（或更好）时才算完成。'),
    para('验证检查点：'),
    para('[ ] 性能比较——将迁移后指标与迁移前基线比较。'),
    para('[ ] 应用测试——所有关键应用的功能测试。'),
    para('[ ] 用户验收测试——让实际用户验证他们的系统工作。'),
    para('[ ] 备份验证——确认所有备份作业在新平台上运行。'),
    para('[ ] 监控验证——确认所有告警和仪表板可操作。'),
    para('[ ] 安全审查——验证防火墙规则、访问控制和加密完好。'),
    para('[ ] 文档更新——更新所有基础设施文档以反映新环境。'),
    h2('阶段7：退役和收尾（第12-13周）'),
    para('最后阶段：清理旧环境并正确关闭项目。'),
    para('退役检查点：'),
    para('[ ] 验证所有VM已迁移——没有VM遗留在旧平台上。'),
    para('[ ] 对旧环境进行最终备份——保留30-90天作为保险。'),
    para('[ ] 退役旧基础设施——关电、拔线、重新利用或出售。'),
    para('[ ] 回收许可——VMware许可通常可以转售或重新分配。'),
    para('[ ] 最终利益相关者签署——确认迁移完成并被接受。'),
    para('[ ] 项目复盘——什么做得好、什么可以改进、经验教训。'),
    para('[ ] 归档迁移文档——保留以供将来参考。'),
    h2('我们如何使用这个清单'),
    para('每次迁移都有自己的清单副本。我们使用共享电子表格，每个检查点有：项目描述、指定负责人、目标日期、完成日期和备注。'),
    para('迁移期间我们每天审查清单。任何未勾选的项目都会被标记。任何延迟的项目都会被升级。这个简单过程自2023年以来防止了每一次灾难。'),
    para('还有一件事：我们在所有复选框都勾选之前不将标记迁移为完成。没有例外。如果一个复选框无法勾选（因为项目不适用），它被记录为"不适用——原因：..."并由项目负责人签署。'),
    h2('这个清单防止的常见错误'),
    para('错误1：没有利益相关者沟通就迁移。清单迫使你通知每个相关方。如果有人抱怨没有被告知，你可以指向沟通日志。'),
    para('错误2：跳过试点。清单要求生产前进行试点迁移。我们从未后悔在试点上多花一周。'),
    para('错误3：没有回滚计划。每个迁移步骤都包含回滚选项。如果出问题，你可以撤销迁移而不需要从头开始。'),
    para('错误4：忘记备份验证。迁移而不确认你能从备份恢复就像开车没有刹车。清单迫使你在迁移前测试备份和恢复。'),
    para('错误5：不完整验证。清单要求性能比较、应用测试、用户验收测试和安全审查。跳过任何这些都可能留下未发现的问题。'),
    h2('结论：清单拯救职业生涯'),
    para('我们在2023年失去的客户？两年后我们用一次完美无缺的迁移赢回了他们。他们告诉我们区别在于清单——他们可以看到每一步、每个负责人、每个日期。这给了他们信心，我们知道我们在做什么。'),
    para('以下是你的行动计划：'),
    para('1. 下载或复制这个清单。'),
    para('2. 根据你的环境定制——根据需要添加或删除检查点。'),
    para('3. 与你的团队分享并获得支持。'),
    para('4. 在你下次迁移中使用它。每次。'),
    para('5. 每次迁移后根据经验教训更新它。'),
    para('迁移清单不令人兴奋。它们不创新。但它们有效。根据我们的经验，"有效"每次都胜过"令人兴奋"。'),
    h2('FAQ'),
    h3('问：使用这个清单的典型VMware迁移需要多长时间？'),
    para('对于中型环境（50-200个VM）：10-14周。阶段1-2（评估和沟通）：2周。阶段3（准备）：2-3周。阶段4（试点）：1-2周。阶段5（生产迁移）：4-6周。阶段6-7（验证和退役）：2-3周。'),
    h3('问：我可以将此清单用于非VMware迁移吗？'),
    para('可以，清单与平台无关。阶段和检查点适用于任何基础设施迁移：VMware到Proxmox、VMware到云、物理到虚拟，甚至数据中心搬迁。'),
    h3('问：如果我在试点中发现需要更改时间表的问题怎么办？'),
    para('这正是试点的目的。如果试点揭示重大问题，立即向利益相关者传达时间表影响。延迟迁移2周比带着已知问题匆忙进入生产更好。'),
    h3('问：如果利益相关者拒绝批准停机窗口怎么办？'),
    para('呈现商业案例：迁移成本（包括停机）vs 不迁移成本（持续风险、更高许可成本、合规问题）。如果他们仍然拒绝，用风险评估文件升级到高管层。'),
    h3('问：迁移后我应该保持旧基础设施运行吗？'),
    para('是的，30-90天。保持关电但可访问。如果新平台出现问题需要旧环境数据，你有备选方案。90天后，你可以安全退役。'),
  ],
};

console.log('Article 6 prepared: vmware-migration-checklist');
console.log(`  Content blocks: ${article6.content.length}`);
console.log(`  Chinese blocks: ${article6.contentZh.length}`);

// ============================================================
// ARTICLE 7: vmware-srm-disaster-recovery-guide
// ============================================================
const article7 = {
  _id: 'post-vmware-srm-disaster-recovery-guide',
  _type: 'post',
  title: 'VMware SRM Disaster Recovery: The Deep Dive Guide We Wish Existed When We Started',
  titleZh: 'VMware SRM灾难恢复：我们当初开始时希望存在的深度指南',
  slug: { current: 'vmware-srm-disaster-recovery-guide', _type: 'slug' },
  category: 'technical',
  excerpt: 'VMware Site Recovery Manager is the gold standard for virtualized disaster recovery. But most guides stop at "install and configure." This one goes deeper — architecture decisions, network design, replication tuning, and the real-world gotchas that vendor docs do not cover.',
  excerptZh: 'VMware Site Recovery Manager是虚拟化灾难恢复的黄金标准。但大多数指南止步于"安装和配置"。这篇更深入——架构决策、网络设计、复制调优，以及供应商文档未涵盖的真实世界陷阱。',
  coverImage: 'https://picsum.photos/seed/vmware-srm-disaster-recovery-guide/800/450',
  author: 'TechGuru Team',
  publishedAt: '2025-01-15T00:00:00Z',
  featured: false,
  tags: ['vmware', 'srm', 'disaster-recovery', 'business-continuity', 'enterprise'],
  content: [
    para('The call came at 4:15 AM. A hospital\'s primary data center had a coolant leak. The server room was flooding. Not metaphorically — literally flooding. Water was pooling around the server racks.'),
    para('The IT team initiated VMware SRM failover. Tier 1 workloads (EHR, lab systems, pharmacy) failed over to the DR site in 8 minutes. Tier 2 (imaging, billing) followed in 20 minutes. By 5:00 AM, the hospital was fully operational from the DR site. Total cost of the disaster: 2.3M PHP for the water damage to the primary site. Cost of the DR failure: zero. Patient care continued uninterrupted.'),
    para('That was the third time SRM saved this client from a major disaster. Each time, the failover was faster than the last — because each time, we learned something and improved the configuration.'),
    para('This guide is the accumulated knowledge from deploying SRM across 20+ Philippine enterprises over 6 years. It goes beyond the standard VMware documentation into the decisions, trade-offs, and real-world configurations that make the difference between an 8-minute failover and a 2-hour panic.'),
    h2('SRM Architecture: The Decisions That Matter'),
    para('SRM deployment is not one-size-fits-all. The architecture decisions you make early determine how well SRM performs when you need it most.'),
    h3('Decision 1: Single-Site vs Multi-Site SRM'),
    para('Single-site SRM: one vCenter at the primary site, one vCenter at the DR site, one SRM pair. This is the standard deployment and works for most scenarios.'),
    para('Multi-site SRM: multiple primary sites connecting to a single DR site. This is common for organizations with multiple data centers that all need DR protection. The complexity increases significantly — you need to manage multiple protection groups, handle conflicting RPO requirements, and plan for scenarios where multiple primary sites fail simultaneously.'),
    para('Our recommendation: start with single-site SRM. Only move to multi-site if you genuinely have multiple primary sites. Multi-site is 3x more complex to manage.'),
    h3('Decision 2: Synchronous vs Asynchronous Replication'),
    para('Synchronous replication: data is written to both primary and DR sites simultaneously. Zero data loss (RPO = 0). But requires low-latency, high-bandwidth connectivity between sites (< 5ms latency, >= 1 Gbps).'),
    para('Asynchronous replication: data is written to the primary site first, then replicated to DR. Small data loss window (RPO = 5-15 minutes typical). Works over standard WAN connections.'),
    para('Our recommendation: use async for 90% of workloads. Only use sync for the most critical databases where zero data loss is a regulatory requirement. Sync replication doubles your storage costs and requires expensive network infrastructure. Most Philippine enterprises use async with a 15-minute RPO.'),
    h3('Decision 3: vSphere Replication vs Array-Based Replication'),
    para('vSphere Replication (VR): software-based replication included with SRM. Runs as a virtual appliance on each ESXi host. No storage vendor involvement required.'),
    para('Array-based replication: uses storage array features (NetApp SnapMirror, Dell RecoverPoint, etc.) to replicate at the storage level. Faster, more efficient, but requires matching storage arrays at both sites.'),
    para('Our recommendation: use vSphere Replication unless you have a compelling reason for array-based. VR is simpler, cheaper, and sufficient for most workloads. We have seen clients save 40-50% on DR infrastructure by choosing VR over array-based replication.'),
    h2('Network Design for SRM'),
    para('Network design is where most SRM deployments succeed or fail. Get this right, and everything else is straightforward. Get this wrong, and you will be debugging network issues during your next disaster.'),
    para('The SRM network has four functional components:'),
    para('1. Management network: used by SRM for communication between the primary and DR sites. Must be reliable and low-latency. We recommend a dedicated VLAN for SRM management traffic.'),
    para('2. Replication network: used by vSphere Replication to transfer VM data. This is the highest-bandwidth requirement. For a 15-minute RPO with 2TB of change data, you need approximately 20 Mbps sustained upload.'),
    para('3. VM network: the networks your VMs use. After failover, VMs need to be reachable on the DR site. This requires careful IP planning.'),
    para('4. Heartbeat network: used by vCenter and SRM to detect failures. This can share the management network.'),
    para('IP address planning is critical. There are two approaches:'),
    para('Static IP: VMs keep the same IP addresses at the DR site. This requires network routing changes (BGP or static routes) to redirect traffic to the DR site after failover. Simpler for applications, more complex for networking.'),
    para('IP customization: SRM automatically changes VM IP addresses during failover. The VM gets a new IP at the DR site, and DNS is updated to point to the new IP. More complex for applications (some apps cache IP addresses), simpler for networking.'),
    para('Our recommendation: use static IPs with network routing for Tier 1 workloads. Use IP customization for Tier 2/3. This gives you the best of both worlds — fast failover for critical systems, simplified management for everything else.'),
    h2('Replication Configuration Deep Dive'),
    para('Replication is the heart of SRM. Getting the configuration right determines your RPO, failover time, and bandwidth requirements.'),
    para('Replication groups: organize VMs into protection groups based on recovery priority, not department structure. A typical hospital might have: Group 1 (EHR + Lab + Pharmacy), Group 2 (Imaging + Billing), Group 3 (Email + File Servers).'),
    para('RPO settings: this is the maximum amount of data you are willing to lose. Lower RPO = more replication traffic = more bandwidth needed.'),
    para('RPO 5 minutes: requires 4x the bandwidth of RPO 15 minutes. Only for the most critical workloads.'),
    para('RPO 15 minutes: our standard recommendation. Balances data protection with bandwidth cost.'),
    para('RPO 1 hour: acceptable for Tier 3 workloads. Significant bandwidth savings.'),
    para('Snapshot scheduling: SRM uses snapshots to capture point-in-time data for replication. The snapshot frequency must align with your RPO. For RPO 15 minutes, snapshots every 15 minutes.'),
    para('Quiescing: for databases and applications that need consistent snapshots, enable guest OS quiescing. This uses VMware Tools to flush writes to disk before taking the snapshot. Without quiescing, you may get crash-consistent snapshots that require database recovery after failover.'),
    para('Bandwidth calculation: the formula we use is (Daily Change Rate x Replication Window) / (RPO x Available Bandwidth). For a typical hospital with 1TB of protected VMs and 10% daily change rate, RPO 15 minutes requires approximately 15-20 Mbps sustained bandwidth.'),
    h2('Failover Planning and Execution'),
    para('Failover is not a button you press in panic. It is a planned, documented, tested procedure.'),
    para('Failover plan components:'),
    para('1. Pre-failover checklist: verify replication health, check DR site capacity, notify stakeholders, confirm network routing is ready.'),
    para('2. Failover execution: use SRM to initiate failover. SRM will: stop replication, power on VMs at DR site in defined order, apply IP customization, run post-failover scripts.'),
    para('3. Post-failover validation: verify VMs are running, applications are accessible, data is consistent, DNS is updated, users can connect.'),
    para('4. Communication: notify stakeholders that failover is complete and systems are operational.'),
    para('Failover testing: test monthly. Not quarterly. Monthly. Here is why: configurations drift, software updates change behavior, network conditions evolve. A test you skip is a test you risk.'),
    para('Test types:'),
    para('Planned failover test: migrate VMs to DR, verify, migrate back. Full validation but requires downtime.'),
    para('Test failover: SRM creates a test environment at DR using the replicated data. VMs run in isolation (no production traffic). Verify without impacting production. This is what you should do monthly.'),
    para('Emergency failover: triggered during an actual disaster. Follow the documented failover plan.'),
    h2('Recovery Point Objective (RPO) and Recovery Time Objective (RTO) Tuning'),
    para('RPO and RTO are not just numbers on a document. They are engineering parameters that drive specific configuration decisions.'),
    para('For RPO 15 minutes:'),
    para('- vSphere Replication with 15-minute recovery point aim.'),
    para('- Snapshot quiescing enabled for database VMs.'),
    para('- Minimum 20 Mbps sustained bandwidth per 1TB of protected data.'),
    para('- Daily replication health checks.'),
    para('For RTO 30 minutes:'),
    para('- Pre-allocated resources at DR site (placeholders or reserved capacity).'),
    para('- Automated post-failover scripts (database startup, application verification).'),
    para('- Pre-configured network routing for fast failover.'),
    para('- Tested failover plan with documented steps.'),
    para('For RPO 0 (zero data loss):'),
    para('- Synchronous replication (requires < 5ms latency).'),
    para('- Significant bandwidth and storage investment.'),
    para('- Only for the most critical workloads (financial transaction databases, regulatory systems).'),
    h2('Best Practices from 20+ SRM Deployments'),
    para('1. Test failover monthly. We cannot emphasize this enough. Monthly testing catches configuration drift, compatibility issues, and human errors before they become disasters.'),
    para('2. Automate everything possible. DNS updates, post-failover scripts, notification emails, health checks. Manual steps during a disaster add minutes to your failover time.'),
    para('3. Use protection groups by priority, not by department. When you failover, you want Tier 1 VMs to move together regardless of which department owns them.'),
    para('4. Document the human steps. SRM handles technical failover. But someone still needs to call the hospital administrator, notify the DOH, update the insurance company. Document these steps.'),
    para('5. Monitor replication health daily. A broken replication means your DR is not protected. Set up alerts for replication lag exceeding your RPO.'),
    para('6. Keep DR site resources warm. Cold DR sites take longer to failover. Keep minimal production workloads running at DR to validate hardware and network continuously.'),
    para('7. Plan for failback. After a disaster, you need to failback to the primary site once it is restored. Many organizations plan for failover but not failback. Include failback in your runbook.'),
    para('8. Use SRM with vSphere HA for defense in depth. HA handles host failures within a site. SRM handles site-level disasters. Together, they provide comprehensive protection.'),
    h2('Common Mistakes in SRM Deployments'),
    para('Mistake 1: Setting RPO too low. RPO 5 minutes sounds great, but it requires 4x the bandwidth of RPO 15 minutes. For most workloads, RPO 15 minutes provides excellent protection at a fraction of the cost.'),
    para('Mistake 2: Not testing network failover. SRM moves VMs, but DNS, load balancers, and firewall rules also need to failover. Test the complete stack, not just the VM failover.'),
    para('Mistake 3: Ignoring the return failback. After a disaster, you need to get back to the primary site. Plan for failback from day one.'),
    para('Mistake 4: Over-replicating. Replicating test environments and dev servers wastes bandwidth. Protect Tier 1 and Tier 2. Use backup for Tier 3.'),
    para('Mistake 5: Single point of failure in DR site. If your DR site has a single storage array, single network switch, or single power supply, your DR site itself is a risk. Design for redundancy.'),
    para('Mistake 6: Not involving application owners. The IT team sets up SRM, but application owners know their recovery requirements. Involve them in planning.'),
    para('Mistake 7: Forgetting about licensing. Some software licenses are tied to specific hardware. Moving VMs to DR may require additional licenses. Check before you failover.'),
    h2('Conclusion: DR Is Not a Product, It Is a Process'),
    para('VMware SRM is a powerful tool, but it is only as good as the process around it. The best SRM configuration in the world will fail if nobody knows how to trigger failover, if the runbook is outdated, or if nobody has ever tested the procedure.'),
    para('Here is your action plan:'),
    para('1. Assess your current DR posture. What is your RPO? Your RTO? When was the last failover test?'),
    para('2. If you do not have SRM, start with a PoC. Deploy SRM for your most critical 5-10 VMs.'),
    para('3. If you have SRM but have not tested in 6+ months, schedule a test failover this month.'),
    para('4. Automate DNS updates and post-failover scripts.'),
    para('5. Document your failover plan — including the human steps.'),
    para('6. Test monthly. No exceptions.'),
    para('That hospital with the coolant leak? Their SRM has been tested 36 times in 3 years. Every month, rain or shine. When the real disaster came, it was routine. That is what DR should feel like — routine, not heroic.'),
    h2('FAQ'),
    h3('Q: How much does VMware SRM cost?'),
    para('SRM licensing is per-protected VM. Typical cost: 200-300 USD per VM. For 50 protected VMs: 10,000-15,000 USD in licensing. Add vSphere Replication (included with SRM) and DR site infrastructure. Total project cost varies widely based on scale.'),
    h3('Q: Can SRM protect physical servers?'),
    para('No. SRM only protects virtual machines. For physical server DR, you need traditional backup solutions (Veeam, Commvault) or storage-based replication. Some organizations virtualize their physical servers specifically to enable SRM protection.'),
    h3('Q: What happens if the DR site is also affected by the disaster?'),
    para('SRM only works between two sites. If both sites are affected (regional earthquake, widespread power outage), SRM cannot help. For this scenario, consider a third recovery option: cloud DR (AWS, Azure) or a third physical site.'),
    h3('Q: How long does a typical SRM failover take?'),
    para('Depends on VM count, size, and network speed. Typical range: 5-30 minutes for Tier 1 workloads. We have seen failovers as fast as 3 minutes (5 small VMs) and as slow as 45 minutes (50 large VMs with database recovery).'),
    h3('Q: Do I need matching hardware at primary and DR sites?'),
    para('No. SRM is hardware-agnostic. The DR site can have different server models, different storage arrays, and different network equipment. VMs are converted during failover to match the DR site hardware. However, performance may differ if the DR site hardware is less powerful.'),
  ],
  contentZh: [
    para('电话在凌晨4:15打来。一家医院的主数据中心冷却液泄漏。服务器室在淹水。不是比喻——字面意思在淹水。水在服务器机架周围积聚。'),
    para('IT团队启动了VMware SRM故障转移。第1层工作负载（EHR、实验室系统、药房）在8分钟内故障转移到DR站点。第2层（影像、计费）在20分钟内跟进。到5:00 AM，医院已从DR站点完全运营。灾难总成本：主站点水损230万比索。DR故障成本：零。患者护理持续不间断。'),
    para('这是SRM第三次将这个客户从重大灾难中拯救出来。每次故障转移都比上次更快——因为每次我们都学到了东西并改进了配置。'),
    para('本指南是6年内在20多家菲律宾企业部署SRM积累的知识。它超越了标准VMware文档，深入到决策、权衡和真实世界配置——这些让8分钟故障转移和2小时恐慌之间产生差异。'),
    h2('SRM架构：重要的决策'),
    para('SRM部署不是一刀切的。你早期做出的架构决策决定了SRM在最需要时的表现。'),
    h3('决策1：单站点vs多站点SRM'),
    para('单站点SRM：主站点一个vCenter，DR站点一个vCenter，一对SRM。这是标准部署，适用于大多数场景。'),
    para('多站点SRM：多个主站点连接到单个DR站点。这在有多个数据中心都需要DR保护的组织中很常见。复杂性显著增加——你需要管理多个保护组，处理冲突的RPO要求，并规划多个主站点同时故障的场景。'),
    para('我们的建议：从单站点SRM开始。只有在你确实有多个主站点时才转向多站点。多站点管理复杂度增加3倍。'),
    h3('决策2：同步vs异步复制'),
    para('同步复制：数据同时写入主站点和DR站点。零数据丢失（RPO = 0）。但需要站点间的低延迟、高带宽连接（< 5ms延迟，>= 1 Gbps）。'),
    para('异步复制：数据先写入主站点，然后复制到DR。小数据丢失窗口（RPO = 典型5-15分钟）。适用于标准WAN连接。'),
    para('我们的建议：90%的工作负载使用异步。只对零数据丢失是监管要求的最关键数据库使用同步。同步复制将存储成本翻倍并需要昂贵的网络基础设施。大多数菲律宾企业使用异步，RPO为15分钟。'),
    h3('决策3：vSphere复制vs基于数组的复制'),
    para('vSphere复制（VR）：SRM附带的基于软件的复制。作为虚拟设备运行在每个ESXi主机上。不需要存储供应商参与。'),
    para('基于数组的复制：使用存储阵列功能（NetApp SnapMirror、Dell RecoverPoint等）在存储级别复制。更快、更高效，但需要两个站点匹配的存储阵列。'),
    para('我们的建议：除非有令人信服的理由，否则使用vSphere复制。VR更简单、更便宜，对大多数工作负载足够。我们看到客户通过选择VR而非基于数组的复制节省了40-50%的DR基础设施成本。'),
    h2('SRM的网络设计'),
    para('网络设计是大多数SRM部署成功或失败的地方。这个做对了，其他一切都简单。做错了，你将在下次灾难期间调试网络问题。'),
    para('SRM网络有四个功能组件：'),
    para('1. 管理网络：SRM用于主站点和DR站点间通信。必须可靠且低延迟。我们建议为SRM管理流量使用专用VLAN。'),
    para('2. 复制网络：vSphere Replication用于传输VM数据。这是最高带宽需求。对于15分钟RPO和2TB变更数据，你需要大约20 Mbps持续上传。'),
    para('3. VM网络：你的VM使用的网络。故障转移后，VM需要在DR站点可达。这需要仔细的IP规划。'),
    para('4. 心跳网络：vCenter和SRM用于检测故障。可以共享管理网络。'),
    para('IP地址规划至关重要。有两种方法：'),
    para('静态IP：VM在DR站点保持相同的IP地址。这需要网络路由更改（BGP或静态路由）在故障转移后将流量重定向到DR站点。对应用更简单，对网络更复杂。'),
    para('IP自定义：SRM在故障转移期间自动更改VM IP地址。VM在DR站点获得新IP，DNS更新指向新IP。对应用更复杂（一些应用缓存IP地址），对网络更简单。'),
    para('我们的建议：对第1层工作负载使用静态IP和网络路由。对第2/3层使用IP自定义。这给你两全其美——关键系统快速故障转移，其他一切简化管理。'),
    h2('复制配置深入探讨'),
    para('复制是SRM的核心。配置正确决定了你的RPO、故障转移时间和带宽需求。'),
    para('复制组：根据恢复优先级而非部门结构将VM组织到保护组中。一家典型医院可能有：组1（EHR + 实验室 + 药房），组2（影像 + 计费），组3（邮件 + 文件服务器）。'),
    para('RPO设置：这是你愿意丢失的最大数据量。更低RPO = 更多复制流量 = 需要更多带宽。'),
    para('RPO 5分钟：需要RPO 15分钟4倍的带宽。仅用于最关键的工作负载。'),
    para('RPO 15分钟：我们的标准建议。平衡数据保护和带宽成本。'),
    para('RPO 1小时：可接受用于第3层工作负载。显著节省带宽。'),
    para('快照调度：SRM使用快照捕获时间点数据进行复制。快照频率必须与RPO对齐。对于RPO 15分钟，每15分钟快照一次。'),
    para('静默：对于需要一致快照的数据库和应用，启用客户操作系统静默。这使用VMware Tools在拍摄快照前将写入刷新到磁盘。没有静默，你可能获得崩溃一致的快照，需要在故障转移后进行数据库恢复。'),
    para('带宽计算：我们使用的公式是（每日变化率 x 复制窗口）/（RPO x 可用带宽）。对于拥有1TB受保护VM和10%日变化率的典型医院，RPO 15分钟需要大约15-20 Mbps持续带宽。'),
    h2('故障转移规划和执行'),
    para('故障转移不是你在恐慌中按的按钮。它是计划好的、文档化的、经过测试的程序。'),
    para('故障转移计划组件：'),
    para('1. 故障转移前清单：验证复制健康、检查DR站点容量、通知利益相关者、确认网络路由就绪。'),
    para('2. 故障转移执行：使用SRM启动故障转移。SRM将：停止复制、按定义顺序在DR站点启动VM、应用IP自定义、运行故障转移后脚本。'),
    para('3. 故障转移后验证：验证VM正在运行、应用可访问、数据一致、DNS已更新、用户可以连接。'),
    para('4. 沟通：通知利益相关者故障转移完成且系统可操作。'),
    para('故障转移测试：每月测试。不是每季度。每月。原因是：配置漂移、软件更新改变行为、网络条件演变。你跳过的测试就是你冒险的测试。'),
    para('测试类型：'),
    para('计划故障转移测试：将VM迁移到DR、验证、迁移回来。完全验证但需要停机。'),
    para('测试故障转移：SRM使用复制数据在DR创建测试环境。VM在隔离中运行（无生产流量）。验证不影响生产。这是你应该每月做的。'),
    para('紧急故障转移：在实际灾难期间触发。按照文档化的故障转移计划执行。'),
    h2('恢复点目标（RPO）和恢复时间目标（RTO）调优'),
    para('RPO和RTO不仅仅是文档上的数字。它们是驱动特定配置决策的工程参数。'),
    para('对于RPO 15分钟：'),
    para('- vSphere复制，恢复点目标15分钟。'),
    para('- 数据库VM启用快照静默。'),
    para('- 每1TB受保护数据至少20 Mbps持续带宽。'),
    para('- 每日复制健康检查。'),
    para('对于RTO 30分钟：'),
    para('- DR站点预分配资源（占位符或预留容量）。'),
    para('- 自动化故障转移后脚本（数据库启动、应用验证）。'),
    para('- 预配置网络路由用于快速故障转移。'),
    para('- 经过测试的故障转移计划，有文档化步骤。'),
    para('对于RPO 0（零数据丢失）：'),
    para('- 同步复制（需要< 5ms延迟）。'),
    para('- 显著的带宽和存储投资。'),
    para('- 仅用于最关键的工作负载（金融交易数据库、监管系统）。'),
    h2('来自20+次SRM部署的最佳实践'),
    para('1. 每月测试故障转移。我们无法强调这一点。每月测试在配置漂移、兼容性问题和人为错误变成灾难之前捕获它们。'),
    para('2. 自动化一切可能的。DNS更新、故障转移后脚本、通知邮件、健康检查。灾难期间的手动步骤为故障转移时间增加分钟。'),
    para('3. 按优先级而非部门使用保护组。当你故障转移时，你希望第1层VM一起移动，不管哪个部门拥有它们。'),
    para('4. 记录人工步骤。SRM处理技术故障转移。但仍然需要有人通知医院管理员、通知卫生部、更新保险公司。记录这些步骤。'),
    para('5. 每天监控复制健康。损坏的复制意味着你的DR没有保护。设置复制延迟超过RPO的告警。'),
    para('6. 保持DR站点资源温热。冷DR站点故障转移需要更长时间。在DR保持最少生产工作负载运行以持续验证硬件和网络。'),
    para('7. 规划回切。灾难之后，你需要在主站点恢复后回切。许多组织规划了故障转移但没有规划回切。在运维手册中包含回切。'),
    para('8. 将SRM与vSphere HA结合用于纵深防御。HA处理站点内的主机故障。SRM处理站点级灾难。两者一起提供全面保护。'),
    h2('SRM部署中的常见错误'),
    para('错误1：设置RPO太低。RPO 5分钟听起来不错，但需要RPO 15分钟4倍的带宽。对于大多数工作负载，RPO 15分钟以一小部分成本提供出色保护。'),
    para('错误2：不测试网络故障转移。SRM移动VM，但DNS、负载均衡器和防火墙规则也需要故障转移。测试完整栈，不仅仅是VM故障转移。'),
    para('错误3：忽略回切。灾难之后，你需要回到主站点。从第一天就规划回切。'),
    para('错误4：过度复制。复制测试环境和开发服务器浪费带宽。保护第1层和第2层。对第3层使用备份。'),
    para('错误5：DR站点单点故障。如果你的DR站点有单一存储阵列、单一网络交换机或单一电源，DR站点本身就是风险。设计冗余。'),
    para('错误6：不涉及应用所有者。IT团队设置SRM，但应用所有者知道他们的恢复要求。在规划中包含他们。'),
    para('错误7：忘记许可。一些软件许可与特定硬件绑定。将VM移到DR可能需要额外许可。故障转移前检查。'),
    h2('结论：DR不是产品，是过程'),
    para('VMware SRM是强大的工具，但它只和围绕它的过程一样好。世界上最好的SRM配置也会失败，如果没人知道如何触发故障转移、运维手册过时、或没人测试过程序。'),
    para('以下是你的行动计划：'),
    para('1. 评估你当前的DR姿态。你的RPO是什么？RTO是什么？上次故障转移测试是什么时候？'),
    para('2. 如果你没有SRM，从PoC开始。为你最关键的5-10个VM部署SRM。'),
    para('3. 如果你有SRM但6个月以上没有测试，本月安排一次测试故障转移。'),
    para('4. 自动化DNS更新和故障转移后脚本。'),
    para('5. 记录你的故障转移计划——包括人工步骤。'),
    para('6. 每月测试。没有例外。'),
    para('那家冷却液泄漏的医院？他们的SRM在3年内测试了36次。每个月，风雨无阻。当真正的灾难来临时，它是例行公事。DR应该感觉像这样——例行，而不是英勇。'),
    h2('FAQ'),
    h3('问：VMware SRM成本多少？'),
    para('SRM许可按受保护VM计费。典型成本：每个VM 200-300美元。对于50个受保护VM：许可10,000-15,000美元。加上vSphere复制（SRM附带）和DR站点基础设施。总项目成本根据规模差异很大。'),
    h3('问：SRM可以保护物理服务器吗？'),
    para('不可以。SRM只保护虚拟机。对于物理服务器DR，你需要传统备份解决方案（Veeam、Commvault）或基于存储的复制。一些组织专门将物理服务器虚拟化以启用SRM保护。'),
    h3('问：如果DR站点也受灾难影响会怎样？'),
    para('SRM只在两个站点之间工作。如果两个站点都受影响（区域性地震、大范围停电），SRM无法帮助。对于这种场景，考虑第三个恢复选项：云DR（AWS、Azure）或第三个物理站点。'),
    h3('问：典型的SRM故障转移需要多长时间？'),
    para('取决于VM数量、大小和网络速度。典型范围：第1层工作负载5-30分钟。我们见过最快3分钟（5个小VM）和最慢45分钟（50个大VM带数据库恢复）。'),
    h3('问：我需要在主站点和DR站点匹配硬件吗？'),
    para('不需要。SRM与硬件无关。DR站点可以有不同的服务器型号、不同的存储阵列和不同的网络设备。VM在故障转移期间被转换以匹配DR站点硬件。但是，如果DR站点硬件性能较低，性能可能不同。'),
  ],
};

console.log('Article 7 prepared: vmware-srm-disaster-recovery-guide');
console.log(`  Content blocks: ${article7.content.length}`);
console.log(`  Chinese blocks: ${article7.contentZh.length}`);

async function uploadArticle(article) {
  try {
    const result = await client.createOrReplace(article);
    console.log(`  ✓ Uploaded: ${article.slug.current} (_id: ${result._id})`);
    return true;
  } catch (err) {
    console.error(`  ✗ Failed: ${article.slug.current} — ${err.message}`);
    return false;
  }
}

async function main() {
  const articles = [article5, article6, article7];
  let success = 0;
  let failed = 0;

  for (const article of articles) {
    const ok = await uploadArticle(article);
    if (ok) success++;
    else failed++;
  }

  console.log(`\nBatch 3 complete: ${success} uploaded, ${failed} failed`);
}

main().catch(console.error);
