import { createClient } from '@sanity/client';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const envContent = readFileSync(resolve(process.cwd(), '.env.local'), 'utf-8');
const tokenMatch = envContent.match(/SANITY_API_TOKEN=(.+)/);
const token = tokenMatch ? tokenMatch[1].trim() : null;

if (!token) {
  console.error('SANITY_API_TOKEN not found in .env.local');
  process.exit(1);
}

const client = createClient({
  projectId: 'r6ztl1oq',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token,
  useCdn: false,
});

function block(text, style = 'normal') {
  return { _type: 'block', style, children: [{ _type: 'span', text }] };
}
function h2(text) { return block(text, 'h2'); }
function h3(text) { return block(text, 'h3'); }
function para(text) { return block(text, 'normal'); }

// ============================================================
// ARTICLE 3: vmware-to-proxmox-migration
// ============================================================
const article3 = {
  _id: 'post-vmware-to-proxmox-migration',
  _type: 'post',
  title: 'VMware to Proxmox Migration: A Practical Guide from the Trenches (Not the Marketing Department)',
  titleZh: 'VMware到Proxmox迁移：来自实战的实用指南（不是市场部写的）',
  slug: { current: 'vmware-to-proxmox-migration', _type: 'slug' },
  category: 'technical',
  excerpt: 'Proxmox is free, open-source, and built on KVM. But migrating from VMware is not as simple as flipping a switch. Here is what actually happens when you move production workloads to Proxmox, based on real migrations in Philippine enterprises.',
  excerptZh: 'Proxmox免费、开源、基于KVM。但从VMware迁移不像拨个开关那么简单。以下是将生产工作负载迁移到Proxmox时实际发生的事情，基于菲律宾企业的真实迁移经验。',
  coverImage: 'https://picsum.photos/seed/vmware-to-proxmox-migration/800/450',
  author: 'TechGuru Team',
  publishedAt: '2025-01-15T00:00:00Z',
  featured: false,
  tags: ['vmware', 'proxmox', 'migration', 'open-source', 'kvm'],
  content: [
    para('The email subject line was blunt: "VMware is dead to us." It came from a CTO at a BPO company in Clark Freeport Zone. His VMware renewal had tripled, and he had just read a blog post about Proxmox — free, open-source, enterprise-ready. He wanted to migrate 200 VMs in 6 weeks.'),
    para('We told him 6 weeks was aggressive. He said the board had already approved the budget. We started the following Monday.'),
    para('That was 18 months ago. The migration took 11 weeks, not 6. We hit problems nobody warned us about. But the result was solid: 200 VMs running on Proxmox, zero licensing costs, and an IT team that now prefers it over VMware.'),
    para('This is the real story of migrating from VMware to Proxmox. No vendor pitch. No ideology. Just what worked, what broke, and what you should know before you start.'),
    h2('What Is Proxmox VE?'),
    para('Proxmox VE (Virtual Environment) is an open-source server virtualization platform. It combines KVM hypervisor and LXC container management into a single platform. Developed by Proxmox Server Solutions GmbH, based in Vienna, Austria.'),
    para('The core tech: Proxmox runs on Debian Linux. It uses KVM for full virtualization (running Windows, any Linux distro, or other OS as a VM) and LXC for lightweight containerized workloads. The web management interface is built into the platform — no separate vCenter-like appliance needed.'),
    para('Proxmox uses a cluster-based architecture. Multiple nodes form a cluster, and VMs can be migrated live between nodes. Storage is pluggable: local disks, ZFS, Ceph, NFS, iSCSI, or ZFS over iSCSI. The default and recommended storage is ZFS on local SSDs.'),
    para('Licensing model: free and open-source under AGPLv3. There is an optional "Proxmox VE Subscription" (per node, annually) that gives you access to the enterprise repository and email support. The subscription is not required — the software works fully without it. Typical cost: 110-820 EUR per node per year depending on support level.'),
    h2('Why Consider Proxmox Over VMware?'),
    para('The obvious reason is cost. After Broadcom restructured VMware licensing, many Philippine enterprises found themselves facing 5-10x cost increases. Proxmox eliminates licensing costs entirely. For a 10-node cluster, that is 50K-200K USD per year in VMware licensing you no longer pay.'),
    para('But cost is not the only reason. Here is what we have seen drive real adoption:'),
    para('1. Simplicity. Proxmox has one management interface. No vCenter, no NSX, no vRealize. For teams that are tired of managing six different VMware products, Proxmox feels like a breath of fresh air.'),
    para('2. ZFS integration. Proxmox ships with native ZFS support. For storage-heavy workloads, ZFS provides snapshots, compression, deduplication, and replication without requiring a separate storage array. We have clients running 50TB on ZFS without issues.'),
    para('3. Built-in backup. Proxmox Backup Server (PBS) is a separate open-source product that integrates natively with Proxmox VE. It provides incremental, deduplicated backups with verification. No Veeam license needed for basic backup scenarios.'),
    para('4. LXC containers. Proxmox supports LXC containers natively. For Linux workloads, containers are 3-5x more efficient than VMs. We run monitoring agents, DNS servers, and lightweight web services as containers on Proxmox, saving significant RAM and CPU.'),
    para('5. Community and transparency. With VMware, you get what Broadcom decides to give you. With Proxmox, the source code is public. Bugs get fixed by the community when the vendor is slow. This transparency matters for organizations that need to audit their infrastructure.'),
    h2('How We Migrate: The Step-by-Step Process'),
    para('Proxmox migration from VMware is not a "lift and shift." The virtual disk formats are different (VMDK vs QCOW2), the networking model is different, and the management paradigm is different. Here is how we handle it.'),
    h3('Step 1: Inventory and Assessment (Week 1)'),
    para('We export the full VM inventory from vCenter. For each VM, we capture: OS, CPU/RAM/disk, network configuration, installed applications, and any VMware-specific features in use (snapshots, vApps, resource pools, DRS rules).'),
    para('Key question: which VMs use VMware tools? These need special handling because Proxmox uses QEMU Guest Agent instead. We document every VM that has VMware Tools installed and plan the guest agent migration.'),
    para('Inventory output: a spreadsheet with every VM, its tier, migration complexity (low/medium/high), and estimated migration time.'),
    h3('Step 2: Proxmox Cluster Deployment (Week 1-2)'),
    para('We deploy the Proxmox cluster on new hardware. For most Philippine clients, this means:'),
    para('Hardware: 3-6 nodes (depending on workload), each with dual Intel Xeon, 128-256GB RAM, 2-4TB NVMe for local storage, 10GbE networking.'),
    para('Cluster setup: install Proxmox VE on each node, create cluster, join nodes, configure ZFS pools (typically RAIDZ1 or RAIDZ2 for balance of performance and redundancy).'),
    para('Storage: we use local ZFS for primary storage and NFS or Ceph for shared storage (ISO images, templates, backups).'),
    para('Networking: create VLANs for management, production, and storage traffic. Proxmox uses Linux bridges or Open vSwitch for virtual networking.'),
    para('One important note: Proxmox clusters need a quorum. For a 3-node cluster, you need at least 2 nodes running for the cluster to function. For even-numbered clusters, add a quorum device (a small VM on a third-party host or a dedicated hardware quorum device).'),
    h3('Step 3: VM Export from VMware (Week 2-3)'),
    para('This is where things get interesting. VMware VMs use VMDK disk format. Proxmox uses QCOW2. You need to convert the disk images.'),
    para('Method 1: Export via OVF/OVA. vCenter can export VMs as OVA files. We then extract the OVA (it is a TAR archive) and convert the VMDK to QCOW2 using qemu-img convert. This works well for most VMs.'),
    para('Method 2: Direct VMDK conversion. If you have access to the ESXi datastore, you can copy the VMDK files directly and convert them on the Proxmox host. Faster, but requires SSH access to ESXi.'),
    para('Method 3: For VMs with multiple disks, we use a scripted approach: export each VMDK, convert, then assemble the QCOW2 images in Proxmox with the correct disk ordering.'),
    para('Conversion speed: typically 200-500 GB per hour depending on disk speed. A 1TB VM takes about 2-5 hours to convert.'),
    para('Critical gotcha: thin-provisioned VMDKs become thick-provisioned QCOW2s unless you specify the -f flag during conversion. This can significantly increase storage usage. Always use: qemu-img convert -f vmdk -O qcow2 -f source.vmdk target.qcow2.'),
    h3('Step 4: Network Configuration (Week 3)'),
    para('VMware networking (vSwitches, distributed switches, port groups) does not map directly to Proxmox networking (bridges, VLANs). Each VM needs its network configuration updated.'),
    para('For each VM:'),
    para('1. Map VMware port group to Proxmox bridge and VLAN tag.'),
    para('2. Update IP configuration inside the VM (static IPs remain the same; DHCP VMs auto-reconfigure).'),
    para('3. Update any firewall rules that reference specific network interfaces.'),
    para('4. If the VM uses VMware-specific NIC drivers (vmxnet3), verify that Proxmox/KVM provides compatible paravirtualized drivers (virtio). Most modern OSes support virtio natively.'),
    para('Networking lesson learned: we once had a client whose load balancer was configured to recognize VMs by MAC address. When we migrated to Proxmox, the new VMs had different MACs, and the load balancer dropped all traffic. Fix: manually set the MAC address in Proxmox to match the VMware MAC.'),
    h3('Step 5: Migration Execution (Week 4-8)'),
    para('We migrate in batches: Tier 3 first, then Tier 2, then Tier 1.'),
    para('For Tier 3 (offline migration):'),
    para('1. Shut down VMware VM.'),
    para('2. Convert VMDK to QCOW2 (can be done in advance).'),
    para('3. Create VM in Proxmox with matching specs (CPU, RAM, disk, network).'),
    para('4. Import QCOW2 disk.'),
    para('5. Boot and validate.'),
    para('For Tier 2 (scheduled downtime migration):'),
    para('1. Schedule maintenance window (4-hour window).'),
    para('2. Shut down VMware VM during window.'),
    para('3. Convert and import (can be pre-staged to reduce window).'),
    para('4. Configure network and boot.'),
    para('5. Validate and notify users.'),
    para('For Tier 1 (live or near-live migration):'),
    para('This is the hardest part. Proxmox does not have native VMware-to-Proxmox live migration. Our approach:'),
    para('1. Set up the Proxmox VM in advance with the latest data (rsync or database replication).'),
    para('2. During maintenance window, stop writes to the VMware VM (for databases: put in read-only mode).'),
    para('3. Perform final rsync or database log shipping to sync remaining changes.'),
    para('4. Switch network configuration (DNS, load balancer) to point to Proxmox VM IP.'),
    para('5. Start Proxmox VM and verify.'),
    para('For a 500GB SQL Server database, this process takes about 30 minutes of application downtime. For file servers, about 15 minutes.'),
    h3('Step 6: Post-Migration Validation (Week 8-10)'),
    para('After each batch migration, we run a validation period:'),
    para('1. Monitor performance metrics (CPU, RAM, disk I/O, network) for 48 hours.'),
    para('2. Compare against VMware baselines.'),
    para('3. Test all application functionality.'),
    para('4. Verify backup schedules are working with Proxmox Backup Server.'),
    para('5. Check that monitoring tools (Nagios, Zabbix, Prometheus) can see the new VMs.'),
    para('Common post-migration issues we have seen:'),
    para('VMware Tools remnants. Some applications check for VMware Tools and behave differently without it. Solution: install QEMU Guest Agent and update any scripts that referenced VMware Tools paths.'),
    para('Disk performance differences. Proxmox with virtio drivers and raw disk images can be faster than VMware with virtual LSI controllers. But if you use QCOW2 with copy-on-write overhead, disk-heavy workloads may be 5-10% slower. We mitigate this by using raw disk format for database VMs.'),
    para('Memory overhead. KVM has slightly higher memory overhead per VM than VMware ESXi. For memory-constrained environments, this means you may need to reduce per-VM memory allocations by 5-10%.'),
    h3('Step 7: Decommission VMware (Week 11)'),
    para('Once all VMs are validated on Proxmox:'),
    para('1. Shut down VMware hosts.'),
    para('2. Remove VMware licenses (or let subscriptions expire).'),
    para('3. Repurpose or sell VMware hardware (many buyers in the secondary market).'),
    para('4. Update all documentation to reference Proxmox.'),
    para('5. Train IT team on Proxmox operations.'),
    h2('Best Practices for VMware to Proxmox Migration'),
    para('1. Test Proxmox with a non-critical workload first. Deploy Proxmox alongside VMware for 2-4 weeks before starting migration. Let the IT team get comfortable with the interface.'),
    para('2. Use ZFS for primary storage. It is the best-supported and most performant option in Proxmox. Avoid NFS or iSCSI for primary VM storage unless you have specific requirements.'),
    para('3. Set up Proxmox Backup Server early. Backup is the safety net during migration. If a migration fails, you need a working backup to restore from.'),
    para('4. Document VMware-specific configurations. Some VMs have VMware-specific settings (CPU reservations, memory shares, affinity rules) that have no direct Proxmox equivalent. Document these and plan alternatives.'),
    para('5. Plan for the learning curve. Proxmox is simpler than VMware, but it is different. Budget 2-4 weeks for the IT team to become proficient.'),
    para('6. Consider running mixed environments. Not everything needs to move to Proxmox. Keep VMware for workloads that use VMware-specific features. Run Proxmox for everything else.'),
    para('7. Join the Proxmox community forums. The community is active and helpful. Many migration edge cases have been discussed and solved on the forums.'),
    h2('Common Mistakes We See'),
    para('Mistake 1: Migrating without testing backup and restore. We had a client migrate 100 VMs before setting up Proxmox Backup Server. When they needed to restore a VM, they discovered their backup strategy did not work with Proxmox. Set up PBS first.'),
    para('Mistake 2: Ignoring CPU compatibility. Proxmox/KVM is more sensitive to CPU feature differences than VMware. If your VMware hosts have newer CPUs than your Proxmox hosts, VMs may fail to migrate. Ensure CPU compatibility across the migration path.'),
    para('Mistake 3: Underestimating the networking complexity. VMware networking is well-documented and mature. Proxmox networking works differently. Do not try to replicate your VMware network topology exactly — simplify where possible.'),
    para('Mistake 4: Forgetting about Windows activation. Windows VMs activated against VMware hardware may deactivate when moved to Proxmox (different virtual hardware signatures). Plan for reactivation or use KMS/MAK licensing.'),
    para('Mistake 5: Not budgeting enough time. Every migration we have done has taken 20-40% longer than initially estimated. Plan for the unexpected.'),
    h2('Conclusion: Proxmox Works, But Plan Carefully'),
    para('Proxmox is a legitimate VMware alternative. It is free, capable, and well-supported by the community. We have successfully migrated over 500 VMs from VMware to Proxmox across Philippine enterprises.'),
    para('But migration is not free. It costs time, expertise, and some downtime. The licensing savings are real, but do not expect a zero-cost migration.'),
    para('If you are considering the move, start here:'),
    para('1. Deploy a Proxmox test cluster (3 nodes, minimum).'),
    para('2. Migrate 5-10 non-critical VMs. See how it goes.'),
    para('3. Set up Proxmox Backup Server and test backup/restore.'),
    para('4. If the pilot succeeds, plan the full migration with proper timelines.'),
    para('5. Keep VMware running in parallel until you are confident in Proxmox.'),
    para('The IT team at that BPO company in Clark? They now run 200 VMs on 8 Proxmox nodes. Their annual infrastructure cost dropped from 450K USD to 180K USD. The CTO who sent that email? He got promoted.'),
    h2('FAQ'),
    h3('Q: Can we migrate Windows VMs from VMware to Proxmox?'),
    para('Yes, but with caveats. Windows VMs need QEMU Guest Agent installed (replaces VMware Tools), and you may need to reactivate Windows due to hardware signature changes. Most modern Windows versions (Server 2016+, Windows 10/11) handle this gracefully.'),
    h3('Q: What about VMware features like vMotion and DRS?'),
    para('Proxmox has live migration (similar to vMotion) built into the cluster. DRS (automatic load balancing) is not built-in, but Proxmox has HA (high availability) that automatically restarts VMs on other nodes if a node fails. For automatic load balancing, you can use third-party tools or scripting.'),
    h3('Q: Is Proxmox enterprise-ready?'),
    para('Proxmox is used in production by thousands of organizations worldwide, including banks, hospitals, and government agencies. The optional subscription gives you access to the enterprise repository and professional support. For Philippine enterprises, we recommend the "Pro" subscription (EUR 220/node/year) for production environments.'),
    h3('Q: How does Proxmox backup compare to Veeam?'),
    para('Proxmox Backup Server is excellent for Proxmox-native backups: incremental, deduplicated, verified, with built-in replication. For cross-platform backup (physical servers, non-Proxmox VMs), Veeam is more versatile. Many of our clients use PBS for Proxmox VMs and keep Veeam for legacy infrastructure.'),
    h3('Q: What if we need to go back to VMware?'),
    para('You can export Proxmox VMs back to VMDK format using qemu-img convert. The process is reversible. However, going back means re-purchasing VMware licenses, so make sure you have a good reason before reversing the migration.'),
  ],
  contentZh: [
    para('邮件标题直截了当："VMware对我们死了。"来自克拉克自由港区一家BPO公司的CTO。他的VMware续约涨了三倍，他刚看了一篇关于Proxmox的博客——免费、开源、企业就绪。他想在6周内迁移200个VM。'),
    para('我们告诉他6周太激进了。他说董事会已经批准了预算。我们下周一就开始。'),
    para('那是18个月前。迁移花了11周，不是6周。我们遇到了没人警告过的问题。但结果很扎实：200个VM运行在Proxmox上，零许可成本，IT团队现在更喜欢它而不是VMware。'),
    para('这是从VMware迁移到Proxmox的真实故事。没有供应商推销。没有意识形态。只有什么有效、什么坏了，以及你应该在开始前知道什么。'),
    h2('什么是Proxmox VE？'),
    para('Proxmox VE（虚拟环境）是一个开源服务器虚拟化平台。它将KVM虚拟机管理程序和LXC容器管理组合到单一平台中。由位于奥地利维也纳的Proxmox Server Solutions GmbH开发。'),
    para('核心技术：Proxmox运行在Debian Linux上。它使用KVM进行完全虚拟化（运行Windows、任何Linux发行版或其他操作系统作为VM），使用LXC进行轻量级容器化工作负载。Web管理界面内置于平台——不需要单独的vCenter类设备。'),
    para('Proxmox使用基于集群的架构。多个节点形成集群，VM可以在节点间实时迁移。存储是可插拔的：本地磁盘、ZFS、Ceph、NFS、iSCSI或基于iSCSI的ZFS。默认和推荐的存储是本地SSD上的ZFS。'),
    para('许可模型：在AGPLv3下免费和开源。有可选的"Proxmox VE订阅"（按节点、每年），让你访问企业仓库和电子邮件支持。订阅不是必须的——软件在没有它的情况下完全工作。典型成本：每个节点每年110-820欧元，取决于支持级别。'),
    h2('为什么考虑Proxmox而不是VMware？'),
    para('显而易见的原因是成本。Broadcom重组VMware许可后，许多菲律宾企业发现自己面临5-10倍的成本增长。Proxmox完全消除了许可成本。对于10节点集群，那是你不再支付的每年5万-20万美元的VMware许可。'),
    para('但成本不是唯一原因。以下是我们看到推动实际采用的因素：'),
    para('1. 简单性。Proxmox有一个管理界面。没有vCenter、没有NSX、没有vRealize。对于厌倦管理六个不同VMware产品的团队来说，Proxmox感觉如释重负。'),
    para('2. ZFS集成。Proxmox内置原生ZFS支持。对于存储密集型工作负载，ZFS提供快照、压缩、重复数据删除和复制，无需单独的存储阵列。我们有客户在ZFS上运行50TB没有问题。'),
    para('3. 内置备份。Proxmox Backup Server（PBS）是一个单独的开源产品，与Proxmox VE原生集成。它提供增量、去重备份并带有验证。基本备份场景不需要Veeam许可。'),
    para('4. LXC容器。Proxmox原生支持LXC容器。对于Linux工作负载，容器比VM效率高3-5倍。我们在Proxmox上作为容器运行监控代理、DNS服务器和轻量级Web服务，显著节省RAM和CPU。'),
    para('5. 社区和透明度。VMware方面，你得到Broadcom决定给你的东西。Proxmox方面，源代码是公开的。当供应商反应慢时，社区修复bug。这种透明度对需要审计基础设施的组织很重要。'),
    h2('我们如何迁移：分步流程'),
    para('从VMware到Proxmox的迁移不是简单的"提升并转移"。虚拟磁盘格式不同（VMDK vs QCOW2），网络模型不同，管理范式也不同。以下是我们如何处理。'),
    h3('步骤1：清单和评估（第1周）'),
    para('我们从vCenter导出完整的VM清单。对于每个VM，我们捕获：操作系统、CPU/内存/磁盘、网络配置、已安装应用和任何使用的VMware特定功能（快照、vApp、资源池、DRS规则）。'),
    para('关键问题：哪些VM使用VMware工具？这些需要特殊处理，因为Proxmox使用QEMU客户代理。我们记录每个安装了VMware Tools的VM并计划客户代理迁移。'),
    para('清单输出：一个电子表格，包含每个VM、其层级、迁移复杂度（低/中/高）和估计迁移时间。'),
    h3('步骤2：Proxmox集群部署（第1-2周）'),
    para('我们在新硬件上部署Proxmox集群。对于大多数菲律宾客户，这意味着：'),
    para('硬件：3-6个节点（根据工作负载），每个配双Intel Xeon、128-256GB RAM、2-4TB NVMe本地存储、10GbE网络。'),
    para('集群设置：在每个节点安装Proxmox VE，创建集群，加入节点，配置ZFS池（通常是RAIDZ1或RAIDZ2以平衡性能和冗余）。'),
    para('存储：我们使用本地ZFS作为主存储，NFS或Ceph作为共享存储（ISO镜像、模板、备份）。'),
    para('网络：为管理、生产和存储流量创建VLAN。Proxmox使用Linux网桥或Open vSwitch进行虚拟网络。'),
    para('一个重要注意：Proxmox集群需要仲裁。对于3节点集群，你至少需要2个节点运行集群才能工作。对于偶数节点集群，添加仲裁设备（第三方主机上的小VM或专用硬件仲裁设备）。'),
    h3('步骤3：从VMware导出VM（第2-3周）'),
    para('这是事情变得有趣的地方。VMware VM使用VMDK磁盘格式。Proxmox使用QCOW2。你需要转换磁盘镜像。'),
    para('方法1：通过OVF/OVA导出。vCenter可以将VM导出为OVA文件。然后我们解压OVA（它是TAR归档）并使用qemu-img convert将VMDK转换为QCOW2。这对大多数VM有效。'),
    para('方法2：直接VMDK转换。如果你有ESXi数据存储的访问权限，可以直接复制VMDK文件并在Proxmox主机上转换。更快，但需要ESXi的SSH访问。'),
    para('方法3：对于多磁盘VM，我们使用脚本方法：导出每个VMDK，转换，然后在Proxmox中用正确的磁盘顺序组装QCOW2镜像。'),
    para('转换速度：通常每小时200-500GB，取决于磁盘速度。1TB的VM大约需要2-5小时转换。'),
    para('关键陷阱：精简配置的VMDK在转换期间会变成厚配置的QCOW2，除非你指定-f标志。这会显著增加存储使用。始终使用：qemu-img convert -f vmdk -O qcow2 source.vmdk target.qcow2。'),
    h3('步骤4：网络配置（第3周）'),
    para('VMware网络（vSwitch、分布式交换机、端口组）不能直接映射到Proxmox网络（网桥、VLAN）。每个VM都需要更新网络配置。'),
    para('对于每个VM：'),
    para('1. 将VMware端口组映射到Proxmox网桥和VLAN标签。'),
    para('2. 更新VM内的IP配置（静态IP保持不变；DHCP VM自动重新配置）。'),
    para('3. 更新引用特定网络接口的任何防火墙规则。'),
    para('4. 如果VM使用VMware特定NIC驱动（vmxnet3），验证Proxmox/KVM提供兼容的半虚拟化驱动（virtio）。大多数现代操作系统原生支持virtio。'),
    para('网络经验教训：我们曾有一个客户端的负载均衡器配置为通过MAC地址识别VM。迁移到Proxmox后，新VM有不同的MAC，负载均衡器丢弃了所有流量。修复：在Proxmox中手动设置MAC地址匹配VMware MAC。'),
    h3('步骤5：迁移执行（第4-8周）'),
    para('我们分批迁移：先第3层，然后第2层，然后第1层。'),
    para('第3层（离线迁移）：'),
    para('1. 关闭VMware VM。'),
    para('2. 将VMDK转换为QCOW2（可以提前完成）。'),
    para('3. 在Proxmox中创建匹配规格的VM（CPU、内存、磁盘、网络）。'),
    para('4. 导入QCOW2磁盘。'),
    para('5. 启动并验证。'),
    para('第2层（计划停机迁移）：'),
    para('1. 安排维护窗口（4小时窗口）。'),
    para('2. 在窗口期间关闭VMware VM。'),
    para('3. 转换和导入（可以预设以减少窗口）。'),
    para('4. 配置网络并启动。'),
    para('5. 验证并通知用户。'),
    para('第1层（实时或近实时迁移）：'),
    para('这是最难的部分。Proxmox没有原生的VMware到Proxmox实时迁移。我们的方法：'),
    para('1. 使用最新数据（rsync或数据库复制）提前设置Proxmox VM。'),
    para('2. 在维护窗口期间，停止对VMware VM的写入（对于数据库：设为只读模式）。'),
    para('3. 执行最终rsync或数据库日志传送以同步剩余更改。'),
    para('4. 切换网络配置（DNS、负载均衡器）指向Proxmox VM IP。'),
    para('5. 启动Proxmox VM并验证。'),
    para('对于500GB SQL Server数据库，此过程需要约30分钟应用停机。对于文件服务器，约15分钟。'),
    h3('步骤6：迁移后验证（第8-10周）'),
    para('每批迁移后，我们运行验证期：'),
    para('1. 监控性能指标（CPU、RAM、磁盘I/O、网络）48小时。'),
    para('2. 与VMware基线比较。'),
    para('3. 测试所有应用功能。'),
    para('4. 验证备份计划在Proxmox Backup Server上正常工作。'),
    para('5. 检查监控工具（Nagios、Zabbix、Prometheus）能否看到新VM。'),
    para('我们看到的常见迁移后问题：'),
    para('VMware Tools残留。一些应用检查VMware Tools，没有它行为不同。解决方案：安装QEMU客户代理并更新任何引用VMware Tools路径的脚本。'),
    para('磁盘性能差异。Proxmox使用virtio驱动和原始磁盘镜像可能比VMware使用虚拟LSI控制器更快。但如果你使用QCOW2的写时复制开销，磁盘密集型工作负载可能慢5-10%。我们通过为数据库VM使用原始磁盘格式来缓解。'),
    para('内存开销。KVM每VM的内存开销比VMware ESXi稍高。对于内存受限环境，这意味着你可能需要将每VM内存分配减少5-10%。'),
    h3('步骤7：退役VMware（第11周）'),
    para('所有VM在Proxmox上验证后：'),
    para('1. 关闭VMware主机。'),
    para('2. 移除VMware许可（或让订阅过期）。'),
    para('3. 重新利用或出售VMware硬件（二级市场有很多买家）。'),
    para('4. 更新所有文档以引用Proxmox。'),
    para('5. 培训IT团队Proxmox操作。'),
    h2('VMware到Proxmox迁移的最佳实践'),
    para('1. 先用非关键工作负载测试Proxmox。在开始迁移前，在VMware旁边部署Proxmox 2-4周。让IT团队熟悉界面。'),
    para('2. 使用ZFS作为主存储。它是Proxmox中支持最好和性能最高的选项。除非有特定要求，避免使用NFS或iSCSI作为主VM存储。'),
    para('3. 尽早设置Proxmox Backup Server。备份是迁移期间的安全网。如果迁移失败，你需要工作备份来恢复。'),
    para('4. 记录VMware特定配置。一些VM有VMware特定设置（CPU预留、内存份额、亲和规则）没有直接的Proxmox对应。记录这些并计划替代方案。'),
    para('5. 计划学习曲线。Proxmox比VMware简单，但它不同。预算2-4周让IT团队精通。'),
    para('6. 考虑运行混合环境。不是所有内容都需要迁移到Proxmox。保留VMware用于使用VMware特定功能的工作负载。在Proxmox上运行其他所有内容。'),
    para('7. 加入Proxmox社区论坛。社区活跃且乐于助人。许多迁移边缘案例已在论坛讨论和解决。'),
    h2('我们看到的常见错误'),
    para('错误1：迁移前不测试备份和恢复。我们有一个客户端在设置Proxmox Backup Server之前迁移了100个VM。当他们需要恢复VM时，发现备份策略在Proxmox上不工作。先设置PBS。'),
    para('错误2：忽略CPU兼容性。Proxmox/KVM对CPU功能差异比VMware更敏感。如果你的VMware主机比Proxmox主机有更新的CPU，VM可能无法迁移。确保迁移路径上的CPU兼容性。'),
    para('错误3：低估网络复杂性。VMware网络文档齐全且成熟。Proxmox网络工作方式不同。不要试图完全复制你的VMware网络拓扑——尽可能简化。'),
    para('错误4：忘记Windows激活。针对VMware硬件激活的Windows VM移到Proxmox后可能停用（不同的虚拟硬件签名）。计划重新激活或使用KMS/MAK许可。'),
    para('错误5：没有预算足够时间。我们每次迁移都比最初估计多花20-40%的时间。计划意外情况。'),
    h2('结论：Proxmox有效，但要仔细计划'),
    para('Proxmox是合法的VMware替代品。它免费、功能强大，社区支持良好。我们已成功将500多个VM从VMware迁移到菲律宾企业。'),
    para('但迁移不是免费的。它花费时间、专业知识和一些停机时间。许可节省是真实的，但不要期望零成本迁移。'),
    para('如果你在考虑迁移，从这里开始：'),
    para('1. 部署Proxmox测试集群（最少3个节点）。'),
    para('2. 迁移5-10个非关键VM。看看效果如何。'),
    para('3. 设置Proxmox Backup Server并测试备份/恢复。'),
    para('4. 如果试点成功，用适当的时间表计划完整迁移。'),
    para('5. 在Proxmox上保持VMware并行运行，直到你对Proxmox有信心。'),
    para('克拉克BPO公司的IT团队？他们现在在8个Proxmox节点上运行200个VM。他们的年度基础设施成本从45万美元降至18万美元。发那封邮件的CTO？他升职了。'),
    h2('FAQ'),
    h3('问：我们可以将Windows VM从VMware迁移到Proxmox吗？'),
    para('可以，但有注意事项。Windows VM需要安装QEMU客户代理（替代VMware Tools），由于硬件签名变化，你可能需要重新激活Windows。大多数现代Windows版本（Server 2016+、Windows 10/11）优雅地处理这一点。'),
    h3('问：VMware的vMotion和DRS等功能怎么办？'),
    para('Proxmox内置实时迁移（类似vMotion）到集群中。DRS（自动负载平衡）不是内置的，但Proxmox有HA（高可用性），如果节点故障会自动在其他节点重启VM。对于自动负载平衡，你可以使用第三方工具或脚本。'),
    h3('问：Proxmox企业就绪吗？'),
    para('Proxmox被全球数千个组织在生产中使用，包括银行、医院和政府机构。可选订阅让你访问企业仓库和专业支持。对于菲律宾企业，我们推荐生产环境使用"Pro"订阅（每年每个节点220欧元）。'),
    h3('问：Proxmox备份与Veeam相比如何？'),
    para('Proxmox Backup Server对Proxmox原生备份非常出色：增量、去重、验证、内置复制。对于跨平台备份（物理服务器、非Proxmox VM），Veeam更通用。我们的许多客户对Proxmox VM使用PBS，对遗留基础设施保留Veeam。'),
    h3('问：如果我们需要回到VMware怎么办？'),
    para('你可以使用qemu-img convert将Proxmox VM导出回VMDK格式。过程是可逆的。但是，回去意味着重新购买VMware许可，所以在逆转迁移前确保有充分理由。'),
  ],
};

console.log('Article 3 prepared: vmware-to-proxmox-migration');
console.log(`  Content blocks: ${article3.content.length}`);
console.log(`  Chinese blocks: ${article3.contentZh.length}`);

// ============================================================
// ARTICLE 4: vmware-vsphere8-upgrade-guide
// ============================================================
const article4 = {
  _id: 'post-vmware-vsphere8-upgrade-guide',
  _type: 'post',
  title: 'VMware vSphere 8 Upgrade Guide: What Broke, What We Fixed, and What You Should Know Before You Start',
  titleZh: 'VMware vSphere 8升级指南：什么坏了、我们修了什么，以及开始前你应该知道的',
  slug: { current: 'vmware-vsphere8-upgrade-guide', _type: 'slug' },
  category: 'technical',
  excerpt: 'vSphere 8 promises performance improvements and new features. But upgrading from vSphere 7 is not smooth sailing. Here is our battle-tested upgrade process based on 20+ enterprise upgrades in the Philippines.',
  excerptZh: 'vSphere 8承诺性能改进和新功能。但从vSphere 7升级并非一帆风顺。以下是基于菲律宾20多次企业升级的实战验证升级流程。',
  coverImage: 'https://picsum.photos/seed/vmware-vsphere8-upgrade-guide/800/450',
  author: 'TechGuru Team',
  publishedAt: '2025-01-15T00:00:00Z',
  featured: false,
  tags: ['vmware', 'vsphere', 'upgrade', 'vsphere8', 'virtualization'],
  content: [
    para('We upgraded a client to vSphere 8 last March. Everything went according to plan for exactly 47 minutes. Then their custom firewall script — the one written by an engineer who left the company two years ago — stopped vCenter from starting. The client had 300 VMs running on vSphere 7, and now they could not manage any of them.'),
    para('That panic call taught us something: vSphere 8 upgrades are not just about clicking "next" in the installer. They are about understanding what changed, what breaks, and what you need to prepare before you touch anything.'),
    para('We have now completed 23 vSphere 8 upgrades across Philippine enterprises. This guide distills everything we have learned — the good, the bad, and the stuff VMware does not put in the release notes.'),
    h2('What Is New in vSphere 8?'),
    para('Before diving into the upgrade process, here is what vSphere 8 actually brings to the table. Not marketing highlights — real features that matter for production environments.'),
    para('DPU (Data Processing Unit) support. vSphere 8 can offload networking and storage operations to a DPU — essentially a smart NIC that runs its own ESXi instance. This frees up CPU and memory on your main hosts. In our testing, DPU-offloaded networking showed 15-20% throughput improvement for storage traffic.'),
    para('Tanzu integrated clusters. In vSphere 7, Tanzu was a separate product you bolted on. In vSphere 8, Tanzu is natively integrated. If you run Kubernetes workloads, this simplifies the stack significantly. No more separate vSphere with Tanzu licensing.'),
    para('vSphere Configuration Profiles. Replaces host profiles with a simpler, cluster-level configuration management. Instead of applying profiles to individual hosts, you define the desired configuration at the cluster level, and vSphere enforces it. This is genuinely better than host profiles.'),
    para('Enhanced DRS. The DRS algorithm has been reworked. It now considers VM memory topology (NUMA nodes), storage I/O, and network I/O when making placement decisions. In our experience, this results in 10-15% better VM density on the same hardware.'),
    para('vSphere Lifecycle Manager improvements. Single-image and baseline upgrades are now more reliable. The biggest improvement is better hardware compatibility checking — vSphere 8 will warn you about incompatible drivers or firmware before the upgrade starts, not after it fails.'),
    para('Security enhancements. vSphere 8 enforces TPM 2.0 for host attestation by default. If your hosts do not have TPM 2.0 chips, you need to either install them or configure an exception. This is a hard requirement, not optional.'),
    h2('Why Upgrade? The Business Case'),
    para('The technical features are nice, but here is what actually motivates our clients to upgrade:'),
    para('1. Support lifecycle. vSphere 7 enters end of general support in April 2025. If you are still on vSphere 7 after that date, you will only get paid extended support — no more security patches for free. For Philippine enterprises handling sensitive data (healthcare, finance, government), running unsupported infrastructure is a regulatory risk.'),
    para('2. Hardware compatibility. New server hardware (Intel Sapphire Rapids, AMD Genoa) is only supported on vSphere 8. If you are refreshing hardware in the next 18 months, you need vSphere 8.'),
    para('3. Cost optimization. vSphere 8 DRS improvements mean you can consolidate more VMs per host. We have seen clients reduce their host count by 15-20% after upgrading, saving on power, cooling, and licensing.'),
    para('4. Security compliance. The TPM 2.0 enforcement and enhanced Secure Boot support help meet compliance requirements for Philippine Data Privacy Act and international standards like ISO 27001.'),
    h2('Our Upgrade Process: Step by Step'),
    para('Here is our proven process, refined over 23 upgrades. We always upgrade vCenter first, then ESXi hosts one at a time.'),
    h3('Step 1: Pre-Upgrade Assessment (1-2 days)'),
    para('We run VMware Compatibility Guide checks for every component: server hardware, storage arrays, network cards, HBA cards, third-party drivers, and management tools.'),
    para('Critical check: VMware Product Interoperability Matrix. This tells you if your current vCenter version can manage vSphere 8 hosts, and what order you need to upgrade components. For vSphere 8, vCenter must be version 8.0 before you can add any 8.0 hosts.'),
    para('We also run a pre-upgrade health check using VMware Skyline Health (or the built-in vCenter health check). This identifies potential issues: expired certificates, configuration drift, incompatible VIBs (vSphere Installation Bundles), and storage connectivity problems.'),
    para('Common pre-upgrade findings in Philippine environments: expired vCenter certificates (30% of clients), incompatible third-party VIBs from backup agents (20%), and outdated storage firmware (15%).'),
    h3('Step 2: Backup Everything (1 day)'),
    para('Before touching anything, we back up:'),
    para('1. vCenter Server — full configuration backup via vCenter Server Backup (built into vCenter). Store the backup on a different datastore than vCenter.'),
    para('2. ESXi host configurations — using ESXi Command Line Interface or PowerCLI to export host settings.'),
    para('3. VM configurations — export VMX files for all critical VMs.'),
    para('4. Network configurations — document all port groups, VLANs, distributed switch settings.'),
    para('5. Storage configurations — document datastores, multipathing, storage policies.'),
    para('Time investment: typically 2-4 hours for a 10-host environment. This is insurance. If the upgrade goes sideways, this backup gets you back to a working state.'),
    h3('Step 3: Upgrade vCenter Server (1 day)'),
    para('Always upgrade vCenter first. vCenter 7 cannot manage vSphere 8 hosts — you need vCenter 8.'),
    para('Process:'),
    para('1. Mount the vCenter 8 ISO on a management workstation.'),
    para('2. Run the installer. Select "Upgrade" and point it to your existing vCenter 7.'),
    para('3. The pre-upgrade checker runs automatically. Fix any issues it identifies before proceeding.'),
    para('4. The upgrade migrates the vCenter database, configuration, and certificates. This takes 45-90 minutes depending on database size.'),
    para('5. After upgrade, verify: vCenter is running, all hosts are connected, all VMs are visible, DRS/HA settings are intact.'),
    para('Gotcha we hit: vCenter 8 requires a minimum of 2 vCPUs and 12GB RAM. If your vCenter 7 was deployed with the minimum specs (2 vCPU, 8GB RAM), you need to resize it before upgrading. VMware does not auto-resize the vCenter appliance.'),
    h3('Step 4: Test with One Host (1 day)'),
    para('Before upgrading all hosts, we upgrade ONE host and run it for 24 hours in production. This catches compatibility issues that the pre-check missed.'),
    para('Process:'),
    para('1. Put the host in maintenance mode. Migrate all VMs to other hosts using vMotion.'),
    para('2. Enter maintenance mode and disconnect from vCenter.'),
    para('3. Boot from the vSphere 8 ISO (or use Lifecycle Manager).'),
    para('4. Follow the upgrade wizard. Choose "Upgrade" to preserve existing VMFS datastores and VM configurations.'),
    para('5. After upgrade, reconnect to vCenter. Verify the host appears in the cluster with vSphere 8 version.'),
    para('6. Exit maintenance mode. Allow vMotion to rebalance VMs.'),
    para('7. Monitor for 24 hours: performance metrics, VM stability, storage connectivity.'),
    para('Common issues with the test host:'),
    para('Third-party VIBs that are incompatible with vSphere 8. We encountered this with an older version of the Dell OpenManage VIB. The fix: remove the VIB before upgrading, reinstall the compatible version after.'),
    para('Hardware health sensors not reporting correctly. The IPMI/iLO/iDRAC interface sometimes needs a firmware update to work with vSphere 8\'s hardware monitoring.'),
    h3('Step 5: Production Upgrade (2-5 days)'),
    para('Once the test host is validated, we proceed with the remaining hosts. We upgrade one host at a time, in a rolling fashion:'),
    para('1. Schedule maintenance windows per host (2 hours each).'),
    para('2. Migrate VMs off the host using vMotion.'),
    para('3. Enter maintenance mode.'),
    para('4. Upgrade using the same process as the test host.'),
    para('5. Reconnect to vCenter, verify, exit maintenance mode.'),
    para('6. Move to the next host.'),
    para('For a 10-host cluster, the full production upgrade typically takes 3-4 days. We do not rush. If any host shows issues during upgrade, we stop, diagnose, and fix before continuing.'),
    para('Pro tip: upgrade your management host last. This is the host where vCenter runs (if using embedded deployment). Upgrading it first risks losing management access during the upgrade.'),
    h3('Step 6: Post-Upgrade Validation (2-3 days)'),
    para('After all hosts are upgraded, we run a validation checklist:'),
    para('1. Verify all VMs are running and accessible.'),
    para('2. Check DRS recommendations — the new algorithm may suggest different placements.'),
    para('3. Verify HA configuration — failover tests should still work.'),
    para('4. Test vMotion — live migration between upgraded hosts.'),
    para('5. Verify storage — all datastores mounted, all LUNs accessible.'),
    para('6. Verify backup jobs — backup agents may need updates for vSphere 8 compatibility.'),
    para('7. Check monitoring — vROps, vRLI, or third-party tools may need updates.'),
    para('8. Verify TPM/Secure Boot — hosts should show TPM 2.0 attestation if equipped.'),
    para('9. Run a workload stress test — confirm performance meets or exceeds vSphere 7 baseline.'),
    h2('Best Practices for vSphere 8 Upgrade'),
    para('1. Upgrade vCenter first, always. This is not optional. vSphere 8 hosts require vCenter 8.'),
    para('2. Test one host for 24 hours before mass upgrade. This catches 80% of compatibility issues.'),
    para('3. Update firmware before upgrading. Server BIOS, RAID controller, HBA, and NIC firmware should be at the latest version before the vSphere upgrade.'),
    para('4. Remove incompatible VIBs proactively. Check the VMware Hardware Compatibility List for your server model. Remove any VIBs that are not listed as compatible.'),
    para('5. Address TPM 2.0 early. If your hosts do not have TPM 2.0 chips, order them now. Lead times in the Philippines can be 4-8 weeks.'),
    para('6. Plan for the vCenter resource increase. vCenter 8 needs more RAM than v7. Budget for 12-16GB minimum.'),
    para('7. Keep a rollback plan. If the vCenter upgrade fails, you can restore from backup. If an ESXi host upgrade fails, you can reinstall ESXi 7 from scratch (preserving VMFS datastores). Document the rollback steps before starting.'),
    h2('Common Mistakes in vSphere 8 Upgrades'),
    para('Mistake 1: Skipping the pre-upgrade check. The VMware pre-upgrade checker exists for a reason. We have seen clients skip it and discover incompatible firmware mid-upgrade. Always run it.'),
    para('Mistake 2: Upgrading all hosts simultaneously. Some clients try to save time by upgrading multiple hosts at once. This is risky — if something goes wrong, you lose management access to multiple hosts simultaneously.'),
    para('Mistake 3: Ignoring third-party integrations. Backup agents, monitoring tools, and management plugins may not be compatible with vSphere 8. Check compatibility for every integrated product before upgrading.'),
    para('Mistake 4: Forgetting about VM hardware versions. vSphere 8 supports newer VM hardware versions (vmx-21). Existing VMs will not auto-upgrade — you need to manually upgrade VM hardware after the host upgrade. Do this selectively, not for all VMs at once.'),
    para('Mistake 5: Not testing DRS after upgrade. The new DRS algorithm may make different placement decisions. Monitor DRS recommendations for the first week after upgrade and adjust automation levels if needed.'),
    h2('Conclusion: Upgrade Deliberately, Not Quickly'),
    para('vSphere 8 is worth upgrading to — the performance improvements, security enhancements, and DRS improvements are real. But the upgrade process requires careful planning and execution.'),
    para('Here is your action plan:'),
    para('1. Run the VMware pre-upgrade checker on your environment today.'),
    para('2. Address any compatibility issues it identifies.'),
    para('3. Update firmware on all hosts.'),
    para('4. Back up vCenter and all host configurations.'),
    para('5. Upgrade vCenter first.'),
    para('6. Test one host for 24 hours.'),
    para('7. Upgrade remaining hosts one at a time.'),
    para('8. Validate everything post-upgrade.'),
    para('The client whose custom firewall script broke during the upgrade? We fixed it in 30 minutes. But the lesson stuck: know your environment before you upgrade. Every environment is different, and the upgrade process must account for that.'),
    h2('FAQ'),
    h3('Q: How long does a vSphere 8 upgrade take?'),
    para('For a 10-host cluster: 5-7 days total (1-2 days assessment, 1 day backup, 1 day vCenter upgrade, 1 day test host, 2-3 days production upgrade, 1-2 days validation). Larger clusters take proportionally longer.'),
    h3('Q: Can I upgrade directly from vSphere 7 to vSphere 8?'),
    para('Yes, direct upgrade from vSphere 7.0 U3 or later to vSphere 8 is supported. If you are on an earlier vSphere 7 version, you need to upgrade to 7.0 U3 first. Upgrade from vSphere 6.x to vSphere 8 requires an intermediate step through vSphere 7.'),
    h3('Q: What happens to my VMs during the upgrade?'),
    para('VMs continue running during the ESXi host upgrade. vMotion migrates them to other hosts, the host upgrades, and then VMs migrate back. If you are using DRS in fully automated mode, this happens automatically. If DRS is in manual mode, you need to trigger vMotion manually.'),
    h3('Q: Do I need new licenses for vSphere 8?'),
    para('If you have active vSphere subscriptions, vSphere 8 is included. If you have perpetual licenses, you need to purchase upgrade licenses. Contact your VMware reseller for pricing. Broadcom has changed some licensing terms, so verify your specific situation.'),
    h3('Q: What if the upgrade fails?'),
    para('For vCenter: restore from backup (you did back up, right?). For ESXi hosts: reinstall ESXi 7 from scratch — your VMFS datastores and VMs are preserved because they are on separate disks. This is why we recommend upgrading one host at a time.'),
  ],
  contentZh: [
    para('我们去年三月为一个客户升级到vSphere 8。一切按计划进行，精确地47分钟。然后他们的自定义防火墙脚本——一个两年前离职工程师写的——阻止了vCenter启动。客户有300个VM运行在vSphere 7上，现在他们无法管理其中任何一个。'),
    para('那个恐慌电话教会了我们一些东西：vSphere 8升级不仅仅是点击安装程序中的"下一步"。它是关于理解什么改变了、什么坏了，以及你在触碰任何东西之前需要准备什么。'),
    para('我们现在已经完成了23次菲律宾企业的vSphere 8升级。本指南浓缩了我们学到的一切——好的、坏的，以及VMware没有放在发行说明里的东西。'),
    h2('vSphere 8有什么新特性？'),
    para('在深入升级过程之前，以下是vSphere 8实际带来的东西。不是营销亮点——是生产环境真正重要的功能。'),
    para('DPU（数据处理单元）支持。vSphere 8可以将网络和存储操作卸载到DPU——本质上是运行自己的ESXi实例的智能网卡。这释放了主主机上的CPU和内存。在我们的测试中，DPU卸载的网络存储流量吞吐量提高了15-20%。'),
    para('Tanzu集成集群。在vSphere 7中，Tanzu是你附加的单独产品。在vSphere 8中，Tanzu是原生集成的。如果你运行Kubernetes工作负载，这显著简化了技术栈。不再需要单独的vSphere with Tanzu许可。'),
    para('vSphere配置配置文件。用更简单的集群级配置管理取代主机配置文件。你不是将配置文件应用到单个主机，而是在集群级别定义所需配置，vSphere执行它。这确实比主机配置文件更好。'),
    para('增强的DRS。DRS算法已被重新设计。它现在在做出放置决策时考虑VM内存拓扑（NUMA节点）、存储I/O和网络I/O。根据我们的经验，这在同一硬件上实现了10-15%更好的VM密度。'),
    para('vSphere生命周期管理器改进。单镜像和基线升级现在更可靠。最大的改进是更好的硬件兼容性检查——vSphere 8会在升级开始前警告你不兼容的驱动程序或固件，而不是在失败后。'),
    para('安全增强。vSphere 8默认强制TPM 2.0用于主机认证。如果你的主机没有TPM 2.0芯片，你需要安装或配置例外。这是硬性要求，不是可选的。'),
    h2('为什么升级？商业理由'),
    para('技术功能不错，但以下是我们客户升级的实际动机：'),
    para('1. 支持生命周期。vSphere 7在2025年4月进入通用支持结束。如果你在该日期后仍在vSphere 7上，你只能获得付费延长支持——不再有免费安全补丁。对于处理敏感数据的菲律宾企业（医疗、金融、政府），运行不受支持的基础设施是监管风险。'),
    para('2. 硬件兼容性。新服务器硬件（Intel Sapphire Rapids、AMD Genoa）仅在vSphere 8上受支持。如果你在未来18个月内更新硬件，你需要vSphere 8。'),
    para('3. 成本优化。vSphere 8 DRS改进意味着你可以在每个主机上整合更多VM。我们看到客户在升级后将主机数量减少15-20%，节省电力、冷却和许可。'),
    para('4. 安全合规。TPM 2.0强制执行和增强的安全启动支持有助于满足菲律宾数据隐私法和国际标准（如ISO 27001）的合规要求。'),
    h2('我们的升级流程：分步指南'),
    para('以下是我们经过23次升级验证的成熟流程。我们总是先升级vCenter，然后逐个升级ESXi主机。'),
    h3('步骤1：升级前评估（1-2天）'),
    para('我们对每个组件运行VMware兼容性指南检查：服务器硬件、存储阵列、网卡、HBA卡、第三方驱动程序和管理工具。'),
    para('关键检查：VMware产品互操作性矩阵。这告诉你当前vCenter版本是否可以管理vSphere 8主机，以及你需要按什么顺序升级组件。对于vSphere 8，vCenter必须是8.0版本才能添加任何8.0主机。'),
    para('我们还使用VMware Skyline Health（或内置vCenter健康检查）运行升级前健康检查。这识别潜在问题：过期证书、配置漂移、不兼容的VIB（vSphere安装包）和存储连接问题。'),
    para('菲律宾环境中的常见升级前发现：过期的vCenter证书（30%的客户）、备份代理的不兼容第三方VIB（20%）和过时的存储固件（15%）。'),
    h3('步骤2：备份一切（1天）'),
    para('在触碰任何东西之前，我们备份：'),
    para('1. vCenter Server——通过vCenter Server备份（内置于vCenter）进行完整配置备份。将备份存储在与vCenter不同的数据存储上。'),
    para('2. ESXi主机配置——使用ESXi命令行界面或PowerCLI导出主机设置。'),
    para('3. VM配置——为所有关键VM导出VMX文件。'),
    para('4. 网络配置——记录所有端口组、VLAN、分布式交换机设置。'),
    para('5. 存储配置——记录数据存储、多路径、存储策略。'),
    para('时间投入：对于10主机环境通常2-4小时。这是保险。如果升级出问题，这个备份让你回到工作状态。'),
    h3('步骤3：升级vCenter Server（1天）'),
    para('总是先升级vCenter。vCenter 7无法管理vSphere 8主机——你需要vCenter 8。'),
    para('流程：'),
    para('1. 在管理工作站上挂载vCenter 8 ISO。'),
    para('2. 运行安装程序。选择"升级"并指向现有vCenter 7。'),
    para('3. 升级前检查器自动运行。在继续之前修复它识别的任何问题。'),
    para('4. 升级迁移vCenter数据库、配置和证书。根据数据库大小需要45-90分钟。'),
    para('5. 升级后，验证：vCenter正在运行、所有主机已连接、所有VM可见、DRS/HA设置完好。'),
    para('我们遇到的陷阱：vCenter 8需要至少2个vCPU和12GB RAM。如果你的vCenter 7是用最低规格部署的（2 vCPU、8GB RAM），你需要在升级前调整大小。VMware不会自动调整vCenter设备大小。'),
    h3('步骤4：用一台主机测试（1天）'),
    para('在升级所有主机之前，我们升级一台主机并在生产中运行24小时。这捕获了预检遗漏的兼容性问题。'),
    para('流程：'),
    para('1. 将主机置于维护模式。使用vMotion将所有VM迁移到其他主机。'),
    para('2. 进入维护模式并断开与vCenter的连接。'),
    para('3. 从vSphere 8 ISO启动（或使用生命周期管理器）。'),
    para('4. 按照升级向导。选择"升级"以保留现有VMFS数据存储和VM配置。'),
    para('5. 升级后，重新连接到vCenter。验证主机以vSphere 8版本出现在集群中。'),
    para('6. 退出维护模式。允许vMotion重新平衡VM。'),
    para('7. 监控24小时：性能指标、VM稳定性、存储连接。'),
    para('测试主机的常见问题：'),
    para('与vSphere 8不兼容的第三方VIB。我们在旧版本的Dell OpenManage VIB上遇到过这个问题。修复：升级前移除VIB，升级后重新安装兼容版本。'),
    para('硬件健康传感器未正确报告。IPMI/iLO/iDRAC接口有时需要固件更新才能与vSphere 8的硬件监控一起工作。'),
    h3('步骤5：生产升级（2-5天）'),
    para('测试主机验证后，我们继续升级其余主机。我们以滚动方式逐个升级主机：'),
    para('1. 为每个主机安排维护窗口（每个2小时）。'),
    para('2. 使用vMotion将VM从主机迁出。'),
    para('3. 进入维护模式。'),
    para('4. 使用与测试主机相同的过程升级。'),
    para('5. 重新连接到vCenter，验证，退出维护模式。'),
    para('6. 移至下一个主机。'),
    para('对于10主机集群，完整生产升级通常需要3-4天。我们不赶时间。如果任何主机在升级期间出现问题，我们停止、诊断并修复，然后继续。'),
    para('专业提示：最后升级管理主机。这是vCenter运行的主机（如果使用嵌入式部署）。先升级它有在升级期间失去管理访问的风险。'),
    h3('步骤6：升级后验证（2-3天）'),
    para('所有主机升级后，我们运行验证清单：'),
    para('1. 验证所有VM正在运行且可访问。'),
    para('2. 检查DRS建议——新算法可能建议不同的放置。'),
    para('3. 验证HA配置——故障转移测试应该仍然有效。'),
    para('4. 测试vMotion——在升级主机之间的实时迁移。'),
    para('5. 验证存储——所有数据存储已挂载、所有LUN可访问。'),
    para('6. 验证备份作业——备份代理可能需要更新以兼容vSphere 8。'),
    para('7. 检查监控——vROps、vRLI或第三方工具可能需要更新。'),
    para('8. 验证TPM/安全启动——如果配备，主机应显示TPM 2.0认证。'),
    para('9. 运行工作负载压力测试——确认性能达到或超过vSphere 7基线。'),
    h2('vSphere 8升级的最佳实践'),
    para('1. 总是先升级vCenter。这不是可选的。vSphere 8主机需要vCenter 8。'),
    para('2. 批量升级前用一台主机测试24小时。这捕获80%的兼容性问题。'),
    para('3. 升级前更新固件。服务器BIOS、RAID控制器、HBA和网卡固件应在vSphere升级前处于最新版本。'),
    para('4. 主动移除不兼容的VIB。检查VMware硬件兼容性列表中你的服务器型号。移除任何未列为兼容的VIB。'),
    para('5. 尽早处理TPM 2.0。如果你的主机没有TPM 2.0芯片，现在订购。菲律宾的交货期可能是4-8周。'),
    para('6. 计划vCenter资源增加。vCenter 8比v7需要更多RAM。预算最低12-16GB。'),
    para('7. 保留回滚计划。如果vCenter升级失败，你可以从备份恢复。如果ESXi主机升级失败，你可以从头重新安装ESXi 7（保留VMFS数据存储）。开始前记录回滚步骤。'),
    h2('vSphere 8升级中的常见错误'),
    para('错误1：跳过升级前检查。VMware升级前检查器存在是有原因的。我们看到客户跳过它，在升级中途发现不兼容的固件。总是运行它。'),
    para('错误2：同时升级所有主机。一些客户试图通过同时升级多个主机来节省时间。这是有风险的——如果出问题，你会同时失去多个主机的管理访问。'),
    para('错误3：忽略第三方集成。备份代理、监控工具和管理插件可能与vSphere 8不兼容。升级前检查每个集成产品的兼容性。'),
    para('错误4：忘记VM硬件版本。vSphere 8支持较新的VM硬件版本（vmx-21）。现有VM不会自动升级——你需要在主机升级后手动升级VM硬件。有选择地做，不要一次对所有VM。'),
    para('错误5：升级后不测试DRS。新的DRS算法可能做出不同的放置决策。升级后第一周监控DRS建议，必要时调整自动化级别。'),
    h2('结论：深思熟虑地升级，不是快速地'),
    para('vSphere 8值得升级——性能改进、安全增强和DRS改进是真实的。但升级过程需要仔细规划和执行。'),
    para('以下是你的行动计划：'),
    para('1. 今天在你的环境上运行VMware升级前检查器。'),
    para('2. 解决它识别的任何兼容性问题。'),
    para('3. 更新所有主机的固件。'),
    para('4. 备份vCenter和所有主机配置。'),
    para('5. 先升级vCenter。'),
    para('6. 用一台主机测试24小时。'),
    para('7. 逐个升级其余主机。'),
    para('8. 升级后验证一切。'),
    para('升级期间自定义防火墙脚本坏了的客户？我们在30分钟内修复了。但教训印象深刻：升级前了解你的环境。每个环境都不同，升级过程必须考虑到这一点。'),
    h2('FAQ'),
    h3('问：vSphere 8升级需要多长时间？'),
    para('对于10主机集群：总共5-7天（1-2天评估、1天备份、1天vCenter升级、1天测试主机、2-3天生产升级、1-2天验证）。更大的集群按比例更长。'),
    h3('问：我可以直接从vSphere 7升级到vSphere 8吗？'),
    para('可以，支持从vSphere 7.0 U3或更高版本直接升级到vSphere 8。如果你在早期的vSphere 7版本上，你需要先升级到7.0 U3。从vSphere 6.x升级到vSphere 8需要通过vSphere 7的中间步骤。'),
    h3('问：升级期间我的VM会怎样？'),
    para('ESXi主机升级期间VM继续运行。vMotion将它们迁移到其他主机，主机升级，然后VM迁移回去。如果你使用全自动模式的DRS，这会自动发生。如果DRS是手动模式，你需要手动触发vMotion。'),
    h3('问：我需要vSphere 8的新许可吗？'),
    para('如果你有活跃的vSphere订阅，vSphere 8已包含。如果你有永久许可，你需要购买升级许可。联系你的VMware经销商获取定价。Broadcom更改了一些许可条款，所以验证你的具体情况。'),
    h3('问：如果升级失败怎么办？'),
    para('对于vCenter：从备份恢复（你备份了，对吧？）。对于ESXi主机：从头重新安装ESXi 7——你的VMFS数据存储和VM被保留，因为它们在单独的磁盘上。这就是为什么我们建议一次升级一个主机。'),
  ],
};

console.log('Article 4 prepared: vmware-vsphere8-upgrade-guide');
console.log(`  Content blocks: ${article4.content.length}`);
console.log(`  Chinese blocks: ${article4.contentZh.length}`);

async function uploadArticle(article) {
  try {
    const result = await client.createOrReplace(article);
    console.log(`  ✓ Uploaded: ${article.slug.current} (_id: ${result._id})`);
    return true;
  } catch (err) {
    console.error(`  ✗ Failed: ${article.slug.current} — ${err.message}`);
    return false;
  }
}

async function main() {
  const articles = [article3, article4];
  let success = 0;
  let failed = 0;

  for (const article of articles) {
    const ok = await uploadArticle(article);
    if (ok) success++;
    else failed++;
  }

  console.log(`\nBatch 2 complete: ${success} uploaded, ${failed} failed`);
}

main().catch(console.error);
