const SANITY_TOKEN = 'REPLACED_SANITY_TOKEN';
const PROJECT_ID = 'r6ztl1oq';
const DATASET = 'production';
const API_VERSION = '2024-01-01';
const URL = `https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/mutate/${DATASET}?returnIds=true`;

function makeBlock(text) {
  return text.split('\n\n').filter(p => p.trim()).map(p => ({
    _type: 'block', children: [{ _type: 'span', text: p.trim() }], style: 'normal'
  }));
}
function makeHeading(text, level) {
  return { _type: 'block', style: level, children: [{ _type: 'span', text: text }] };
}
function makeListItem(text) {
  return { _type: 'block', style: 'normal', listItem: 'bullet', children: [{ _type: 'span', text: text }] };
}
function makeNumberedItem(text) {
  return { _type: 'block', style: 'normal', listItem: 'number', children: [{ _type: 'span', text: text }] };
}
function makeFAQBlock(q, a) {
  return [makeHeading(q, 'h3'), ...makeBlock(a)];
}
async function createPost(post) {
  const mutations = [{ create: post }];
  const res = await fetch(URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${SANITY_TOKEN}` },
    body: JSON.stringify({ mutations })
  });
  const data = await res.json();
  if (data.error) { console.error(`FAILED: ${post.title.en}`, data.error.message); return null; }
  const id = data.results?.[0]?.id;
  console.log(`OK: ${post.title.en} → ${id}`);
  return id;
}

// ===== ARTICLE 19: Hybrid Cloud Architecture =====
const article19 = {
  _type: 'post',
  title: { en: 'Hybrid Cloud Architecture: On-Premises + AWS/Azure', zh: '混合云架构：本地部署+AWS/Azure' },
  titleZh: '混合云架构：本地部署+AWS/Azure',
  slug: { current: 'hybrid-cloud-architecture-guide' },
  category: 'technical',
  excerpt: {
    en: 'Hybrid cloud combines on-premises infrastructure with AWS or Azure for flexibility and cost control. This architecture guide covers network design, workload placement, and security for enterprise hybrid cloud.',
    zh: '混合云将本地基础设施与AWS或Azure结合，实现灵活性和成本控制。本架构指南涵盖企业混合云的网络设计、工作负载分配和安全策略。'
  },
  excerptZh: '混合云将本地基础设施与AWS或Azure结合，实现灵活性和成本控制。本架构指南涵盖企业混合云的网络设计、工作负载分配和安全策略。',
  coverImage: 'https://picsum.photos/seed/hybrid-cloud-architecture-guide/800/450',
  language: 'en',
  publishedAt: '2025-01-31T00:00:00Z',
  content: [
    makeHeading('Hybrid Cloud Architecture: On-Premises + AWS/Azure', 'h1'),
    ...makeBlock('A Philippine bank had a constraint: customer data must stay on Philippine soil (Bangko Sentral ng Pilipinas regulation). But their marketing team needed to deploy a customer-facing web app that could handle 10x traffic spikes during loan promotions.'),
    ...makeBlock('The solution: keep the core banking system on-premises in their Manila data center. Deploy the web frontend on AWS in the Singapore region (closest to Philippine users). Connect them through a dedicated AWS Direct Connect link. The app handles 10x traffic. Customer data stays local. Everyone\'s happy.'),
    ...makeBlock('That\'s hybrid cloud done right. Not a migration — a strategic extension.'),
    makeHeading('What is Hybrid Cloud?', 'h2'),
    ...makeBlock('Hybrid cloud is an architecture that connects on-premises infrastructure (your data center) with public cloud resources (AWS, Azure, or GCP). Workloads run where they make the most sense: sensitive data stays on-premises, scalable applications run in the cloud.'),
    ...makeBlock('It\'s not "cloud-first" or "cloud-only." It\'s "right cloud for the right workload."'),
    makeHeading('Why Hybrid Cloud Matters', 'h2'),
    ...makeBlock('Three forces drive hybrid cloud adoption in Southeast Asia:'),
    makeListItem('Data sovereignty: Regulations in the Philippines, Indonesia, and Vietnam require certain data to stay in-country. Public cloud regions may not be available locally.'),
    makeListItem('Cost optimization: On-premises infrastructure is cheaper for steady-state workloads. Cloud is cheaper for variable workloads. Hybrid gives you the best of both.'),
    makeListItem('Legacy modernization: You can\'t lift-and-shift a 15-year-old ERP to the cloud overnight. Hybrid lets you modernize gradually.'),
    ...makeBlock('The numbers back this up: 82% of enterprises have a hybrid cloud strategy (Flexera 2024). It\'s not a trend — it\'s the default architecture.'),
    makeHeading('Architecture Components', 'h2'),
    ...makeBlock('A hybrid cloud architecture has four key components:'),
    makeNumberedItem('On-premises infrastructure: Your data center running HCI, VMware, or traditional infrastructure. This is your "home base" for sensitive data and steady-state workloads.'),
    makeNumberedItem('Public cloud resources: AWS, Azure, or GCP for scalable applications, DR, dev/test, and cloud-native services.'),
    makeNumberedItem('Network connectivity: The bridge between on-premises and cloud. Options include Direct Connect/ExpressRoute (dedicated), site-to-site VPN (encrypted over internet), or SD-WAN.'),
    makeNumberedItem('Management layer: Tools to manage both environments from a single pane. Examples: Azure Arc, AWS Outposts, Nutanix Xi, or third-party tools like Terraform.'),
    makeHeading('Network Design', 'h2'),
    ...makeBlock('Network design makes or breaks hybrid cloud. Here\'s what we recommend:'),
    ...makeBlock('Primary link: AWS Direct Connect or Azure ExpressRoute (100Mbps-1Gbps dedicated). Latency: 2-5ms to nearest cloud region. Cost: $500-2,000/month depending on bandwidth.'),
    ...makeBlock('Backup link: Site-to-site VPN over your existing internet connection. Failover if the dedicated link goes down. Cost: free (uses existing internet).'),
    ...makeBlock('DNS: Use a split-horizon DNS setup. Internal DNS resolves on-premises resources. External DNS resolves cloud resources. Users don\'t need to know where things run.'),
    ...makeBlock('IP addressing: Plan IP ranges carefully. Use non-overlapping CIDR blocks for on-premises and cloud. Example: on-premises uses 10.0.0.0/16, AWS VPC uses 172.16.0.0/16.'),
    makeHeading('Workload Placement Strategy', 'h2'),
    ...makeBlock('Where should each workload run? Here\'s our decision framework:'),
    ...makeBlock('Keep on-premises:'),
    makeListItem('Sensitive data (customer PII, financial records) subject to data sovereignty.'),
    makeListItem('Latency-sensitive applications (databases, ERP) that need <1ms response time.'),
    makeListItem('Steady-state workloads with predictable resource needs.'),
    makeListItem('Legacy applications that can\'t be easily refactored for cloud.'),
    ...makeBlock('Move to cloud:'),
    makeListItem('Scalable web applications with variable traffic patterns.'),
    makeListItem('Development and testing environments (self-service provisioning).'),
    makeListItem('Disaster recovery (cheaper than a physical DR site).'),
    makeListItem('Cloud-native services (AI/ML, analytics, IoT processing).'),
    ...makeBlock('The key question for each workload: "Does this need to be close to my data center, or can it run anywhere?" If it needs to be close, keep it on-premises. If it can run anywhere, cloud is usually better.'),
    makeHeading('Security Architecture', 'h2'),
    ...makeBlock('Hybrid cloud security requires a unified approach across both environments:'),
    makeNumberedItem('Identity: Use a single identity provider (Azure AD, Okta) for both on-premises and cloud. Single sign-on everywhere.'),
    makeNumberedItem('Encryption: Encrypt data in transit (TLS 1.3) and at rest (AES-256) in both environments. Use cloud KMS for cloud data, on-prem HSM for sensitive keys.'),
    makeNumberedItem('Network segmentation: Use microsegmentation (NSX, AWS Security Groups) to isolate workloads. Don\'t let cloud resources freely access on-premises databases.'),
    makeNumberedItem('Monitoring: Centralize logs and alerts. Use a SIEM that covers both environments (Splunk, Sentinel, or Elastic).'),
    makeNumberedItem('Compliance: Map regulatory requirements to specific controls. Document which data is where and why.'),
    makeHeading('Cost Management', 'h2'),
    ...makeBlock('Hybrid cloud costs can be managed with discipline:'),
    makeListItem('On-premises: Fixed costs (hardware, power, staff). Predictable but inflexible.'),
    makeListItem('Cloud: Variable costs (pay-per-use). Flexible but can surprise you.'),
    ...makeBlock('Cost optimization tips:'),
    makeNumberedItem('Reserved instances for predictable cloud workloads (save 40-60%).'),
    makeNumberedItem('Spot instances for batch processing (save 70-90%).'),
    makeNumberedItem('Auto-scaling to match demand. Don\'t run cloud resources 24/7 if you only need them 8 hours/day.'),
    makeNumberedItem('Cost monitoring dashboards. Review weekly. Set billing alerts.'),
    ...makeBlock('A typical hybrid cloud deployment costs 20-30% less than all-on-premises or all-cloud, when workload placement is optimized.'),
    makeHeading('Best Practices', 'h2'),
    makeNumberedItem('Start with a clear use case. Don\'t adopt hybrid cloud because it\'s trendy. Adopt it because you have a specific problem it solves (DR, scalability, compliance).'),
    makeNumberedItem('Invest in networking. The network between on-premises and cloud is your biggest risk point. Use dedicated links with redundancy.'),
    makeNumberedItem('Automate everything. Use Terraform, Ansible, or cloud-native IaC for provisioning. Manual configuration doesn\'t scale.'),
    makeNumberedItem('Plan for failure. What happens if the cloud link goes down? Your on-premises workloads should keep running independently.'),
    makeNumberedItem('Review monthly. Cloud costs, network performance, workload placement — review and optimize every month.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('Hybrid cloud is the practical architecture for enterprises that need both the control of on-premises and the flexibility of cloud. Start with a specific use case (DR or scalable web app), build the network bridge, and expand from there.'),
    ...makeBlock('The bank from the opening story now runs 30% of their workloads in AWS and 70% on-premises. They didn\'t "move to the cloud" — they extended to it. That\'s the hybrid cloud mindset.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: What\'s the difference between hybrid cloud and multi-cloud?', 'A: Hybrid cloud connects on-premises with one or more public clouds. Multi-cloud uses multiple public clouds (e.g., AWS + Azure) without necessarily including on-premises. Most enterprises are both hybrid and multi-cloud.'),
    ...makeFAQBlock('Q: How much does network connectivity cost?', 'A: AWS Direct Connect: $500-2,000/month for 100Mbps-1Gbps. Azure ExpressRoute: similar pricing. Site-to-site VPN: free (uses existing internet). Budget $1,000-3,000/month for production hybrid networking.'),
    ...makeFAQBlock('Q: Can I run Kubernetes across hybrid cloud?', 'A: Yes. Azure AKS Arc, AWS EKS Anywhere, and Rancher all support hybrid Kubernetes. Your containers can run on-premises and in the cloud with a single management plane.'),
    ...makeFAQBlock('Q: Which cloud is best for Philippine enterprises?', 'A: AWS has the largest global footprint. Azure integrates best with Microsoft ecosystems. Both have Singapore regions with good latency to the Philippines. GCP is growing but has less local presence.'),
  ]
};

// ===== ARTICLE 20: DR Site Design =====
const article20 = {
  _type: 'post',
  title: { en: 'DR Site Design: Active-Passive vs Active-Active', zh: '灾难恢复站点设计：主备模式 vs 双活模式' },
  titleZh: '灾难恢复站点设计：主备模式 vs 双活模式',
  slug: { current: 'dr-site-design-active-passive' },
  category: 'technical',
  excerpt: {
    en: 'Active-passive DR is simpler and cheaper; active-active provides near-zero downtime. This guide compares both approaches with real deployment data, cost analysis, and decision frameworks for enterprise DR.',
    zh: '主备模式DR更简单、更便宜；双活模式提供近乎零停机。本指南比较两种方法，包含真实部署数据、成本分析和企业级DR决策框架。'
  },
  excerptZh: '主备模式DR更简单、更便宜；双活模式提供近乎零停机。本指南比较两种方法，包含真实部署数据、成本分析和企业级DR决策框架。',
  coverImage: 'https://picsum.photos/seed/dr-site-design-active-passive/800/450',
  language: 'en',
  publishedAt: '2025-02-02T00:00:00Z',
  content: [
    makeHeading('DR Site Design: Active-Passive vs Active-Active', 'h1'),
    ...makeBlock('At 3am on a Saturday, a typhoon hit Metro Manila. A 500-person BPO company lost power to their primary data center. Their active-passive DR site kicked in within 12 minutes. 400 agents were back on calls by 3:30am. Total downtime: 12 minutes. Total data loss: zero.'),
    ...makeBlock('That\'s active-passive DR working as designed. But what if 12 minutes of downtime costs your business $60,000? Then you need active-active. Here\'s how to choose.'),
    makeHeading('What is Active-Passive DR?', 'h2'),
    ...makeBlock('Active-passive DR means you have two sites: a primary site that handles all production traffic, and a standby site that mirrors your data but stays idle until disaster strikes.'),
    ...makeBlock('How it works:'),
    makeListItem('Primary site: All VMs run here. All user traffic goes here.'),
    makeListItem('Standby site: Data replicates from primary to standby. VMs exist but are powered off or minimal.'),
    makeListItem('Failover: When primary fails, you manually (or automatically) power up standby VMs and redirect traffic. RTO: 10-30 minutes.'),
    ...makeBlock('Cost: The standby site costs 30-50% of the primary site (less hardware, no licensing for idle VMs).'),
    makeHeading('What is Active-Active DR?', 'h2'),
    ...makeBlock('Active-active means both sites run production workloads simultaneously. Traffic is distributed across sites. If one site fails, the other absorbs all traffic with minimal disruption.'),
    ...makeBlock('How it works:'),
    makeListItem('Both sites: Run identical workloads. Users are distributed across sites (via DNS, load balancer, or global server load balancing).'),
    makeListItem('Data replication: Synchronous between sites (requires <5ms latency).'),
    makeListItem('Failover: Automatic. If one site fails, the other absorbs all traffic. RTO: 0-2 minutes.'),
    ...makeBlock('Cost: The second site costs 80-100% of the primary site (full hardware, full licensing, full staffing).'),
    makeHeading('Head-to-Head Comparison', 'h2'),
    ...makeBlock('Here\'s the data from our deployments:'),
    ...makeBlock('Recovery Time Objective (RTO):'),
    makeListItem('Active-passive: 10-30 minutes (manual failover) or 2-5 minutes (automated).'),
    makeListItem('Active-active: 0-2 minutes (automatic).'),
    ...makeBlock('Recovery Point Objective (RPO):'),
    makeListItem('Active-passive: 15-60 minutes (async replication).'),
    makeListItem('Active-active: 0 (synchronous replication).'),
    ...makeBlock('Cost (relative to primary site):'),
    makeListItem('Active-passive: 30-50%.'),
    makeListItem('Active-active: 80-100%.'),
    ...makeBlock('Complexity:'),
    makeListItem('Active-passive: Moderate. Requires failover testing and runbooks.'),
    makeListItem('Active-active: High. Requires load balancing, synchronous replication, and conflict resolution.'),
    ...makeBlock('Staffing:'),
    makeListItem('Active-passive: Can be managed by existing IT team.'),
    makeListItem('Active-active: Requires dedicated infrastructure team or managed service.'),
    makeHeading('When to Choose Active-Passive', 'h2'),
    ...makeBlock('Active-passive is the right choice when:'),
    makeListItem('Your RTO can tolerate 10-30 minutes of downtime.'),
    makeListItem('Your budget is limited (30-50% cost savings versus active-active).'),
    makeListItem('Your workloads don\'t require zero data loss.'),
    makeListItem('You have a small IT team that needs simpler operations.'),
    ...makeBlock('Typical use cases:'),
    makeListItem('BPO companies with shift-based operations (10-minute failover is acceptable).'),
    makeListItem('Manufacturing (ERP downtime is painful but not life-threatening).'),
    makeListItem('Retail (POS systems need HA, not real-time DR).'),
    makeListItem('Education and government (budget-constrained, moderate RTO requirements).'),
    makeHeading('When to Choose Active-Active', 'h2'),
    ...makeBlock('Active-active is the right choice when:'),
    makeListItem('Every minute of downtime costs significant revenue or reputation.'),
    makeListItem('Regulatory requirements mandate zero data loss (financial services, healthcare).'),
    makeListItem('You have the budget and team to manage the complexity.'),
    makeListItem('Your users are geographically distributed across two regions.'),
    ...makeBlock('Typical use cases:'),
    makeListItem('Financial services (banking, insurance — every minute of downtime = regulatory risk).'),
    makeListItem('Healthcare (patient care systems can\'t go down).'),
    makeListItem('E-commerce (Black Friday traffic needs real-time failover).'),
    makeListItem('Global SaaS platforms (users expect 99.99% uptime).'),
    makeHeading('Implementation Architecture', 'h2'),
    ...makeBlock('Active-passive architecture:'),
    makeNumberedItem('Primary site: 4-node HCI cluster running production workloads.'),
    makeNumberedItem('DR site: 2-node HCI cluster with data replicated from primary.'),
    makeNumberedItem('Replication: Async (RPO 15-60 minutes) over dedicated WAN link.'),
    makeNumberedItem('Failover: Nutanix Runbook or VMware SRM for automated failover.'),
    makeNumberedItem('Testing: Quarterly failover tests to verify the process.'),
    ...makeBlock('Active-active architecture:'),
    makeNumberedItem('Site A: 4-node HCI cluster running half the workloads.'),
    makeNumberedItem('Site B: 4-node HCI cluster running the other half.'),
    makeNumberedItem('Replication: Synchronous between sites (<5ms latency required).'),
    makeNumberedItem('Traffic distribution: Global load balancer (F5, Cloudflare, or AWS Route 53).'),
    makeNumberedItem('Monitoring: Real-time health checks across both sites.'),
    ...makeBlock('The active-active architecture requires careful capacity planning. Each site must be able to handle 100% of traffic if the other fails.'),
    makeHeading('Cost Analysis', 'h2'),
    ...makeBlock('Here\'s a real cost comparison for a 200-VM environment:'),
    ...makeBlock('Active-passive:'),
    makeListItem('Primary site: $80,000 (hardware) + $15,000/year (licensing).'),
    makeListItem('DR site: $35,000 (hardware) + $8,000/year (licensing).'),
    makeListItem('WAN link: $1,000/month.'),
    makeListItem('Total 3-year cost: $163,000.'),
    ...makeBlock('Active-active:'),
    makeListItem('Site A: $80,000 (hardware) + $15,000/year (licensing).'),
    makeListItem('Site B: $80,000 (hardware) + $15,000/year (licensing).'),
    makeListItem('WAN link: $2,000/month (higher bandwidth for sync replication).'),
    makeListItem('Load balancer: $10,000.'),
    makeListItem('Total 3-year cost: $272,000.'),
    ...makeBlock('Active-active costs 67% more. That premium buys you near-zero downtime and zero data loss. Worth it for financial services. Overkill for most other industries.'),
    makeHeading('Best Practices', 'h2'),
    makeNumberedItem('Test failover quarterly. A DR plan you haven\'t tested is a theory, not a plan.'),
    makeNumberedItem('Document runbooks. Step-by-step procedures for failover, failback, and escalation.'),
    makeNumberedItem('Monitor replication health daily. Replication lag is the silent killer of DR.'),
    makeNumberedItem('Consider cloud DR as an alternative. AWS, Azure, and GCP all offer DR services that can replace a physical DR site at 60-80% lower cost.'),
    makeNumberedItem('Start with active-passive. Upgrade to active-active only if you have a proven need for zero downtime.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('Active-passive DR is the right choice for 80% of enterprises. It\'s simpler, cheaper, and provides adequate protection for most workloads. Active-active is for the 20% that truly cannot tolerate downtime — financial services, healthcare, and global SaaS platforms.'),
    ...makeBlock('Start with active-passive. Test it. If 10-30 minutes of downtime is acceptable, stay with it. If not, upgrade to active-active. Don\'t over-engineer DR from day one.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: Can I mix active-passive and active-active?', 'A: Yes. Run critical workloads (databases, EHR) in active-active, and less critical workloads (dev/test, admin systems) in active-passive. This balances cost and protection.'),
    ...makeFAQBlock('Q: What WAN speed do I need for DR?', 'A: Active-passive: 100Mbps-1Gbps (async replication). Active-active: 1Gbps+ with <5ms latency (sync replication). Budget $1,000-3,000/month for dedicated WAN.'),
    ...makeFAQBlock('Q: How often should I test DR?', 'A: Quarterly for active-passive. Monthly for active-active. Document every test. Fix every failure. A DR test that passes is confidence; one that fails is a gift.'),
    ...makeFAQBlock('Q: Is cloud DR better than on-premises DR?', 'A: Cloud DR costs 60-80% less than a physical DR site. Tradeoff: longer failover time (minutes vs seconds) and reliance on internet connectivity. For most enterprises, cloud DR is the better choice.'),
  ]
};

// ===== ARTICLE 21: Cloud Migration 6R =====
const article21 = {
  _type: 'post',
  title: { en: 'Cloud Migration: 6R Approach Guide', zh: '云迁移：6R方法指南' },
  titleZh: '云迁移：6R方法指南',
  slug: { current: 'cloud-migration-6r-approach' },
  category: 'technical',
  excerpt: {
    en: 'The 6R migration framework (Rehost, Replatform, Refactor, Repurchase, Retire, Retain) helps enterprises make smart cloud migration decisions. This guide walks through each strategy with real examples.',
    zh: '6R迁移框架（重新托管、重新平台化、重构、更换、退役、保留）帮助企业做出明智的云迁移决策。本指南通过真实案例逐一讲解每种策略。'
  },
  excerptZh: '6R迁移框架（重新托管、重新平台化、重构、更换、退役、保留）帮助企业做出明智的云迁移决策。本指南通过真实案例逐一讲解每种策略。',
  coverImage: 'https://picsum.photos/seed/cloud-migration-6r-approach/800/450',
  language: 'en',
  publishedAt: '2025-02-04T00:00:00Z',
  content: [
    makeHeading('Cloud Migration: 6R Approach Guide', 'h1'),
    ...makeBlock('A manufacturing company wanted to "move everything to the cloud." After analyzing their 120 applications, we found: 15% should be retired, 25% should stay on-premises, 40% should be rehosted (lift-and-shift), and only 20% would benefit from cloud-native redesign.'),
    ...makeBlock('Their original plan would have cost $800,000/year in cloud fees. Our 6R analysis brought it down to $320,000/year — while actually improving performance for the workloads that truly belonged in the cloud.'),
    ...makeBlock('The 6R framework is the most practical tool for cloud migration decisions. Here\'s how to use it.'),
    makeHeading('What is the 6R Framework?', 'h2'),
    ...makeBlock('The 6R framework, originally defined by Gartner and refined by AWS, categorizes every workload into one of six migration strategies:'),
    makeNumberedItem('Rehost (lift-and-shift): Move as-is to cloud infrastructure.'),
    makeNumberedItem('Replatform (lift-and-optimize): Move with minor optimizations.'),
    makeNumberedItem('Refactor (re-architect): Redesign for cloud-native architecture.'),
    makeNumberedItem('Repurchase (drop-and-shop): Switch to a SaaS alternative.'),
    makeNumberedItem('Retire: Decommission applications no longer needed.'),
    makeNumberedItem('Retain: Keep on-premises for now.'),
    ...makeBlock('The key insight: not every workload should be migrated. The goal is to put each workload in the right place, not to move everything to the cloud.'),
    makeHeading('Strategy 1: Rehost (Lift-and-Shift)', 'h2'),
    ...makeBlock('What it means: Move the VM as-is from on-premises to cloud IaaS (EC2, Azure VMs). No code changes, no architecture changes. Just change the hosting platform.'),
    ...makeBlock('Effort: Low (days to weeks per application).'),
    ...makeBlock('Cost: Low migration cost, moderate ongoing cloud cost.'),
    ...makeBlock('When to use:'),
    makeListItem('Legacy applications with no cloud-native path.'),
    makeListItem('Time-sensitive migrations (data center lease expiring).'),
    makeListItem('Applications that work fine as-is but need to move off aging hardware.'),
    ...makeBlock('Real example: A law firm moved 30 file servers from on-premises to AWS EC2 in 2 weeks. No code changes. The servers work exactly the same — just running on AWS instead of Dell hardware. Cost: $3,000/month in EC2 fees vs $15,000/year in hardware refresh.'),
    ...makeBlock('Watch out: Rehosted applications don\'t get cloud-native benefits (auto-scaling, managed services). You\'re just renting someone else\'s server.'),
    makeHeading('Strategy 2: Replatform (Lift-and-Optimize)', 'h2'),
    ...makeBlock('What it means: Move to cloud with minor optimizations. Not a full redesign, but take advantage of managed services where it\'s easy.'),
    ...makeBlock('Effort: Medium (weeks to months per application).'),
    ...makeBlock('Cost: Moderate migration cost, lower ongoing cost than rehosting.'),
    ...makeBlock('When to use:'),
    makeListItem('Applications that can benefit from managed databases (RDS, Azure SQL).'),
    makeListItem('Workloads that can use managed file storage (EFS, Azure Files).'),
    makeListItem('Applications where swapping components is low-risk.'),
    ...makeBlock('Real example: A hospital moved their ERP database from on-premises SQL Server to AWS RDS (managed SQL Server). Same application, same SQL queries, but AWS handles patching, backups, and HA. Saved 40% on database administration.'),
    ...makeBlock('Watch out: Replatforming can introduce subtle compatibility issues. Test thoroughly.'),
    makeHeading('Strategy 3: Refactor (Re-architect)', 'h2'),
    ...makeBlock('What it means: Redesign the application for cloud-native architecture. Break monoliths into microservices, use containers (ECS/EKS), serverless (Lambda), and cloud-native databases.'),
    ...makeBlock('Effort: High (months to years per application).'),
    ...makeBlock('Cost: High migration cost, lowest ongoing cost.'),
    ...makeBlock('When to use:'),
    makeListItem('Applications with high scaling requirements (web apps, APIs).'),
    makeListItem('When the current architecture can\'t meet performance or cost targets.'),
    makeListItem('When you have budget and time for a proper redesign.'),
    ...makeBlock('Real example: An e-commerce platform refactored from a monolithic PHP application to microservices on Kubernetes. Deployment frequency went from monthly to daily. Auto-scaling handled 10x traffic spikes automatically. Ongoing cost dropped 60% after the refactor.'),
    ...makeBlock('Watch out: Refactoring is expensive and risky. Only do it for high-value applications with clear ROI.'),
    makeHeading('Strategy 4: Repurchase (Drop-and-Shop)', 'h2'),
    ...makeBlock('What it means: Replace your custom application with a SaaS alternative. Don\'t migrate the app — replace it.'),
    ...makeBlock('Effort: Medium (data migration + user training).'),
    ...makeBlock('Cost: SaaS subscription replaces custom development/maintenance costs.'),
    ...makeBlock('When to use:'),
    makeListItem('Custom CRM → Salesforce.'),
    makeListItem('Custom HR system → Workday or BambooHR.'),
    makeListItem('Custom email → Microsoft 365 or Google Workspace.'),
    ...makeBlock('Real example: A 200-person company replaced their custom-built HR system (10 years old, barely maintained) with BambooHR. Implementation took 4 weeks. Ongoing cost: $8/user/month vs $50,000/year in maintenance.'),
    ...makeBlock('Watch out: SaaS means less customization. If your custom app has unique business logic, SaaS may not cover it.'),
    makeHeading('Strategy 5: Retire', 'h2'),
    ...makeBlock('What it means: Decommission applications that are no longer needed.'),
    ...makeBlock('Effort: Low (audit + shutdown).'),
    ...makeBlock('Cost: Zero migration cost. Saves ongoing maintenance costs.'),
    ...makeBlock('When to use:'),
    makeListItem('Applications with zero or very few users.'),
    makeListItem('Duplicate applications (two systems doing the same thing).'),
    makeListItem('Legacy apps replaced by newer systems but never decommissioned.'),
    ...makeBlock('Real example: During a 6R assessment, we found a 500-person company running 87 applications. 22 had zero active users. Retiring them saved $180,000/year in licensing and maintenance.'),
    ...makeBlock('Watch out: Retiring applications requires stakeholder buy-in. Someone "owns" every app, and they may resist retirement.'),
    makeHeading('Strategy 6: Retain', 'h2'),
    ...makeBlock('What it means: Keep the application on-premises for now. Revisit in 6-12 months.'),
    ...makeBlock('Effort: Zero.'),
    ...makeBlock('Cost: No change.'),
    ...makeBlock('When to use:'),
    makeListItem('Applications with data sovereignty requirements that cloud can\'t meet yet.'),
    makeListItem('Recently upgraded applications (don\'t migrate right after a major investment).'),
    makeListItem('Applications with unclear business value (need more analysis).'),
    ...makeBlock('Real example: A bank\'s core banking system was recently upgraded at a cost of $2M. Retaining it on-premises for 3 more years makes financial sense. Cloud migration will be evaluated in 2027.'),
    makeHeading('How to Apply 6R to Your Applications', 'h2'),
    ...makeBlock('Here\'s our step-by-step process:'),
    makeNumberedItem('Inventory: List all applications. Include owner, users, dependencies, and current infrastructure.'),
    makeNumberedItem('Assess: For each application, evaluate business value, technical complexity, and cloud readiness.'),
    makeNumberedItem('Categorize: Assign each application a 6R strategy. Use the decision tree: Is it needed? → Retire or Retain. Is there a SaaS alternative? → Repurchase. Can it run as-is? → Rehost. Can it be optimized? → Replatform. Should it be redesigned? → Refactor.'),
    makeNumberedItem('Prioritize: Start with quick wins (Retire, Rehost). Build momentum. Save Refactor for high-value applications.'),
    makeNumberedItem('Execute: Migrate in waves. Each wave = 5-10 applications. Test, validate, optimize, then move to the next wave.'),
    makeHeading('Best Practices', 'h2'),
    makeNumberedItem('Don\'t force everything into one strategy. The power of 6R is that different workloads get different treatments.'),
    makeNumberedItem('Start with Retire and Retain. These are zero-effort decisions that immediately clarify your migration scope.'),
    makeNumberedItem('Rehost first, refactor later. Get to the cloud quickly with rehosting. Optimize in place over time.'),
    makeNumberedItem('Estimate total cost of ownership (TCO) for each strategy. The cheapest migration isn\'t always the cheapest long-term.'),
    makeNumberedItem('Involve application owners early. They know their apps best and will be key to successful migration.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('The 6R framework prevents the #1 cloud migration mistake: treating every workload the same. Some apps should be retired. Some should stay on-premises. Some should be rehosted. Only a few benefit from full refactoring.'),
    ...makeBlock('Start by inventorying your applications. Apply the 6R framework. You\'ll likely find that 20-40% of your portfolio doesn\'t need to move to the cloud at all — and that realization saves you hundreds of thousands of dollars.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: How long does a 6R assessment take?', 'A: For a 50-application portfolio: 2-4 weeks. For 200+ applications: 6-8 weeks. The assessment itself is the most valuable part — it prevents costly migration mistakes.'),
    ...makeFAQBlock('Q: Can an application use multiple 6R strategies?', 'A: Not simultaneously, but over time. You might rehost first, then refactor later as the business case justifies it. The strategy is a snapshot in time.'),
    ...makeFAQBlock('Q: What tools help with 6R assessments?', 'A: AWS Migration Acceleration Program (MAP), Azure Migration Program, and third-party tools like Cloudamize and Turbonomic provide automated discovery and assessment.'),
    ...makeFAQBlock('Q: What\'s the biggest risk in cloud migration?', 'A: Underestimating complexity. Rehosting looks easy but can reveal hidden dependencies. Refactoring looks ambitious but may be necessary for cost optimization. The 6R framework helps you make informed decisions.'),
  ]
};

// ===== ARTICLE 22: DRaaS vs Self-Built DR =====
const article22 = {
  _type: 'post',
  title: { en: 'DRaaS vs Self-Built DR: Which is Better?', zh: 'DRaaS vs自建DR：哪个更好？' },
  titleZh: 'DRaaS vs自建DR：哪个更好？',
  slug: { current: 'draas-vs-self-built-dr' },
  category: 'technical',
  excerpt: {
    en: 'DRaaS delivers disaster recovery as a managed service; self-built DR gives you full control. This comparison covers cost, complexity, RTO/RPO, and real-world tradeoffs to help you choose.',
    zh: 'DRaaS将灾难恢复作为托管服务交付；自建DR给你完全控制权。本对比涵盖成本、复杂性、RTO/RPO和真实权衡，帮助你做出选择。'
  },
  excerptZh: 'DRaaS将灾难恢复作为托管服务交付；自建DR给你完全控制权。本对比涵盖成本、复杂性、RTO/RPO和真实权衡，帮助你做出选择。',
  coverImage: 'https://picsum.photos/seed/draas-vs-self-built-dr/800/450',
  language: 'en',
  publishedAt: '2025-02-06T00:00:00Z',
  content: [
    makeHeading('DRaaS vs Self-Built DR: Which is Better?', 'h1'),
    ...makeBlock('A mid-size insurance company spent $150,000 building their own DR site. They bought hardware, set up replication, configured failover, and hired a dedicated DR engineer. Two years later, they tested failover — and it failed. The replication had silently broken 6 months ago. No one noticed because nobody was monitoring it.'),
    ...makeBlock('They switched to Zerto DRaaS. Monthly cost: $2,500. The DRaaS provider monitors replication 24/7, tests failover monthly, and provides a tested recovery environment. The insurance company\'s DR engineer now focuses on application modernization instead of babysitting replication.'),
    ...makeBlock('Self-built DR gives you control. DRaaS gives you reliability. Here\'s how to decide.'),
    makeHeading('What is DRaaS?', 'h2'),
    ...makeBlock('DRaaS (Disaster Recovery as a Service) is a managed service where a third-party provider handles your disaster recovery infrastructure. You replicate your data to their cloud. They handle the hardware, networking, monitoring, and failover orchestration.'),
    ...makeBlock('Major DRaaS providers: Zerto (now part of HPE), Veeam Cloud Connect, AWS Disaster Recovery, Azure Site Recovery, Rubrik.'),
    makeHeading('What is Self-Built DR?', 'h2'),
    ...makeBlock('Self-built DR means you own and operate your own DR infrastructure. You buy the hardware, set up the replication, configure the failover, and maintain everything yourself.'),
    ...makeBlock('Self-built DR options:'),
    makeListItem('Physical DR site: Your own secondary data center with duplicate infrastructure.'),
    makeListItem('Cloud DR: VMs and storage in AWS/Azure that you manage yourself.'),
    makeListItem('HCI-based DR: Nutanix or VMware cluster at a co-location facility.'),
    makeHeading('Head-to-Head Comparison', 'h2'),
    ...makeBlock('Here\'s what we\'ve seen across 30+ DR deployments:'),
    ...makeBlock('Upfront Cost:'),
    makeListItem('DRaaS: Low ($0-5,000 setup). Pay monthly.'),
    makeListItem('Self-built: High ($50,000-200,000 for hardware, networking, facility).'),
    ...makeBlock('Monthly Cost:'),
    makeListItem('DRaaS: $1,000-10,000/month (based on protected data volume).'),
    makeListItem('Self-built: $2,000-5,000/month (power, cooling, licensing, staff).'),
    ...makeBlock('RTO/RPO:'),
    makeListItem('DRaaS: RPO 15-60 minutes, RTO 15-60 minutes (provider-managed).'),
    makeListItem('Self-built: RPO 0-15 minutes, RTO 5-30 minutes (if properly maintained).'),
    ...makeBlock('Operational Burden:'),
    makeListItem('DRaaS: Low. Provider handles monitoring, patching, testing.'),
    makeListItem('Self-built: High. Your team handles everything.'),
    ...makeBlock('Control:'),
    makeListItem('DRaaS: Limited. You\'re dependent on provider\'s infrastructure and policies.'),
    makeListItem('Self-built: Full control over hardware, software, and configuration.'),
    ...makeBlock('Expertise Required:'),
    makeListItem('DRaaS: Basic. Provider handles the complex parts.'),
    makeListItem('Self-built: Advanced. Need dedicated DR/infrastructure expertise.'),
    makeHeading('When DRaaS is the Better Choice', 'h2'),
    ...makeBlock('DRaaS wins when:'),
    makeListItem('Your IT team is small (1-3 people). Self-built DR requires dedicated expertise you probably don\'t have.'),
    makeListItem('Budget is constrained. DRaaS avoids $50,000-200,000 in upfront costs.'),
    makeListItem('You need fast deployment. DRaaS can be operational in days. Self-built takes months.'),
    makeListItem('You want guaranteed SLAs. DRaaS providers offer contractual RTO/RPO guarantees.'),
    makeListItem('You\'re not confident in your DR testing. DRaaS providers test failover regularly.'),
    ...makeBlock('The insurance company from the opening story is a perfect DRaaS candidate: small team, limited budget, and they needed someone to actually monitor the DR environment.'),
    makeHeading('When Self-Built DR is the Better Choice', 'h2'),
    ...makeBlock('Self-built DR wins when:'),
    makeListItem('You have strict data sovereignty requirements. Some data can\'t leave your physical control.'),
    makeListItem('You need RPO=0 (synchronous replication). DRaaS typically offers async only.'),
    makeListItem('You have existing infrastructure expertise and capacity. If you already run a data center, adding a DR site is incremental.'),
    makeListItem('You\'re running specialized workloads (mainframes, legacy systems) that DRaaS providers don\'t support.'),
    makeListItem('Cost is lower long-term. If you\'re protecting 500TB+ of data, self-built is cheaper per TB.'),
    ...makeBlock('A Philippine bank we work with uses self-built DR because BSP regulations require data to stay within their physical control. DRaaS providers in the Philippines don\'t meet this requirement yet.'),
    makeHeading('Hybrid Approach: Best of Both', 'h2'),
    ...makeBlock('Many enterprises use a hybrid approach:'),
    makeListItem('Critical workloads: Self-built DR with synchronous replication (RPO=0, RTO<5 minutes).'),
    makeListItem('Standard workloads: DRaaS with async replication (RPO 15-60 minutes, RTO 30-60 minutes).'),
    ...makeBlock('This gives you maximum protection for critical systems while keeping costs manageable for everything else. We\'ve seen this pattern reduce DR costs by 40% compared to self-built for everything.'),
    makeHeading('Cost Breakdown', 'h2'),
    ...makeBlock('Let\'s compare real costs for a 100-VM, 50TB environment over 3 years:'),
    ...makeBlock('DRaaS (Zerto + AWS):'),
    makeListItem('Setup: $2,000.'),
    makeListItem('Monthly: $3,000 (Zerto license + AWS storage + compute).'),
    makeListItem('Total 3-year: $110,000.'),
    ...makeBlock('Self-Built (Nutanix at co-location):'),
    makeListItem('Hardware: $60,000 (2-node Nutanix cluster).'),
    makeListItem('Co-location: $1,500/month.'),
    makeListItem('Licensing: $500/month.'),
    makeListItem('Staff: 0.5 FTE = $25,000/year.'),
    makeListItem('Total 3-year: $159,000.'),
    ...makeBlock('DRaaS saves $49,000 over 3 years. But self-built gives you RPO=0 and full control. The right choice depends on your requirements.'),
    makeHeading('Best Practices', 'h2'),
    makeNumberedItem('Test DR regardless of approach. DRaaS or self-built — test quarterly. A DR solution that hasn\'t been tested is a gamble.'),
    makeNumberedItem('Document everything. Runbooks, escalation paths, contact lists. When disaster strikes at 2am, you need clear instructions.'),
    makeNumberedItem('Start with DRaaS if unsure. It\'s easier to switch from DRaaS to self-built than the other way around.'),
    makeNumberedItem('Consider hybrid. Critical workloads self-built, standard workloads DRaaS. Optimize cost and protection.'),
    makeNumberedItem('Review annually. Your DR needs change as your infrastructure evolves. Review and adjust yearly.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('DRaaS is the better choice for most mid-size enterprises: lower upfront cost, less operational burden, and faster deployment. Self-built DR makes sense for organizations with strict compliance requirements, existing infrastructure teams, or very large data volumes.'),
    ...makeBlock('Don\'t let perfect be the enemy of good. A DRaaS solution tested quarterly is better than a self-built solution that nobody monitors. Start with what you can actually maintain, and upgrade over time.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: Can I switch from DRaaS to self-built later?', 'A: Yes, but it requires planning. You\'ll need to migrate your DR data from the provider\'s cloud to your own infrastructure. Plan for 2-4 weeks of transition time.'),
    ...makeFAQBlock('Q: What RTO/RPO can DRaaS achieve?', 'A: Most DRaaS providers offer RPO 15-60 minutes and RTO 15-60 minutes. Some premium providers (Zerto) can achieve RPO under 5 minutes with continuous replication.'),
    ...makeFAQBlock('Q: Is DRaaS secure enough for regulated industries?', 'A: Yes, if you choose a provider with SOC 2, ISO 27001, and industry-specific certifications. Verify data encryption (at rest and in transit) and data residency options.'),
    ...makeFAQBlock('Q: How do I evaluate DRaaS providers?', 'A: Check: (1) SLA guarantees for RTO/RPO, (2) Compliance certifications, (3) Local data center presence, (4) Support quality and response time, (5) Integration with your existing infrastructure.'),
  ]
};

const articles = [article19, article20, article21, article22];
(async () => {
  let success = 0;
  for (const article of articles) {
    const id = await createPost(article);
    if (id) success++;
  }
  console.log(`\nBatch 3 complete: ${success}/${articles.length} uploaded`);
})();
