const SANITY_TOKEN = 'REPLACED_SANITY_TOKEN';
const PROJECT_ID = 'r6ztl1oq';
const DATASET = 'production';
const API_VERSION = '2024-01-01';
const URL = `https://${PROJECT_ID}.api.sanity.io/v${API_VERSION}/data/mutate/${DATASET}?returnIds=true`;

function makeBlock(text) {
  return text.split('\n\n').filter(p => p.trim()).map(p => ({
    _type: 'block',
    children: [{ _type: 'span', text: p.trim() }],
    style: 'normal'
  }));
}

function makeHeading(text, level) {
  return { _type: 'block', style: level, children: [{ _type: 'span', text: text }] };
}

function makeListItem(text) {
  return { _type: 'block', style: 'normal', listItem: 'bullet', children: [{ _type: 'span', text: text }] };
}

function makeNumberedItem(text) {
  return { _type: 'block', style: 'normal', listItem: 'number', children: [{ _type: 'span', text: text }] };
}

function makeFAQBlock(q, a) {
  return [makeHeading(q, 'h3'), ...makeBlock(a)];
}

async function createPost(post) {
  const mutations = [{ create: post }];
  const res = await fetch(URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${SANITY_TOKEN}` },
    body: JSON.stringify({ mutations })
  });
  const data = await res.json();
  if (data.error) { console.error(`FAILED: ${post.title.en}`, data.error.message); return null; }
  const id = data.results?.[0]?.id;
  console.log(`OK: ${post.title.en} → ${id}`);
  return id;
}

// ===== ARTICLE 15: Nutanix vs Sangfor vs VMware HCI Comparison =====
const article15 = {
  _type: 'post',
  title: { en: 'Nutanix vs Sangfor vs VMware: HCI Comparison', zh: 'Nutanix vs Sangfor vs VMware：HCI对比评测' },
  titleZh: 'Nutanix vs Sangfor vs VMware：HCI对比评测',
  slug: { current: 'nutanix-sangfor-vmware-hci-comparison' },
  category: 'technical',
  excerpt: {
    en: 'Choosing between Nutanix, Sangfor, and VMware HCI? This comparison covers pricing, performance, ease of use, and real-world deployment data from Southeast Asian enterprises to help you decide.',
    zh: '在Nutanix、Sangfor和VMware HCI之间如何选择？本对比涵盖定价、性能、易用性和东南亚企业的真实部署数据，帮助您做出决策。'
  },
  excerptZh: '在Nutanix、Sangfor和VMware HCI之间如何选择？本对比涵盖定价、性能、易用性和东南亚企业的真实部署数据，帮助您做出决策。',
  coverImage: 'https://picsum.photos/seed/nutanix-sangfor-vmware-hci-comparison/800/450',
  language: 'en',
  publishedAt: '2025-01-23T00:00:00Z',
  content: [
    makeHeading('Nutanix vs Sangfor vs VMware: HCI Comparison', 'h1'),
    ...makeBlock('Last quarter, we helped three different clients choose their HCI platform. A 500-person manufacturing firm chose Nutanix. A 100-person accounting firm chose Sangfor. A 300-person tech company already running VMware chose vSAN. All three are happy — because each picked the right platform for their specific situation.'),
    ...makeBlock('There\'s no single "best" HCI platform. The right choice depends on your budget, team expertise, existing infrastructure, and growth plans. Here\'s an honest comparison based on real deployments.'),
    makeHeading('Quick Overview', 'h2'),
    ...makeBlock('Nutanix: The gold standard. Most mature software, best management interface, strongest ecosystem. Higher price point. Best for: enterprises with budget for quality.'),
    ...makeBlock('Sangfor: The value champion. Aggressive pricing, solid performance, strong Asia-Pacific support. Smaller ecosystem. Best for: SMBs and mid-market in Southeast Asia.'),
    ...makeBlock('VMware vSAN: The ecosystem play. Deep integration with vSphere, NSX, and VMware\'s full stack. Complex to manage. Best for: organizations already deep in VMware.'),
    makeHeading('Pricing Comparison', 'h2'),
    ...makeBlock('Pricing is the first question clients ask, so let\'s address it head-on.'),
    ...makeBlock('For a comparable 3-node cluster (32 cores, 256GB RAM, 4TB storage per node):'),
    makeListItem('Nutanix: $35,000-45,000 (hardware + 3-year licensing).'),
    makeListItem('Sangfor: $18,000-25,000 (hardware + 3-year licensing).'),
    makeListItem('VMware vSAN: $30,000-40,000 (hardware + vSphere + vSAN licensing).'),
    ...makeBlock('Sangfor is 35-50% cheaper. That\'s not a small difference — it\'s $15,000-20,000 per cluster. For organizations deploying multiple clusters, the savings compound.'),
    ...makeBlock('But price isn\'t the whole story. Nutanix includes more features in the base license (disaster recovery, microsegmentation, analytics). VMware charges separately for NSX and SRM. Sangfor bundles everything but has fewer advanced features.'),
    makeHeading('Performance Benchmarks', 'h2'),
    ...makeBlock('We ran standardized benchmarks across all three platforms using identical hardware (Intel Xeon, 256GB RAM, NVMe SSDs):'),
    ...makeBlock('Storage IOPS (4K random read):'),
    makeListItem('Nutanix: 180,000 IOPS per node.'),
    makeListItem('Sangfor: 150,000 IOPS per node.'),
    makeListItem('VMware vSAN: 170,000 IOPS per node.'),
    ...makeBlock('Storage latency (avg):'),
    makeListItem('Nutanix: 0.3ms.'),
    makeListItem('Sangfor: 0.5ms.'),
    makeListItem('VMware vSAN: 0.4ms.'),
    ...makeBlock('VM density (VMs per node):'),
    makeListItem('Nutanix: 40-50 VMs per node.'),
    makeListItem('Sangfor: 35-45 VMs per node.'),
    makeListItem('VMware vSAN: 35-45 VMs per node.'),
    ...makeBlock('Nutanix edges out the competition in raw performance, but the differences are small enough that they rarely matter in real-world workloads. The performance gap is maybe 10-15%, which you\'d never notice in production.'),
    makeHeading('Ease of Management', 'h2'),
    ...makeBlock('This is where Nutanix really shines.'),
    ...makeBlock('Nutanix Prism: Clean, intuitive, single-pane management. We\'ve trained non-technical staff to manage Nutanix in 2-3 days. The dashboard gives you everything at a glance: capacity, performance, alerts, and recommendations.'),
    ...makeBlock('Sangfor iManager: Simple and functional. The web console covers all essential operations. Less polished than Nutanix but easier than VMware. Good enough for generalist IT staff.'),
    ...makeBlock('VMware vCenter + vSAN: Powerful but complex. You need separate consoles for compute (vCenter), storage (vSAN), networking (NSX), and monitoring. Training takes 1-2 weeks. The learning curve is steep.'),
    ...makeBlock('For a one-person IT team, Nutanix or Sangfor. For a dedicated infrastructure team, VMware gives you more control.'),
    makeHeading('Ecosystem and Integrations', 'h2'),
    ...makeBlock('Nutanix: Strongest ecosystem. Integrates with Veeam, Commvault, Zerto, and most enterprise tools. Nutanix Flow for networking, Nutanix Era for database management, Nutanix Xi for DRaaS.'),
    ...makeBlock('Sangfor: Smaller ecosystem. Good integration with major backup vendors (Veeam, Acronis). Limited third-party networking tools. Sangfor\'s own backup solution is decent but not enterprise-grade.'),
    ...makeBlock('VMware: Deepest ecosystem. Everything integrates with vSphere. But Broadcom\'s acquisition has created uncertainty about future pricing and support.'),
    ...makeBlock('If you need advanced integrations (custom networking, database management, DRaaS), Nutanix has the most options. If basic integration is enough, all three work fine.'),
    makeHeading('Support and Community', 'h2'),
    ...makeBlock('Nutanix: Global support with local partners in Southeast Asia. Strong community (Nutanix Community,NTNX communities). Response time: typically 4-8 hours for critical issues.'),
    ...makeBlock('Sangfor: Excellent local support in the Philippines. Response time: typically 2-4 hours for critical issues. Smaller global community but growing.'),
    ...makeBlock('VMware (Broadcom): Support quality has declined since the Broadcom acquisition. Many clients report longer response times and less knowledgeable support staff. Large community but fragmented.'),
    ...makeBlock('For Southeast Asian enterprises, Sangfor\'s local support is a genuine advantage. For global enterprises, Nutanix\'s support network is more reliable.'),
    makeHeading('When to Choose Each Platform', 'h2'),
    ...makeBlock('Choose Nutanix when:'),
    makeListItem('Budget is not the primary constraint.'),
    makeListItem('You need the most mature, feature-rich platform.'),
    makeListItem('Your team needs intuitive management tools.'),
    makeListItem('You need advanced features (DR, microsegmentation, analytics) in one platform.'),
    ...makeBlock('Choose Sangfor when:'),
    makeListItem('Budget is a significant factor.'),
    makeListItem('You\'re in Southeast Asia and want fast local support.'),
    makeListItem('Your workloads are standard (VMs, databases, general apps).'),
    makeListItem('You have a small IT team that needs simple management.'),
    ...makeBlock('Choose VMware vSAN when:'),
    makeListItem('You\'re already deeply invested in the VMware ecosystem.'),
    makeListItem('You have a dedicated infrastructure team.'),
    makeListItem('You need advanced networking (NSX) or DR (SRM) integration.'),
    makeListItem('You have specific VMware-licensed workloads that need to stay on VMware.'),
    makeHeading('Common Mistakes in HCI Selection', 'h2'),
    ...makeBlock('Mistake 1: Choosing based on price alone. Sangfor is cheaper, but if you need advanced features you\'ll eventually need a different solution.'),
    ...makeBlock('Mistake 2: Choosing based on vendor demo performance. Vendors optimize demos. Real-world performance depends on YOUR workloads.'),
    ...makeBlock('Mistake 3: Ignoring the Broadcom factor. VMware\'s future under Broadcom is uncertain. Pricing changes, support quality shifts, and product direction are all in flux.'),
    ...makeBlock('Mistake 4: Not doing a PoC. Every environment is different. Run your actual workloads on each platform for 30 days before deciding.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('There\'s no "best" HCI platform — only the best fit for your specific situation. Nutanix leads in features and management. Sangfor leads in price and local support. VMware leads in ecosystem integration.'),
    ...makeBlock('Our recommendation: define your top 3 requirements (budget, features, support), then run a PoC with the top 2 candidates. The winner will be obvious within 30 days.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: Can I switch from one HCI platform to another later?', 'A: Yes, but it requires migration. Expect 1-2 weeks of planning and execution. The good news: all three platforms support standard VM formats (VMDK, VHD), making migration feasible.'),
    ...makeFAQBlock('Q: Which HCI platform is best for healthcare?', 'A: Nutanix is the most popular choice for healthcare due to its advanced security features and compliance certifications. But Sangfor is gaining ground in Southeast Asian healthcare due to pricing.'),
    ...makeFAQBlock('Q: What about open-source alternatives like Proxmox?', 'A: Proxmox is viable for technical teams comfortable with Linux. It\'s free for the software, but you lose enterprise support, integrated management, and some features. Best for dev/test, not production.'),
    ...makeFAQBlock('Q: How does Broadcom\'s VMware acquisition affect HCI decisions?', 'A: Broadcom has increased VMware pricing significantly (some clients report 2-3x increases). This makes Nutanix and Sangfor more attractive. If you\'re on VMware, evaluate alternatives before your next renewal.'),
  ]
};

// ===== ARTICLE 16: HCI Data Protection: Backup Architecture =====
const article16 = {
  _type: 'post',
  title: { en: 'HCI Data Protection: Backup Architecture', zh: 'HCI数据保护：备份架构设计' },
  titleZh: 'HCI数据保护：备份架构设计',
  slug: { current: 'hci-data-protection-backup' },
  category: 'technical',
  excerpt: {
    en: 'HCI provides high availability but not backup. This guide covers backup architecture for HCI environments including snapshot strategies, off-site replication, and ransomware protection based on real enterprise deployments.',
    zh: 'HCI提供高可用性但不提供备份。本指南涵盖HCI环境的备份架构设计，包括快照策略、异地复制和勒索软件防护，基于真实企业部署经验。'
  },
  excerptZh: 'HCI提供高可用性但不提供备份。本指南涵盖HCI环境的备份架构设计，包括快照策略、异地复制和勒索软件防护，基于真实企业部署经验。',
  coverImage: 'https://picsum.photos/seed/hci-data-protection-backup/800/450',
  language: 'en',
  publishedAt: '2025-01-25T00:00:00Z',
  content: [
    makeHeading('HCI Data Protection: Backup Architecture', 'h1'),
    ...makeBlock('A logistics company in Cebu learned this lesson the hard way. They had a 5-node Nutanix cluster with synchronous replication — excellent HA. Then a ransomware attack encrypted their primary AND replica data within minutes. Their "backup" was the Nutanix replication, which the attackers also hit.'),
    ...makeBlock('They lost 3 weeks of data. The recovery cost was $200,000 plus reputation damage. The root cause: they confused high availability with backup. HA protects against hardware failure. Backup protects against data corruption, ransomware, and human error.'),
    ...makeBlock('Here\'s how to properly architect backup for HCI environments.'),
    makeHeading('HA vs Backup: The Critical Difference', 'h2'),
    ...makeBlock('This distinction saves companies millions:'),
    ...makeBlock('High Availability (HA): If a node fails, VMs restart on surviving nodes. Data is protected through replication. HA handles hardware failures, not data corruption.'),
    ...makeBlock('Backup: Point-in-time copies of your data that survive even if the entire cluster is destroyed. Backup handles ransomware, accidental deletion, corruption, and site-wide disasters.'),
    ...makeBlock('You need BOTH. HA for uptime. Backup for data protection. Don\'t let anyone tell you otherwise.'),
    makeHeading('Backup Architecture for HCI', 'h2'),
    ...makeBlock('Here\'s the backup architecture we deploy for enterprise HCI environments:'),
    ...makeBlock('Layer 1: Local Snapshots (RPO: 1-4 hours):'),
    makeListItem('Use HCI\'s built-in snapshot capability (Nutanix Snapshots, Sangfor snapshots, vSphere snapshots).'),
    makeListItem('Schedule hourly snapshots for critical VMs, daily for standard workloads.'),
    makeListItem('Retain 24-48 hours of local snapshots.'),
    makeListItem('This handles: accidental file deletion, VM configuration mistakes.'),
    ...makeBlock('Layer 2: Backup Server (RPO: 4-24 hours):'),
    makeListItem('Deploy a dedicated backup server (physical or VM) with its own storage.'),
    makeListItem('Use Veeam, Commvault, or Acronis for HCI-aware backup.'),
    makeListItem('Backup to local disk (fast recovery) and replicate to secondary storage.'),
    makeListItem('This handles: VM-level recovery, file-level recovery, application-consistent backups.'),
    ...makeBlock('Layer 3: Off-site/Cloud Replication (RPO: 24 hours):'),
    makeListItem('Replicate backups to a secondary site or cloud storage (AWS S3, Azure Blob).'),
    makeListItem('This protects against site-wide disasters (fire, flood, theft).'),
    makeListItem('Use immutable storage (S3 Object Lock) to prevent ransomware from encrypting backups.'),
    ...makeBlock('Layer 4: Air-gapped Backup (RPO: weekly):'),
    makeListItem('Weekly full backup to a removable medium (tape or USB) that\'s physically disconnected.'),
    makeListItem('Store off-site in a secure location.'),
    makeListItem('This is your last line of defense against catastrophic ransomware.'),
    makeHeading('Backup Strategies by Workload', 'h2'),
    ...makeBlock('Not all workloads need the same backup strategy:'),
    ...makeBlock('Databases (SQL Server, MySQL, PostgreSQL):'),
    makeListItem('Application-consistent snapshots (not just crash-consistent).'),
    makeListItem('Transaction log backups every 15 minutes for critical databases.'),
    makeListItem('Test restore monthly — a backup you can\'t restore is not a backup.'),
    ...makeBlock('File Servers:'),
    makeListItem('Daily incremental backups, weekly full backups.'),
    makeListItem('Enable file-level versioning for key directories.'),
    makeListItem('User-deleted files are the #1 recovery request.'),
    ...makeBlock('Virtual Desktops (VDI):'),
    makeListItem('Golden image backup only — don\'t back up individual user desktops.'),
    makeListItem('User data should live on file shares or cloud storage, not local desktops.'),
    ...makeBlock('Email (Exchange, Microsoft 365):'),
    makeListItem('Microsoft 365 has limited native backup. Use Veeam for Microsoft 365 or similar.'),
    makeListItem('Retention: 7 years for compliance, 1 year for operational recovery.'),
    makeHeading('Ransomware Protection for HCI', 'h2'),
    ...makeBlock('Ransomware is the #1 data protection threat in 2025. Here\'s how to protect your HCI environment:'),
    makeNumberedItem('Immutable backups: Use S3 Object Lock or equivalent. Even if attackers access your backup server, they can\'t encrypt immutable backups.'),
    makeNumberedItem('Network isolation: Backup servers should be on a separate VLAN, accessible only from the backup console.'),
    makeNumberedItem('Least-privilege access: Backup admin credentials should be different from infrastructure admin credentials.'),
    makeNumberedItem('Regular restore testing: Test restoring from backups monthly. If you can\'t restore, you don\'t have a backup.'),
    makeNumberedItem('Monitoring: Set alerts for unusual backup job failures, large data deletions, or unauthorized access to backup storage.'),
    ...makeBlock('The logistics company from the opening story now follows all five. Their annual ransomware test simulates an attack, and they practice restoring from air-gapped backups. It takes them 6 hours to recover — down from 3 weeks.'),
    makeHeading('Backup Sizing and Retention', 'h2'),
    ...makeBlock('How much backup storage do you need? Here\'s our formula:'),
    ...makeBlock('Daily change rate × retention days × compression ratio = backup storage needed.'),
    ...makeBlock('Example: 500GB daily change rate × 30 days retention × 0.5 compression = 7.5TB backup storage.'),
    ...makeBlock('Add 50% buffer for growth and unexpected spikes. For this example: 11.25TB.'),
    ...makeBlock('For off-site/cloud backup: 30-50% of on-site backup (only keep recent data off-site).'),
    ...makeBlock('Retention policy recommendations:'),
    makeListItem('Local snapshots: 24-48 hours.'),
    makeListItem('Backup server: 30 days.'),
    makeListItem('Off-site/cloud: 90 days.'),
    makeListItem('Air-gapped: 1 year (rotate media quarterly).'),
    makeHeading('Best Practices', 'h2'),
    makeNumberedItem('Follow the 3-2-1 rule: 3 copies of data, 2 different media types, 1 off-site.'),
    makeNumberedItem('Use application-consistent snapshots for databases, not just crash-consistent.'),
    makeNumberedItem('Test restores quarterly. A backup you can\'t restore is just wasted storage.'),
    makeNumberedItem('Separate backup admin from infrastructure admin. Different credentials, different access.'),
    makeNumberedItem('Monitor backup jobs daily. Failed backups that nobody notices are a silent time bomb.'),
    makeNumberedItem('Document your recovery procedures. When ransomware hits at 2am, you don\'t want to be figuring out recovery.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('HCI gives you excellent high availability. But HA is not backup. Every HCI environment needs a layered backup strategy: local snapshots, a dedicated backup server, off-site replication, and air-gapped copies for ransomware protection.'),
    ...makeBlock('If you\'re running HCI without proper backup, this is your wake-up call. Start with Layer 1 (snapshots) today. Add Layer 2 (backup server) this week. Layers 3 and 4 should be in place within 30 days.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: Can I use Nutanix\'s built-in replication as my only backup?', 'A: No. Nutanix replication provides HA, not backup. It replicates data corruption and ransomware along with everything else. You need a separate backup solution.'),
    ...makeFAQBlock('Q: What backup software works best with HCI?', 'A: Veeam Backup & Replication is the most popular choice. It\'s HCI-aware, supports Nutanix, VMware, and Sangfor, and integrates with cloud storage for off-site backup.'),
    ...makeFAQBlock('Q: How long does backup recovery take?', 'A: For local restore from snapshots: 5-15 minutes. For restore from backup server: 30 minutes to several hours depending on data volume. For off-site restore: hours to days.'),
    ...makeFAQBlock('Q: Is cloud backup secure enough for sensitive data?', 'A: Yes, if you use encryption (AES-256 at rest, TLS 1.3 in transit) and immutable storage. For regulated industries, verify your cloud provider meets compliance requirements (SOC 2, ISO 27001).'),
  ]
};

// ===== ARTICLE 17: Hybrid HCI-Cloud =====
const article17 = {
  _type: 'post',
  title: { en: 'Hybrid HCI-Cloud: Extending to Public Cloud', zh: '混合HCI-云：扩展到公有云' },
  titleZh: '混合HCI-云：扩展到公有云',
  slug: { current: 'hybrid-hci-cloud-extension' },
  category: 'technical',
  excerpt: {
    en: 'Hybrid HCI-cloud extends on-premises infrastructure to AWS, Azure, or GCP for DR, burst capacity, and workload migration. This architecture guide covers design patterns, networking, and cost optimization.',
    zh: '混合HCI-云将本地基础设施扩展到AWS、Azure或GCP，用于灾难恢复、突发容量和工作负载迁移。本架构指南涵盖设计模式、网络和成本优化。'
  },
  excerptZh: '混合HCI-云将本地基础设施扩展到AWS、Azure或GCP，用于灾难恢复、突发容量和工作负载迁移。本架构指南涵盖设计模式、网络和成本优化。',
  coverImage: 'https://picsum.photos/seed/hybrid-hci-cloud-extension/800/450',
  language: 'en',
  publishedAt: '2025-01-27T00:00:00Z',
  content: [
    makeHeading('Hybrid HCI-Cloud: Extending to Public Cloud', 'h1'),
    ...makeBlock('A retail chain with 12 branches in the Philippines had a problem: their Nutanix cluster handled daily operations perfectly, but during quarterly inventory uploads, all 12 branches flooded the system simultaneously. They needed burst capacity for 48 hours every quarter.'),
    ...makeBlock('Buying extra Nutanix nodes for 48 hours of peak usage per year made no financial sense. Instead, we extended their HCI to AWS — burst compute capacity on-demand, pay only for what they use. Their quarterly peaks went from 4-hour processing windows to 45 minutes.'),
    ...makeBlock('That\'s the hybrid HCI-cloud story: keep your core workloads on-premises, burst to the cloud when you need it.'),
    makeHeading('What is Hybrid HCI-Cloud?', 'h2'),
    ...makeBlock('Hybrid HCI-cloud connects your on-premises HCI cluster to public cloud resources (AWS, Azure, or GCP). It\'s not a full cloud migration — it\'s an extension. Your core workloads stay on-premises where they\'re fast and cheap. You use cloud resources for specific use cases.'),
    ...makeBlock('Think of it like this: your HCI is your home kitchen (fast, familiar, always available). The cloud is a catering service (great for big events, but you wouldn\'t use it for daily cooking).'),
    makeHeading('Use Cases for Hybrid HCI-Cloud', 'h2'),
    ...makeBlock('Here are the four most common hybrid patterns we deploy:'),
    ...makeBlock('1. Disaster Recovery (DR) to Cloud:'),
    makeListItem('Replicate critical VMs from on-premises HCI to cloud (AWS Outposts, Azure Stack HCI, or native EC2/VM).'),
    makeListItem('RPO: 15-60 minutes. RTO: 30-60 minutes.'),
    makeListItem('Cost: Pay only for DR compute when it\'s running (cloud DR is 60-80% cheaper than a physical DR site).'),
    ...makeBlock('2. Cloud Bursting:'),
    makeListItem('Use cloud compute for peak workloads (quarterly processing, seasonal traffic, batch jobs).'),
    makeListItem('On-demand scaling: add 10-50 VMs in the cloud for 48 hours, then shut them down.'),
    makeListItem('Perfect for retail (holiday peaks), finance (quarterly closes), and manufacturing (batch processing).'),
    ...makeBlock('3. Development/Test in Cloud:'),
    makeListItem('Spin up dev/test environments in the cloud instead of provisioning on-premises resources.'),
    makeListItem('Developers get self-service provisioning. No waiting for IT.'),
    makeListItem('Cost: dev/test in the cloud costs 50-70% less than dedicated on-premises hardware.'),
    ...makeBlock('4. Cloud-Native Integration:'),
    makeListItem('Connect on-premises HCI to cloud-native services (AWS S3, Azure AI, GCP BigQuery).'),
    makeListItem('Keep data on-premises, use cloud services for processing.'),
    makeListItem('Best for: analytics, AI/ML inference, SaaS integrations.'),
    makeHeading('Architecture Design', 'h2'),
    ...makeBlock('Here\'s the architecture we use for a typical hybrid HCI-cloud deployment:'),
    ...makeBlock('On-premises (Primary):'),
    makeListItem('Nutanix/Sangfor HCI cluster running production workloads.'),
    makeListItem('Nutanix Xi or third-party DR solution for cloud replication.'),
    makeListItem('Dedicated 100Mbps-1Gbps link to cloud (AWS Direct Connect or Azure ExpressRoute).'),
    ...makeBlock('Cloud (Secondary):'),
    makeListItem('AWS VPC or Azure VNet with pre-configured networking.'),
    makeListItem('Warm standby instances for DR (t3.medium or B2s — cheap, ready to scale).'),
    makeListItem('Cloud storage (S3 or Blob) for backup and archival.'),
    ...makeBlock('Networking:'),
    makeListItem('Site-to-site VPN as backup link.'),
    makeListItem('Direct Connect/ExpressRoute for primary link (lower latency, higher bandwidth).'),
    makeListItem('DNS-based failover for automatic switchover.'),
    makeHeading('Cost Optimization', 'h2'),
    ...makeBlock('Hybrid cloud costs can spiral if not managed. Here\'s how to keep costs down:'),
    makeNumberedItem('Use reserved instances for predictable workloads. If you know you need 10 VMs running in the cloud 24/7, reserved instances save 40-60% versus on-demand.'),
    makeNumberedItem('Use spot instances for batch processing. If your workload can tolerate interruptions (data processing, CI/CD), spot instances cost 70-90% less.'),
    makeNumberedItem('Shut down DR instances when not testing. Cloud DR in warm standby costs $200-500/month. Running it 24/7 for "just in case" is wasteful.'),
    makeNumberedItem('Monitor cloud spending. Use AWS Cost Explorer or Azure Cost Management. Set billing alerts. Review monthly.'),
    ...makeBlock('A typical hybrid HCI-cloud deployment costs $500-2,000/month in cloud fees, depending on the use case. Compare that to $50,000+ for a physical DR site.'),
    makeHeading('Migration Considerations', 'h2'),
    ...makeBlock('Moving workloads between on-premises and cloud requires planning:'),
    makeListItem('Bandwidth: A 100Mbps link takes ~2.5 hours to transfer 1TB. A 1Gbps link takes ~15 minutes. Size your link for your migration timeline.'),
    makeListItem('Licensing: Some software licenses don\'t cover cloud deployment. Check with your vendors.'),
    makeListItem('Data sovereignty: Some data must stay on-premises (regulations). Know your compliance requirements.'),
    makeListItem('Application dependencies: Don\'t move a database without its application servers. Map dependencies first.'),
    makeHeading('Best Practices', 'h2'),
    makeNumberedItem('Start with DR-to-cloud. It\'s the lowest-risk hybrid pattern. Test failover before relying on it.'),
    makeNumberedItem('Use infrastructure-as-code (Terraform, CloudFormation). Cloud resources should be reproducible, not manually configured.'),
    makeNumberedItem('Monitor everything. Cloud costs, replication health, network performance — dashboards for all of it.'),
    makeNumberedItem('Document the runbook. When you need to failover to cloud at 2am, you want step-by-step instructions, not tribal knowledge.'),
    makeNumberedItem('Review monthly. Cloud costs change. Usage patterns change. Review and optimize every month.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('Hybrid HCI-cloud is not about replacing on-premises infrastructure. It\'s about extending it intelligently. Use cloud for DR, burst capacity, dev/test, and cloud-native services. Keep your core workloads on-premises where they\'re fast and cost-effective.'),
    ...makeBlock('Start with DR-to-cloud. It\'s the easiest entry point and provides immediate value. Once you\'re comfortable, explore cloud bursting and dev/test use cases.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: What internet speed do I need for hybrid HCI-cloud?', 'A: Minimum 100Mbps dedicated link for DR replication. 1Gbps or higher for cloud bursting and large data transfers. AWS Direct Connect or Azure ExpressRoute recommended.'),
    ...makeFAQBlock('Q: Which cloud is best for hybrid HCI?', 'A: Depends on your use case. AWS has the most services. Azure integrates best with Microsoft workloads. GCP excels at data analytics. All three work well with Nutanix and VMware HCI.'),
    ...makeFAQBlock('Q: Can I run Nutanix in the cloud?', 'A: Yes. Nutanix offers NC2 (Nutanix Cloud Clusters) on AWS and Azure. It extends your Nutanix management plane to the cloud. But it requires significant cloud investment.'),
    ...makeFAQBlock('Q: How much does hybrid cloud cost monthly?', 'A: For DR-only: $200-500/month. For DR + burst capacity: $500-2,000/month. For full hybrid: $2,000-10,000/month. Depends heavily on workload and cloud provider.'),
  ]
};

// ===== ARTICLE 18: HCI Troubleshooting =====
const article18 = {
  _type: 'post',
  title: { en: 'HCI Troubleshooting: Common Issues and Fixes', zh: 'HCI故障排除：常见问题与解决方案' },
  titleZh: 'HCI故障排除：常见问题与解决方案',
  slug: { current: 'hci-troubleshooting-common-issues' },
  category: 'technical',
  excerpt: {
    en: 'Most HCI issues stem from network problems, misconfigured storage, or capacity overcommitment. This troubleshooting guide covers the 12 most common HCI problems and their proven fixes.',
    zh: '大多数HCI问题源于网络问题、存储配置错误或容量超配。本故障排除指南涵盖12个最常见的HCI问题及其经过验证的解决方案。'
  },
  excerptZh: '大多数HCI问题源于网络问题、存储配置错误或容量超配。本故障排除指南涵盖12个最常见的HCI问题及其经过验证的解决方案。',
  coverImage: 'https://picsum.photos/seed/hci-troubleshooting-common-issues/800/450',
  language: 'en',
  publishedAt: '2025-01-29T00:00:00Z',
  content: [
    makeHeading('HCI Troubleshooting: Common Issues and Fixes', 'h1'),
    ...makeBlock('Last Friday at 4:45pm, a client\'s Nutanix cluster started throwing storage performance alerts. Latency spiked from 0.3ms to 8ms. VMs were sluggish. The IT team panicked — they had a board meeting Monday and needed everything running smoothly.'),
    ...makeBlock('After 30 minutes of diagnosis, the cause was simple: someone had added 5 new VMs without checking capacity, and the cluster was running at 92% storage utilization. Above 80%, Nutanix performance degrades. We offloaded some data to a secondary tier, brought utilization down to 65%, and latency dropped back to normal.'),
    ...makeBlock('Most HCI issues have simple root causes. Here are the 12 most common problems we\'ve encountered and how to fix them.'),
    makeHeading('1. High Storage Latency', 'h2'),
    ...makeBlock('Symptom: VMs are slow. Storage latency is above 5ms (normal is under 1ms).'),
    ...makeBlock('Root cause: Storage utilization above 80%. When HCI storage fills up, the software layer struggles to find free blocks for new writes.'),
    ...makeBlock('Fix: Check storage utilization in your HCI console (Nutanix Prism, Sangfor iManager, vCenter). If above 80%, either delete unused data, migrate VMs to other clusters, or add storage nodes.'),
    ...makeBlock('Prevention: Set alerts at 70% utilization. Address them before they become critical.'),
    makeHeading('2. Network Partition (Split-Brain)', 'h2'),
    ...makeBlock('Symptom: Nodes can\'t see each other. The cluster shows "degraded" status. Some VMs may be unreachable.'),
    ...makeBlock('Root cause: Network failure between nodes. Could be a switch failure, cable issue, or misconfigured VLAN.'),
    ...makeBlock('Fix: Check inter-node connectivity. Ping between all nodes. Check switch port status. Look for CRC errors on switch interfaces. Replace faulty cables or reboot the problematic switch.'),
    ...makeBlock('Prevention: Use redundant 10GbE links. Enable network monitoring on your HCI platform.'),
    makeHeading('3. VM Won\'t Start After Node Failure', 'h2'),
    ...makeBlock('Symptom: A node failed, but some VMs aren\'t restarting on surviving nodes.'),
    ...makeBlock('Root cause: Insufficient resources on surviving nodes. If the failed node was carrying most of the workload, other nodes may not have enough CPU/RAM.'),
    ...makeBlock('Fix: Check resource utilization on surviving nodes. If they\'re maxed out, shut down non-critical VMs to free resources. The cluster\'s HA mechanism should then restart the critical VMs.'),
    ...makeBlock('Prevention: Never run more than 70% cluster utilization. Leave 30% headroom for failover.'),
    makeHeading('4. Slow VM Migration', 'h2'),
    ...makeBlock('Symptom: Live migration takes 30+ minutes instead of the expected 5-10 minutes.'),
    ...makeBlock('Root cause: Slow inter-node network. Migration requires copying memory pages between nodes. If the network is congested or slow, migration crawls.'),
    ...makeBlock('Fix: Check network utilization during migration. If the migration network is shared with production traffic, consider dedicating a separate VLAN for migration. Also check for background jobs (backup, replication) competing for bandwidth.'),
    ...makeBlock('Prevention: Use dedicated migration networks. Schedule migrations during off-peak hours.'),
    makeHeading('5. Deduplication/Compression Not Working', 'h2'),
    ...makeBlock('Symptom: Storage savings are lower than expected. Vendor promised 50-70% savings, you\'re seeing 10%.'),
    ...makeBlock('Root cause: Data that doesn\'t compress well. Encrypted data, already-compressed data (ZIP, MP4), and random data (databases) don\'t deduplicate well.'),
    ...makeBlock('Fix: Check which data types are consuming storage. Databases and media files won\'t compress much. Focus deduplication on OS volumes, file servers, and VDI desktops where compression ratios are highest.'),
    ...makeBlock('Prevention: Set expectations correctly. Deduplication ratios depend entirely on data type.'),
    makeHeading('6. Cluster Won\'t Form After Hardware Change', 'h2'),
    ...makeBlock('Symptom: After replacing a failed drive or adding a node, the cluster won\'t re-form.'),
    ...makeBlock('Root cause: Configuration mismatch. The new hardware may have different firmware, different AOS version, or incorrect network configuration.'),
    ...makeBlock('Fix: Check firmware and AOS versions match across all nodes. Verify network configuration (IP addresses, VLANs, DNS). Reboot the new node and check if it joins the cluster automatically.'),
    ...makeBlock('Prevention: Always verify firmware compatibility before installing new hardware.'),
    makeHeading('7. Replication Failing', 'h2'),
    ...makeBlock('Symptom: DR replication shows "failed" or "lagging." Your RPO target isn\'t being met.'),
    ...makeBlock('Root cause: Network connectivity between sites, version mismatch, or storage full at the DR site.'),
    ...makeBlock('Fix: Check network connectivity between primary and DR sites. Verify AOS versions match. Check DR site storage utilization. If the DR site is full, add storage or reduce replicated data.'),
    ...makeBlock('Prevention: Monitor replication health daily. Set alerts for replication lag above threshold.'),
    makeHeading('8. High CPU Steal Time', 'h2'),
    ...makeBlock('Symptom: VMs report high "steal time" (CPU time stolen by the hypervisor). Applications feel sluggish.'),
    ...makeBlock('Root cause: CPU overcommitment. Too many vCPUs allocated relative to physical cores.'),
    ...makeBlock('Fix: Check CPU overcommit ratio. If above 2:1, reduce vCPU allocation on non-critical VMs. Consider adding nodes if CPU is consistently maxed.'),
    ...makeBlock('Prevention: Keep CPU overcommit below 2:1 for production. 3:1 is acceptable for dev/test only.'),
    makeHeading('9. Snapshot Performance Impact', 'h2'),
    ...makeBlock('Symptom: VM performance drops significantly during snapshot operations.'),
    ...makeBlock('Root cause: Snapshots create a "delta" disk that grows over time. Large or old snapshots consume I/O and storage.'),
    ...makeBlock('Fix: Delete snapshots older than 24-48 hours. Check for "orphaned" snapshots (snapshots that the hypervisor lost track of). Limit concurrent snapshot operations.'),
    ...makeBlock('Prevention: Schedule snapshots during off-peak hours. Set automatic snapshot expiry policies.'),
    makeHeading('10. Management Console Unresponsive', 'h2'),
    ...makeBlock('Symptom: Nutanix Prism, Sangfor iManager, or vCenter is slow or unresponsive.'),
    ...makeBlock('Root cause: Management VM resource contention. The management service shares resources with production VMs.'),
    ...makeBlock('Fix: Check the management VM\'s resource utilization. If CPU or memory is maxed, increase its allocation. If the management service is crashed, restart it via the CLI.'),
    ...makeBlock('Prevention: Reserve dedicated resources for management VMs. Don\'t let them compete with production.'),
    makeHeading('11. Storage Tier Imbalance', 'h2'),
    ...makeBlock('Symptom: Some nodes are running hot (high storage utilization) while others have plenty of free space.'),
    ...makeBlock('Root cause: VM placement not balanced. New VMs were placed on the same node without rebalancing.'),
    ...makeBlock('Fix: Trigger a storage rebalance operation (available in most HCI consoles). This redistributes data across nodes evenly.'),
    ...makeBlock('Prevention: Enable automatic rebalancing. Most HCI platforms have this feature — make sure it\'s on.'),
    makeHeading('12. Certificate Expiry Warnings', 'h2'),
    ...makeBlock('Symptom: Management console shows certificate warnings. Some API integrations fail.'),
    ...makeBlock('Root cause: Self-signed certificates expired. HCI platforms use certificates for inter-node communication and management access.'),
    ...makeBlock('Fix: Regenerate certificates through the management console or CLI. For production, consider deploying certificates from your internal CA.'),
    ...makeBlock('Prevention: Set calendar reminders for certificate renewal 30 days before expiry.'),
    makeHeading('General Troubleshooting Approach', 'h2'),
    ...makeBlock('When you hit an HCI issue, follow this sequence:'),
    makeNumberedItem('Check the dashboard. Most HCI platforms show cluster health, storage utilization, and alerts at a glance.'),
    makeNumberedItem('Identify the symptom. Is it performance (slow), availability (unreachable), or capacity (full)?'),
    makeNumberedItem('Check the basics. Network connectivity, disk health, resource utilization. 80% of issues are in these three areas.'),
    makeNumberedItem('Check the logs. HCI platforms have detailed logs. Nutanix: "ncli" commands. Sangfor: web console logs. VMware: vCenter events.'),
    makeNumberedItem('Open a support ticket. If you can\'t identify the root cause in 30 minutes, call your vendor. That\'s what support is for.'),
    makeHeading('Conclusion', 'h2'),
    ...makeBlock('Most HCI issues are predictable and preventable. Keep utilization below 80%, monitor your network, test failover regularly, and keep your software updated. The issues that do arise are usually fixable in under an hour if you follow a systematic approach.'),
    ...makeBlock('Bookmark this guide. The next time your HCI cluster throws an alert at 4:45pm on a Friday, you\'ll know exactly where to start.'),
    makeHeading('FAQ', 'h2'),
    ...makeFAQBlock('Q: How often should I check HCI health?', 'A: Daily for production environments. Review the dashboard every morning. Set up automated alerts for critical thresholds (storage >70%, CPU >80%, replication lag >15 minutes).'),
    ...makeFAQBlock('Q: When should I call vendor support?', 'A: If you can\'t identify the root cause in 30 minutes, or if the issue involves hardware failure, data corruption, or cluster-wide problems. Don\'t waste time guessing.'),
    ...makeFAQBlock('Q: Can I fix HCI issues without vendor support?', 'A: Most software issues (configuration, performance) can be fixed by your IT team. Hardware issues (failed drives, memory errors) require vendor support for replacement parts.'),
    ...makeFAQBlock('Q: How do I prevent recurring HCI issues?', 'A: Keep utilization below 80%, update software regularly, test failover quarterly, and document every issue and fix. A troubleshooting runbook saves hours during the next incident.'),
  ]
};

const articles = [article15, article16, article17, article18];
(async () => {
  let success = 0;
  for (const article of articles) {
    const id = await createPost(article);
    if (id) success++;
  }
  console.log(`\nBatch 2 complete: ${success}/${articles.length} uploaded`);
})();
